In [1]:
import pandas as pd
import numpy as np
import datetime
from dateutil.relativedelta import *

In [2]:
form13f = pd.read_csv("../RebellionData/rebellion_databases/form13f.csv", sep=";")

In [3]:
form13f["iFILING_DATE"]= pd.to_datetime(form13f["iFILING_DATE"]).dt.date
form13f["iPERIOD_END"]= pd.to_datetime(form13f["iPERIOD_END"]).dt.date

In [4]:
form13f

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iAMEND,iRESTATEMENT,iTYPE,iQTY,iMARKET_VALUE,iLONG_FRACTION
0,4443748,216235,055622104,1999-09-30,2000-01-03,0,0,0,28287.0,3134550.0,0.009282
1,4443749,216235,020039103,1999-09-30,2000-01-03,0,0,0,79199.0,5690620.0,0.016851
2,4443750,216235,713448108,1999-09-30,2000-01-03,0,0,0,186140.0,5795950.0,0.017163
3,4443751,216235,002824100,1999-09-30,2000-01-03,0,0,0,169555.0,6290420.0,0.018627
4,4443752,216235,05964H105,1999-09-30,2000-01-03,0,0,0,16897.0,174250.0,0.000516
...,...,...,...,...,...,...,...,...,...,...,...
57569231,74561590,1730479,039483102,2020-03-31,2020-04-23,0,0,0,300.0,11000.0,0.000086
57569232,74561591,1730479,88160R101,2020-03-31,2020-04-23,0,0,0,25.0,13000.0,0.000102
57569233,74561592,1730479,921937793,2020-03-31,2020-04-23,0,0,0,230.0,25000.0,0.000196
57569234,74561593,1730479,863667101,2020-03-31,2020-04-23,0,0,0,1030.0,171000.0,0.001341
57569235,74561594,1730479,232806109,2020-03-31,2020-04-23,0,0,0,100.0,2000.0,0.000016

# Set the current (training) period: CHANGE THIS !!!

In [5]:
PERIOD_TRAIN = datetime.date(2018,6,30)
PERIOD_TRAIN

datetime.date(2018, 6, 30)

# I. Data Processing

## Filter individual records

1. Remove records that were filed before June 30, 2013 with iPERIOD_END later than PERIOD_TRAIN

In [6]:
form13f_2013 = form13f[(form13f.iFILING_DATE >= datetime.date(2013, 6, 30)) & (form13f.iPERIOD_END <= PERIOD_TRAIN)]
form13f_2013

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iAMEND,iRESTATEMENT,iTYPE,iQTY,iMARKET_VALUE,iLONG_FRACTION
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,0,0,0,96510.0,3366000.0,0.023443
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,0,0,0,70214.0,5249000.0,0.036557
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,0,0,0,346115.0,15471000.0,0.107748
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,0,0,0,882340.0,11347000.0,0.079026
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,0,0,0,129065.0,3620000.0,0.025212
...,...,...,...,...,...,...,...,...,...,...,...
57510142,74502501,948046,46429B598,2018-06-30,2020-04-21,1,0,0,147975.0,4926000.0,0.000000
57510143,74502502,948046,141633107,2018-06-30,2020-04-21,1,0,0,186939.0,3903000.0,0.000000
57510144,74502503,948046,33740F888,2018-06-30,2020-04-21,1,0,0,400000.0,10012000.0,0.000000
57510145,74502504,948046,398905109,2018-06-30,2020-04-21,1,0,0,173751.0,10946000.0,0.000000
57510146,74502505,948046,134429109,2018-06-30,2020-04-21,1,0,0,823699.0,33395000.0,0.000000

2. Remove records that are duplicates.
3. Remove records wherein QTY is zero.
4. Remove records wherein MARKET_VALUE is zero.

In [7]:
form13f_duplicate = form13f_2013.drop_duplicates()
form13f_QTY = form13f_duplicate[form13f_duplicate["iQTY"] != 0]
form13f_MARKET_VALUE = form13f_QTY[form13f_QTY["iMARKET_VALUE"] != 0]
form13f_MARKET_VALUE["FILING_INTERVAL"] = form13f_MARKET_VALUE["iFILING_DATE"]-form13f_MARKET_VALUE["iPERIOD_END"]
form13f_MARKET_VALUE

/var/folders/gd/f9gfs56x5qgb9q0h_h7dwwrc0000gn/T/ipykernel_4899/4067883774.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  form13f_MARKET_VALUE["FILING_INTERVAL"] = form13f_MARKET_VALUE["iFILING_DATE"]-form13f_MARKET_VALUE["iPERIOD_END"]

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iAMEND,iRESTATEMENT,iTYPE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,0,0,0,96510.0,3366000.0,0.023443,32 days
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,0,0,0,70214.0,5249000.0,0.036557,32 days
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,0,0,0,346115.0,15471000.0,0.107748,32 days
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,0,0,0,882340.0,11347000.0,0.079026,32 days
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,0,0,0,129065.0,3620000.0,0.025212,32 days
...,...,...,...,...,...,...,...,...,...,...,...,...
57510142,74502501,948046,46429B598,2018-06-30,2020-04-21,1,0,0,147975.0,4926000.0,0.000000,661 days
57510143,74502502,948046,141633107,2018-06-30,2020-04-21,1,0,0,186939.0,3903000.0,0.000000,661 days
57510144,74502503,948046,33740F888,2018-06-30,2020-04-21,1,0,0,400000.0,10012000.0,0.000000,661 days
57510145,74502504,948046,398905109,2018-06-30,2020-04-21,1,0,0,173751.0,10946000.0,0.000000,661 days
57510146,74502505,948046,134429109,2018-06-30,2020-04-21,1,0,0,823699.0,33395000.0,0.000000,661 days

## Filter entire funds for each period

1. Funds must complete filing within 46 days of the end of the quarter.

In [8]:
# iCIK is fund identifier
form13f_46 = form13f_MARKET_VALUE.groupby(["iCIK", "iPERIOD_END"]).filter(lambda x:(x.FILING_INTERVAL <= datetime.timedelta(days = 45)).all())
form13f_46

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iAMEND,iRESTATEMENT,iTYPE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,0,0,0,96510.0,3366000.0,0.023443,32 days
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,0,0,0,70214.0,5249000.0,0.036557,32 days
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,0,0,0,346115.0,15471000.0,0.107748,32 days
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,0,0,0,882340.0,11347000.0,0.079026,32 days
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,0,0,0,129065.0,3620000.0,0.025212,32 days
...,...,...,...,...,...,...,...,...,...,...,...,...
50110418,67098553,1641864,422806208,2018-06-30,2018-08-13,0,0,0,531120.0,32372000.0,0.036413,44 days
50110419,67098554,1641864,143130102,2018-06-30,2018-08-13,0,0,0,1269870.0,92536000.0,0.104088,44 days
50110420,67098555,1641864,33829M101,2018-06-30,2018-08-13,0,0,0,11009.0,1076000.0,0.001210,44 days
50110421,67098556,1641864,570535104,2018-06-30,2018-08-13,0,0,0,37653.0,40829000.0,0.045926,44 days
50110422,67098557,1641864,112585104,2018-06-30,2018-08-13,0,0,0,13223.0,536000.0,0.000603,44 days

2. Funds must have exactly one filing point for each quarter i.e., remove funds with amendments.

In [9]:
# counterexample
form13f_46[(form13f_46["iCIK"] == 1536562) & (form13f_46["iPERIOD_END"] == datetime.date(2014,12,31))]

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iAMEND,iRESTATEMENT,iTYPE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26100887,50955873,1536562,438516106,2014-12-31,2015-02-02,0,0,0,9000.0,769000.0,0.020278,33 days
26100888,50955874,1536562,71654V101,2014-12-31,2015-02-02,0,0,0,98132.0,10440000.0,0.275295,33 days
26100889,50955875,1536562,05961W105,2014-12-31,2015-02-02,0,0,0,68521.0,3180000.0,0.083854,33 days
26100890,50955876,1536562,594918104,2014-12-31,2015-02-02,0,0,0,23000.0,1141000.0,0.030087,33 days
26100891,50955877,1536562,437076102,2014-12-31,2015-02-02,0,0,0,6200.0,626000.0,0.016507,33 days
26100892,50955878,1536562,81369Y407,2014-12-31,2015-02-02,0,0,0,16500.0,1163000.0,0.030667,33 days
26100893,50955879,1536562,03524A108,2014-12-31,2015-02-02,0,0,0,105428.0,11476000.0,0.302613,33 days
26100894,50955880,1536562,38259P706,2014-12-31,2015-02-02,0,0,0,3500.0,744000.0,0.019619,33 days
26100895,50955881,1536562,146229109,2014-12-31,2015-02-02,0,0,0,92790.0,8384000.0,0.221080,33 days
26119280,50974218,1536562,438516106,2014-12-31,2015-02-03,1,1,0,9000.0,899000.0,0.000000,34 days
26119281,50974219,1536562,879273209,2014-12-31,2015-02-03,1,1,0,16719.0,324000.0,0.000000,34 days
26119282,50974220,1536562,71654V101,2014-12-31,2015-02-03,1,1,0,98132.0,744000.0,0.000000,34 days
26119283,50974221,1536562,918204108,2014-12-31,2015-02-03,1,1,0,557479.0,41755000.0,0.000000,34 days
26119284,50974222,1536562,82481R106,2014-12-31,2015-02-03,1,1,0,21246.0,4516000.0,0.000000,34 days
26119285,50974223,1536562,88579Y101,2014-12-31,2015-02-03,1,1,0,500000.0,82160000.0,0.000000,34 days
26119286,50974224,1536562,07329M100,2014-12-31,2015-02-03,1,1,0,1826950.0,25194000.0,0.000000,34 days
26119287,50974225,1536562,78462F103,2014-12-31,2015-02-03,1,1,0,23343.0,4797000.0,0.000000,34 days
26119288,50974226,1536562,81369Y407,2014-12-31,2015-02-03,1,1,0,16500.0,1190000.0,0.000000,34 days
26119289,50974227,1536562,81369Y308,2014-12-31,2015-02-03,1,1,0,135580.0,6574000.0,0.000000,34 days
26119290,50974228,1536562,03524A108,2014-12-31,2015-02-03,1,1,0,105428.0,11842000.0,0.000000,34 days
26119291,50974229,1536562,38259P706,2014-12-31,2015-02-03,1,1,0,3500.0,1842000.0,0.000000,34 days
26119292,50974230,1536562,09247X101,2014-12-31,2015-02-03,1,1,0,9500.0,3397000.0,0.000000,34 days
26119293,50974231,1536562,05961W105,2014-12-31,2015-02-03,1,1,0,68521.0,2997000.0,0.000000,34 days
26119294,50974232,1536562,437076102,2014-12-31,2015-02-03,1,1,0,6200.0,651000.0,0.000000,34 days
26119295,50974233,1536562,037833100,2014-12-31,2015-02-03,1,1,0,5500.0,607000.0,0.000000,34 days
26119296,50974234,1536562,369550108,2014-12-31,2015-02-03,1,1,0,3300.0,454000.0,0.000000,34 days
26119297,50974235,1536562,57636Q104,2014-12-31,2015-02-03,1,1,0,33498.0,2886000.0,0.000000,34 days
26119298,50974236,1536562,832696405,2014-12-31,2015-02-03,1,1,0,2489.0,251000.0,0.000000,34 days
26119299,50974237,1536562,254687106,2014-12-31,2015-02-03,1,1,0,18000.0,1695000.0,0.000000,34 days
26119300,50974238,1536562,146229109,2014-12-31,2015-02-03,1,1,0,92790.0,8101000.0,0.000000,34 days
26119301,50974239,1536562,594918104,2014-12-31,2015-02-03,1,1,0,23000.0,1069000.0,0.000000,34 days
26119302,50974240,1536562,29244A102,2014-12-31,2015-02-03,1,1,0,10752.0,101000.0,0.000000,34 days
26119303,50974241,1536562,984245100,2014-12-31,2015-02-03,1,1,0,1911450.0,50596000.0,0.000000,34 days
26119304,50974242,1536562,254709108,2014-12-31,2015-02-03,1,1,0,4500.0,295000.0,0.000000,34 days
26119305,50974243,1536562,231021106,2014-12-31,2015-02-03,1,1,0,6400.0,923000.0,0.000000,34 days
26119306,50974244,1536562,693506107,2014-12-31,2015-02-03,1,1,0,8947.0,2068000.0,0.000000,34 days
26119307,50974245,1536562,615369105,2014-12-31,2015-02-03,1,1,0,13500.0,1293000.0,0.000000,34 days
26119308,50974246,1536562,478160104,2014-12-31,2015-02-03,1,1,0,10200.0,1067000.0,0.000000,34 days
26119309,50974247,1536562,767204100,2014-12-31,2015-02-03,1,1,0,212290.0,9779000.0,0.000000,34 days

In [10]:
# remove the whole fund for that filing period if amend/restate/type=1
form13f_amend = form13f_46.groupby(["iCIK", "iPERIOD_END"]).filter(lambda x:((x.iAMEND == 0)&(x.iRESTATEMENT == 0)&(x.iTYPE == 0)).all())
form13f_amend = form13f_amend.drop('iAMEND', axis=1)
form13f_amend = form13f_amend.drop('iRESTATEMENT', axis=1)
form13f_amend = form13f_amend.drop('iTYPE', axis=1)
form13f_amend

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,96510.0,3366000.0,0.023443,32 days
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,70214.0,5249000.0,0.036557,32 days
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,346115.0,15471000.0,0.107748,32 days
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,882340.0,11347000.0,0.079026,32 days
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,129065.0,3620000.0,0.025212,32 days
...,...,...,...,...,...,...,...,...,...
50110382,67098517,1641042,731094108,2018-06-30,2018-08-13,29000.0,683000.0,0.003574,44 days
50110383,67098518,1641042,85570W100,2018-06-30,2018-08-13,150000.0,5445000.0,0.028494,44 days
50110384,67098519,1641042,056752108,2018-06-30,2018-08-13,48222.0,11720000.0,0.061331,44 days
50110385,67098520,1641042,427746102,2018-06-30,2018-08-13,334331.0,12989000.0,0.067971,44 days
50110386,67098521,1641042,48248M102,2018-06-30,2018-08-13,331000.0,8225000.0,0.043041,44 days

3. Funds must have between 20 and 200 holdings.

In [11]:
form13f_20_200 = form13f_amend.groupby(["iCIK", "iPERIOD_END"]).filter(lambda x: ((20 <= len(x))&(len(x) <= 200)))
form13f_20_200

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,96510.0,3366000.0,0.023443,32 days
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,70214.0,5249000.0,0.036557,32 days
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,346115.0,15471000.0,0.107748,32 days
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,882340.0,11347000.0,0.079026,32 days
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,129065.0,3620000.0,0.025212,32 days
...,...,...,...,...,...,...,...,...,...
50110382,67098517,1641042,731094108,2018-06-30,2018-08-13,29000.0,683000.0,0.003574,44 days
50110383,67098518,1641042,85570W100,2018-06-30,2018-08-13,150000.0,5445000.0,0.028494,44 days
50110384,67098519,1641042,056752108,2018-06-30,2018-08-13,48222.0,11720000.0,0.061331,44 days
50110385,67098520,1641042,427746102,2018-06-30,2018-08-13,334331.0,12989000.0,0.067971,44 days
50110386,67098521,1641042,48248M102,2018-06-30,2018-08-13,331000.0,8225000.0,0.043041,44 days

4. Funds must be valued between 100M and 500M.

In [12]:
form13f_100_500 = form13f_20_200.groupby(["iCIK", "iPERIOD_END"]).filter(lambda x:((100000000 <= sum(x.iMARKET_VALUE))&(sum(x.iMARKET_VALUE) <= 500000000)))
form13f_100_500

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,96510.0,3366000.0,0.023443,32 days
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,70214.0,5249000.0,0.036557,32 days
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,346115.0,15471000.0,0.107748,32 days
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,882340.0,11347000.0,0.079026,32 days
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,129065.0,3620000.0,0.025212,32 days
...,...,...,...,...,...,...,...,...,...
50110382,67098517,1641042,731094108,2018-06-30,2018-08-13,29000.0,683000.0,0.003574,44 days
50110383,67098518,1641042,85570W100,2018-06-30,2018-08-13,150000.0,5445000.0,0.028494,44 days
50110384,67098519,1641042,056752108,2018-06-30,2018-08-13,48222.0,11720000.0,0.061331,44 days
50110385,67098520,1641042,427746102,2018-06-30,2018-08-13,334331.0,12989000.0,0.067971,44 days
50110386,67098521,1641042,48248M102,2018-06-30,2018-08-13,331000.0,8225000.0,0.043041,44 days

5. Funds had to meet all filtering criteria for at least one year -- Survival funds

In [13]:
form13f_1year = form13f_100_500.groupby("iCIK").filter(lambda x:(x.iPERIOD_END.nunique() >= 4))
form13f_1year

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,96510.0,3366000.0,0.023443,32 days
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,70214.0,5249000.0,0.036557,32 days
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,346115.0,15471000.0,0.107748,32 days
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,882340.0,11347000.0,0.079026,32 days
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,129065.0,3620000.0,0.025212,32 days
...,...,...,...,...,...,...,...,...,...
50110382,67098517,1641042,731094108,2018-06-30,2018-08-13,29000.0,683000.0,0.003574,44 days
50110383,67098518,1641042,85570W100,2018-06-30,2018-08-13,150000.0,5445000.0,0.028494,44 days
50110384,67098519,1641042,056752108,2018-06-30,2018-08-13,48222.0,11720000.0,0.061331,44 days
50110385,67098520,1641042,427746102,2018-06-30,2018-08-13,334331.0,12989000.0,0.067971,44 days
50110386,67098521,1641042,48248M102,2018-06-30,2018-08-13,331000.0,8225000.0,0.043041,44 days

In [14]:
print("number of survival funds:", len(form13f_1year["iCIK"].unique()))

number of survival funds: 1808

In [15]:
fund_stocks = form13f_1year["iCUSIP"].unique()
print(len(fund_stocks))
fund_stocks

17407

array(['002824100', '025816109', '026874784', ..., '86877M209',
       '30041R108', '83410S108'], dtype=object)

# II. FUND CLASSIFICATION AND FEATURE EXTRACTION

### 1. Industry Classification (correlation to sector ETFs)

In [16]:
prices = pd.read_csv("../RebellionData/rebellion_databases/prices.csv", sep=";")

In [17]:
prices["pSP_DATE"]= pd.to_datetime(prices["pSP_DATE"]).dt.date
prices.sort_values(by=["pSP_DATE"], inplace = True, ascending = True)

In [18]:
prices = prices[prices.pSP_DATE <= (PERIOD_TRAIN + datetime.timedelta(days=45))]

In [19]:
prices

,pSP_CUSIP,pSP_EXCHANGE,pSP_TICKER,pSP_DATE,pSP_VOLUME,pSP_OPEN,pSP_HIGH,pSP_LOW,pSP_CLOSE
9581087,73936Q405,N,PAO,2013-01-01,0,0.215,0.215,0.215,0.2150
9877577,73937B100,N,PKN,2013-01-01,0,46.700,46.700,46.700,46.6950
9882024,78464A805,N,TMW,2013-01-01,0,4.324,4.324,4.324,4.3240
9882494,73935X203,N,PWO,2013-01-01,0,24.640,24.640,24.640,24.6445
9583019,30304T106,N,FSG,2013-01-01,0,1.110,1.110,1.110,1.1120
...,...,...,...,...,...,...,...,...,...
25846775,055660104,PK,BPXXY,2018-08-14,0,10.350,10.350,10.350,10.3500
25818961,29272W109,N,ENR,2018-08-14,346337,63.370,64.080,63.370,63.5100
27414863,09057N300,OS,BPTH,2018-08-14,1335,29.400,30.598,28.000,28.2000
25832593,671044105,O,OSIS,2018-08-14,150875,78.800,79.755,78.480,79.3600
25825094,718546104,N,PSX,2018-08-14,2703145,121.930,122.000,120.130,120.9400

In [20]:
print("total number of stocks:", len(prices["pSP_CUSIP"].unique()))

total number of stocks: 29024

In [21]:
# prices of fund stocks
fund_prices = prices[prices["pSP_CUSIP"].isin(fund_stocks)]
len(fund_prices["pSP_CUSIP"].unique())

10073

In [22]:
XLF = prices.loc[prices["pSP_TICKER"] == "XLF" ]
XLY = prices.loc[prices["pSP_TICKER"] == "XLY" ]
XLK = prices.loc[prices["pSP_TICKER"] == "XLK" ]
XLB = prices.loc[prices["pSP_TICKER"] == "XLB" ]
XLI = prices.loc[prices["pSP_TICKER"] == "XLI" ]
XLE = prices.loc[prices["pSP_TICKER"] == "XLE" ]
XLU = prices.loc[prices["pSP_TICKER"] == "XLU" ]
XLV = prices.loc[prices["pSP_TICKER"] == "XLV" ]
XLP = prices.loc[prices["pSP_TICKER"] == "XLP" ]
VOX = prices.loc[prices["pSP_TICKER"] == "VOX" ]

In [23]:
print(len(XLF))
print(len(XLY))
print(len(XLK))
print(len(XLB))
print(len(XLI))
print(len(XLE))
print(len(XLU))
print(len(XLV))
print(len(XLP))
print(len(VOX))

1415
1415
1415
1415
1415
1415
1415
1415
1415
1415

In [24]:
XLF = XLF[XLF["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLY = XLY[XLY["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLK = XLK[XLK["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLB = XLB[XLB["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLI = XLI[XLI["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLE = XLE[XLE["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLU = XLU[XLU["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLV = XLV[XLV["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLP = XLP[XLP["pSP_DATE"].isin(VOX["pSP_DATE"])]

In [25]:
Etf_data = {'pSP_DATE':VOX["pSP_DATE"].values,
            'XLF':XLF["pSP_CLOSE"].values,
            'XLY':XLY["pSP_CLOSE"].values,
            'XLK':XLK["pSP_CLOSE"].values,
            'XLB':XLB["pSP_CLOSE"].values,
            'XLI':XLI["pSP_CLOSE"].values,
            'XLE':XLE["pSP_CLOSE"].values,
            'XLU':XLU["pSP_CLOSE"].values,
            'XLV':XLV["pSP_CLOSE"].values,
            'XLP':XLP["pSP_CLOSE"].values,
            'VOX':VOX["pSP_CLOSE"].values}

Etf_df = pd.DataFrame(Etf_data)
Etf_df

,pSP_DATE,XLF,XLY,XLK,XLB,XLI,XLE,XLU,XLV,XLP,VOX
0,2013-01-02,12.5558,45.5328,27.5843,35.2652,35.6120,66.0461,30.5576,38.1085,32.1762,63.7305
1,2013-01-03,12.5409,45.6456,27.4085,35.0086,35.6303,66.0280,30.5576,38.1554,32.0953,63.7931
2,2013-01-04,12.6897,45.8148,27.2974,35.4393,35.8964,66.7608,30.7123,38.3240,32.1852,64.2132
3,2013-01-07,12.6600,45.7020,27.2604,35.3660,35.7404,66.2451,30.4115,38.4458,31.9695,64.3651
4,2013-01-08,12.6228,45.5704,27.1586,35.4210,35.4652,66.0280,30.3170,38.4552,31.8796,63.3372
...,...,...,...,...,...,...,...,...,...,...,...
1410,2018-08-08,28.0255,112.0890,72.7892,59.2200,74.8967,73.7407,51.6824,89.0329,52.4541,85.6817
1411,2018-08-09,27.8582,112.5050,72.8189,59.5400,74.4837,73.0573,51.9165,88.9341,52.2975,86.4059
1412,2018-08-10,27.5334,111.5650,72.2353,58.6800,73.8248,73.5064,51.6922,88.5488,52.1018,85.8206
1413,2018-08-13,27.2676,111.0010,72.1364,58.0900,73.4708,72.5691,51.7605,88.5784,52.1018,85.6519
1414,2018-08-14,27.5235,112.0790,72.5815,58.5800,73.9821,72.7448,51.8678,88.9934,52.4638,86.4555

In [26]:
# ex. pSP_CUSIP == 032511107
x = fund_prices[fund_prices["pSP_CUSIP"] == "032511107" ]
joined = pd.merge(x, Etf_df, on = "pSP_DATE")
joined

,pSP_CUSIP,pSP_EXCHANGE,pSP_TICKER,pSP_DATE,pSP_VOLUME,pSP_OPEN,pSP_HIGH,pSP_LOW,pSP_CLOSE,XLF,XLY,XLK,XLB,XLI,XLE,XLU,XLV,XLP,VOX
0,032511107,N,APC,2013-01-02,4314603,75.75,76.080,74.7300,76.06,12.5558,45.5328,27.5843,35.2652,35.6120,66.0461,30.5576,38.1085,32.1762,63.7305
1,032511107,N,APC,2013-01-03,3098703,75.90,77.350,75.1600,76.33,12.5409,45.6456,27.4085,35.0086,35.6303,66.0280,30.5576,38.1554,32.0953,63.7931
2,032511107,N,APC,2013-01-04,3842372,76.59,78.480,76.4618,78.27,12.6897,45.8148,27.2974,35.4393,35.8964,66.7608,30.7123,38.3240,32.1852,64.2132
3,032511107,N,APC,2013-01-07,2744404,77.73,78.930,77.3500,78.25,12.6600,45.7020,27.2604,35.3660,35.7404,66.2451,30.4115,38.4458,31.9695,64.3651
4,032511107,N,APC,2013-01-08,3230932,77.83,78.860,77.2500,78.35,12.6228,45.5704,27.1586,35.4210,35.4652,66.0280,30.3170,38.4552,31.8796,63.3372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1410,032511107,N,APC,2018-08-08,8035300,64.15,65.490,63.9300,65.15,28.0255,112.0890,72.7892,59.2200,74.8967,73.7407,51.6824,89.0329,52.4541,85.6817
1411,032511107,N,APC,2018-08-09,6255602,65.40,66.480,65.0900,66.06,27.8582,112.5050,72.8189,59.5400,74.4837,73.0573,51.9165,88.9341,52.2975,86.4059
1412,032511107,N,APC,2018-08-10,6780722,65.79,67.225,65.7400,66.82,27.5334,111.5650,72.2353,58.6800,73.8248,73.5064,51.6922,88.5488,52.1018,85.8206
1413,032511107,N,APC,2018-08-13,3853999,66.66,67.345,66.1900,66.34,27.2676,111.0010,72.1364,58.0900,73.4708,72.5691,51.7605,88.5784,52.1018,85.6519
1414,032511107,N,APC,2018-08-14,3595448,67.15,67.380,66.5800,66.98,27.5235,112.0790,72.5815,58.5800,73.9821,72.7448,51.8678,88.9934,52.4638,86.4555

In [27]:
# ex cont.
joined[joined.columns[8:]].corr()

,pSP_CLOSE,XLF,XLY,XLK,XLB,XLI,XLE,XLU,XLV,XLP,VOX
pSP_CLOSE,1.000000,-0.511283,-0.595998,-0.565372,-0.390128,-0.533597,0.892259,-0.712940,-0.601508,-0.737222,-0.519862
XLF,-0.511283,1.000000,0.959828,0.976953,0.958412,0.985776,-0.255251,0.834339,0.900246,0.791328,0.652038
XLY,-0.595998,0.959828,1.000000,0.980265,0.910810,0.966076,-0.356133,0.870533,0.946787,0.854977,0.688922
XLK,-0.565372,0.976953,0.980265,1.000000,0.941433,0.976983,-0.315408,0.859714,0.908857,0.801796,0.633513
XLB,-0.390128,0.958412,0.910810,0.941433,1.000000,0.973937,-0.085366,0.812116,0.880655,0.752658,0.654521
XLI,-0.533597,0.985776,0.966076,0.976983,0.973937,1.000000,-0.240482,0.880302,0.922608,0.839170,0.720131
XLE,0.892259,-0.255251,-0.356133,-0.315408,-0.085366,-0.240482,1.000000,-0.449875,-0.378554,-0.496175,-0.216151
XLU,-0.712940,0.834339,0.870533,0.859714,0.812116,0.880302,-0.449875,1.000000,0.896648,0.957261,0.856279
XLV,-0.601508,0.900246,0.946787,0.908857,0.880655,0.922608,-0.378554,0.896648,1.000000,0.911357,0.738329
XLP,-0.737222,0.791328,0.854977,0.801796,0.752658,0.839170,-0.496175,0.957261,0.911357,1.000000,0.892175
VOX,-0.519862,0.652038,0.688922,0.633513,0.654521,0.720131,-0.216151,0.856279,0.738329,0.892175,1.000000

In [28]:
# ex cont.
joined[joined.columns[8:]].corr()["pSP_CLOSE"][1:]

XLF   -0.511283
XLY   -0.595998
XLK   -0.565372
XLB   -0.390128
XLI   -0.533597
XLE    0.892259
XLU   -0.712940
XLV   -0.601508
XLP   -0.737222
VOX   -0.519862
Name: pSP_CLOSE, dtype: float64

In [29]:
# group fund_prices data by pSP_CUSIP
# for every group, do merge and correlation
# calculate each stock's industry through a correlation script
stock_group = fund_prices.groupby("pSP_CUSIP")
sector_categories = pd.DataFrame(columns = ["iCUSIP", "sector"])
Headings = ["Financial", "Consumer Discretionary", "Technology", "Materials", "Industrial",
            "Energy", "Utilities", "Health Care", "Consumer Staples", "Communications"]

for i in fund_stocks:
    try:
        stock = stock_group.get_group(str(i))
        joined = pd.merge(stock, Etf_df, on = "pSP_DATE")
        sector = joined[joined.columns[8:]].corr()["pSP_CLOSE"][1:]
        sector_index = np.array(sector).argmax()
        sector_categories = sector_categories.append({'iCUSIP': i, 'sector':Headings[sector_index]}, ignore_index = True)
    except KeyError:
        sector_categories = sector_categories.append({'iCUSIP': i, 'sector':'NA'}, ignore_index = True)

In [30]:
sector_categories

          iCUSIP            sector
0      002824100        Technology
1      025816109         Materials
2      026874784  Consumer Staples
3      060505104         Financial
4      064058100         Financial
...          ...               ...
17402  05360L205    Communications
17403  05280R100         Utilities
17404  86877M209    Communications
17405  30041R108    Communications
17406  83410S108            Energy

[17407 rows x 2 columns]

In [31]:
form13f_sector = pd.merge(form13f_1year, sector_categories, on = "iCUSIP")
form13f_sector.sort_values(by=["iPERIOD_END", "iCIK", "sector"], inplace = True, ascending = True)
form13f_sector

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector
110010,39276322,7195,742718109,2013-06-30,2013-08-12,61112.0,4705000.0,0.020468,43 days,Communications
164917,39276303,7195,369604103,2013-06-30,2013-08-12,182959.0,4243000.0,0.018458,43 days,Communications
302628,39276331,7195,92343V104,2013-06-30,2013-08-12,94160.0,4740000.0,0.020620,43 days,Communications
213741,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary
286575,39276297,7195,22160K105,2013-06-30,2013-08-12,41274.0,4564000.0,0.019855,43 days,Consumer Discretionary
...,...,...,...,...,...,...,...,...,...,...
1655233,65812260,1721608,92189F445,2018-06-30,2018-07-13,49724.0,1212000.0,0.004417,13 days,NA
1657269,65812259,1721608,46434G772,2018-06-30,2018-07-13,260955.0,9394000.0,0.034237,13 days,NA
1255782,65812254,1721608,464288174,2018-06-30,2018-07-13,6167.0,482000.0,0.001757,13 days,Technology
1676712,65812273,1721608,46090E103,2018-06-30,2018-07-13,14237.0,2444000.0,0.008907,13 days,Technology
938338,65812274,1721608,464287739,2018-06-30,2018-07-13,107697.0,8678000.0,0.031628,13 days,Utilities

### 2. Value & Size Classification (correlation to Value and Size ETFs)

In [32]:
SPY = prices.loc[prices["pSP_TICKER"] == "SPY" ] # 1865
QQQ = prices[(prices["pSP_TICKER"] == "QQQ") & (prices["pSP_CUSIP"] == "46090E103") ] # 1865
IWD = prices.loc[prices["pSP_TICKER"] == "IWD" ] # 1865
IJH = prices.loc[prices["pSP_TICKER"] == "IJH" ] # 1856
IWP = prices.loc[prices["pSP_TICKER"] == "IWP" ] # 1857
IWS = prices.loc[prices["pSP_TICKER"] == "IWS" ] # 1865
IWM = prices.loc[prices["pSP_TICKER"] == "IWM" ] # 1865
IWO = prices.loc[prices["pSP_TICKER"] == "IWO" ] # 1865
VBR = prices.loc[prices["pSP_TICKER"] == "VBR" ] # 1865

In [33]:
print(len(SPY))
print(len(QQQ))
print(len(IWD))
print(len(IJH))
print(len(IWP))
print(len(IWS))
print(len(IWM))
print(len(IWO))
print(len(VBR))

1415
1415
1415
1415
1415
1415
1415
1415
1415

In [34]:
SPY = SPY[SPY["pSP_DATE"].isin(IJH["pSP_DATE"])]
QQQ = QQQ[QQQ["pSP_DATE"].isin(IJH["pSP_DATE"])]
IWD = IWD[IWD["pSP_DATE"].isin(IJH["pSP_DATE"])]
IWP = IWP[IWP["pSP_DATE"].isin(IJH["pSP_DATE"])]
IWS = IWS[IWS["pSP_DATE"].isin(IJH["pSP_DATE"])]
IWM = IWM[IWM["pSP_DATE"].isin(IJH["pSP_DATE"])]
IWO = IWO[IWO["pSP_DATE"].isin(IJH["pSP_DATE"])]
VBR = VBR[VBR["pSP_DATE"].isin(IJH["pSP_DATE"])]

In [35]:
Etf_data2 = {'pSP_DATE':SPY["pSP_DATE"].values,
             'SPY':SPY["pSP_CLOSE"].values,
             'QQQ':QQQ["pSP_CLOSE"].values,
             'IWD':IWD["pSP_CLOSE"].values,
             'IJH':IJH["pSP_CLOSE"].values,
             'IWP':IWP["pSP_CLOSE"].values,
             'IWS':IWS["pSP_CLOSE"].values,
             'IWM':IWM["pSP_CLOSE"].values,
             'IWO':IWO["pSP_CLOSE"].values,
             'VBR':VBR["pSP_CLOSE"].values}

Etf_df2 = pd.DataFrame(Etf_data2)
Etf_df2

,pSP_DATE,SPY,QQQ,IWD,IJH,IWP,IWS,IWM,IWO,VBR
0,2013-01-02,146.060,67.2000,67.8392,98.2093,61.8643,47.2322,81.8058,94.5759,69.0195
1,2013-01-03,145.734,66.8521,67.7392,98.2469,61.8547,47.2689,81.6173,94.5373,69.1488
2,2013-01-04,146.370,66.6300,68.2575,98.9322,62.2392,47.6732,82.2205,95.0677,69.6291
3,2013-01-07,145.969,66.6504,67.9574,98.6787,62.0662,47.4802,81.9094,94.9905,69.3058
4,2013-01-08,145.550,66.5200,67.7483,98.3971,61.9220,47.2322,81.8529,94.9713,69.1118
...,...,...,...,...,...,...,...,...,...,...
1410,2018-08-08,285.460,182.0200,123.8160,198.6080,130.9570,89.1317,166.1260,209.2600,137.9900
1411,2018-08-09,285.070,181.9100,123.5510,198.3800,131.1950,89.0629,166.5520,209.9860,137.8920
1412,2018-08-10,283.160,180.5200,122.6670,197.2620,130.5790,88.4434,166.0870,209.8770,137.1650
1413,2018-08-13,282.100,180.3200,121.9800,196.2330,129.9140,88.0108,165.1150,208.4540,136.4180
1414,2018-08-14,283.900,181.4500,122.7650,198.0440,131.0660,88.7285,166.7510,210.5630,137.6960

In [36]:
stock_group = fund_prices.groupby("pSP_CUSIP")
value_size_categories = pd.DataFrame(columns = ["iCUSIP", "value_size"])
Headings = ["Large-Cap Blend", "Large-Cap Growth", "Large-Cap Value", "MidCap Blend", "MidCap Growth",
            "MidCap Value", "Small-Cap Blend", "Small-Cap Growth", "Small-Cap Value"]

for i in fund_stocks:
    try:
        stock = stock_group.get_group(str(i))
        joined = pd.merge(stock, Etf_df2, on = "pSP_DATE")
        sector = joined[joined.columns[8:]].corr()["pSP_CLOSE"][1:]
        sector_index = np.array(sector).argmax()
        value_size_categories = value_size_categories.append({'iCUSIP': i, 'value_size':Headings[sector_index]}, ignore_index = True)
    except KeyError:
        value_size_categories = value_size_categories.append({'iCUSIP': i, 'value_size':'NA'}, ignore_index = True)

In [37]:
value_size_categories

          iCUSIP        value_size
0      002824100     MidCap Growth
1      025816109  Small-Cap Growth
2      026874784   Large-Cap Value
3      060505104   Small-Cap Blend
4      064058100   Large-Cap Blend
...          ...               ...
17402  05360L205  Large-Cap Growth
17403  05280R100   Small-Cap Value
17404  86877M209   Small-Cap Blend
17405  30041R108  Small-Cap Growth
17406  83410S108  Small-Cap Growth

[17407 rows x 2 columns]

In [38]:
form13f_value_size = pd.merge(form13f_sector, value_size_categories, on = "iCUSIP")
form13f_value_size.sort_values(by=["iPERIOD_END", "iCIK", "sector", "value_size"], inplace = True, ascending = True)
form13f_value_size

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size
0,39276322,7195,742718109,2013-06-30,2013-08-12,61112.0,4705000.0,0.020468,43 days,Communications,Large-Cap Value
21620,39276331,7195,92343V104,2013-06-30,2013-08-12,94160.0,4740000.0,0.020620,43 days,Communications,Large-Cap Value
10661,39276303,7195,369604103,2013-06-30,2013-08-12,182959.0,4243000.0,0.018458,43 days,Communications,MidCap Value
29832,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth
37004,39276297,7195,22160K105,2013-06-30,2013-08-12,41274.0,4564000.0,0.019855,43 days,Consumer Discretionary,Large-Cap Growth
...,...,...,...,...,...,...,...,...,...,...,...
1655232,65812260,1721608,92189F445,2018-06-30,2018-07-13,49724.0,1212000.0,0.004417,13 days,NA,NA
1657181,65812259,1721608,46434G772,2018-06-30,2018-07-13,260955.0,9394000.0,0.034237,13 days,NA,NA
1677147,65812273,1721608,46090E103,2018-06-30,2018-07-13,14237.0,2444000.0,0.008907,13 days,Technology,Large-Cap Growth
845372,65812254,1721608,464288174,2018-06-30,2018-07-13,6167.0,482000.0,0.001757,13 days,Technology,Small-Cap Growth
1336038,65812274,1721608,464287739,2018-06-30,2018-07-13,107697.0,8678000.0,0.031628,13 days,Utilities,MidCap Value

### 3. Performance (mean of funds' return as benchmark)

In [39]:
# closing price on filing date
form13f_close = pd.merge(form13f_value_size, fund_prices[["pSP_CLOSE","pSP_CUSIP","pSP_DATE"]],  how='left', left_on=["iCUSIP","iFILING_DATE"], right_on = ["pSP_CUSIP","pSP_DATE"])
form13f_close = form13f_close.iloc[:,:-2]
form13f_close

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE
0,39276322,7195,742718109,2013-06-30,2013-08-12,61112.0,4705000.0,0.020468,43 days,Communications,Large-Cap Value,81.6200
1,39276331,7195,92343V104,2013-06-30,2013-08-12,94160.0,4740000.0,0.020620,43 days,Communications,Large-Cap Value,49.6500
2,39276303,7195,369604103,2013-06-30,2013-08-12,182959.0,4243000.0,0.018458,43 days,Communications,MidCap Value,24.1915
3,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000
4,39276297,7195,22160K105,2013-06-30,2013-08-12,41274.0,4564000.0,0.019855,43 days,Consumer Discretionary,Large-Cap Growth,115.7300
...,...,...,...,...,...,...,...,...,...,...,...,...
1678608,65812260,1721608,92189F445,2018-06-30,2018-07-13,49724.0,1212000.0,0.004417,13 days,NA,NA,NaN
1678609,65812259,1721608,46434G772,2018-06-30,2018-07-13,260955.0,9394000.0,0.034237,13 days,NA,NA,NaN
1678610,65812273,1721608,46090E103,2018-06-30,2018-07-13,14237.0,2444000.0,0.008907,13 days,Technology,Large-Cap Growth,179.6100
1678611,65812254,1721608,464288174,2018-06-30,2018-07-13,6167.0,482000.0,0.001757,13 days,Technology,Small-Cap Growth,76.9032
1678612,65812274,1721608,464287739,2018-06-30,2018-07-13,107697.0,8678000.0,0.031628,13 days,Utilities,MidCap Value,79.4892

In [40]:
form13f_close["shares"] = form13f_close["iMARKET_VALUE"] / form13f_close["pSP_CLOSE"]
form13f_close

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE,shares
0,39276322,7195,742718109,2013-06-30,2013-08-12,61112.0,4705000.0,0.020468,43 days,Communications,Large-Cap Value,81.6200,57645.185004
1,39276331,7195,92343V104,2013-06-30,2013-08-12,94160.0,4740000.0,0.020620,43 days,Communications,Large-Cap Value,49.6500,95468.277946
2,39276303,7195,369604103,2013-06-30,2013-08-12,182959.0,4243000.0,0.018458,43 days,Communications,MidCap Value,24.1915,175392.183205
3,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000,62664.141414
4,39276297,7195,22160K105,2013-06-30,2013-08-12,41274.0,4564000.0,0.019855,43 days,Consumer Discretionary,Large-Cap Growth,115.7300,39436.619718
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678608,65812260,1721608,92189F445,2018-06-30,2018-07-13,49724.0,1212000.0,0.004417,13 days,NA,NA,NaN,NaN
1678609,65812259,1721608,46434G772,2018-06-30,2018-07-13,260955.0,9394000.0,0.034237,13 days,NA,NA,NaN,NaN
1678610,65812273,1721608,46090E103,2018-06-30,2018-07-13,14237.0,2444000.0,0.008907,13 days,Technology,Large-Cap Growth,179.6100,13607.260175
1678611,65812254,1721608,464288174,2018-06-30,2018-07-13,6167.0,482000.0,0.001757,13 days,Technology,Small-Cap Growth,76.9032,6267.619553
1678612,65812274,1721608,464287739,2018-06-30,2018-07-13,107697.0,8678000.0,0.031628,13 days,Utilities,MidCap Value,79.4892,109172.063626

In [41]:
form13f_close["FILING_INTERVAL"].astype('timedelta64[D]').mean() # mean filing interval

32.39370420698517

In [42]:
# assume filing interval is 32 days
# filing_3mos: previous filing date
# funds report完换股票
form13f_close["filing_3mos"] = form13f_close["iPERIOD_END"] - relativedelta(days=+60) # 31+30+31(previous period)-32(filing interval)
form13f_close

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE,shares,filing_3mos
0,39276322,7195,742718109,2013-06-30,2013-08-12,61112.0,4705000.0,0.020468,43 days,Communications,Large-Cap Value,81.6200,57645.185004,2013-05-01
1,39276331,7195,92343V104,2013-06-30,2013-08-12,94160.0,4740000.0,0.020620,43 days,Communications,Large-Cap Value,49.6500,95468.277946,2013-05-01
2,39276303,7195,369604103,2013-06-30,2013-08-12,182959.0,4243000.0,0.018458,43 days,Communications,MidCap Value,24.1915,175392.183205,2013-05-01
3,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000,62664.141414,2013-05-01
4,39276297,7195,22160K105,2013-06-30,2013-08-12,41274.0,4564000.0,0.019855,43 days,Consumer Discretionary,Large-Cap Growth,115.7300,39436.619718,2013-05-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678608,65812260,1721608,92189F445,2018-06-30,2018-07-13,49724.0,1212000.0,0.004417,13 days,NA,NA,NaN,NaN,2018-05-01
1678609,65812259,1721608,46434G772,2018-06-30,2018-07-13,260955.0,9394000.0,0.034237,13 days,NA,NA,NaN,NaN,2018-05-01
1678610,65812273,1721608,46090E103,2018-06-30,2018-07-13,14237.0,2444000.0,0.008907,13 days,Technology,Large-Cap Growth,179.6100,13607.260175,2018-05-01
1678611,65812254,1721608,464288174,2018-06-30,2018-07-13,6167.0,482000.0,0.001757,13 days,Technology,Small-Cap Growth,76.9032,6267.619553,2018-05-01
1678612,65812274,1721608,464287739,2018-06-30,2018-07-13,107697.0,8678000.0,0.031628,13 days,Utilities,MidCap Value,79.4892,109172.063626,2018-05-01

In [43]:
# closing price 2 months before period end
form13f_3mos = pd.merge(form13f_close, fund_prices[["pSP_CLOSE","pSP_CUSIP","pSP_DATE"]],  how='left', left_on=["iCUSIP","filing_3mos"], right_on = ["pSP_CUSIP","pSP_DATE"])
form13f_3mos = form13f_3mos.iloc[:,:-2]
form13f_3mos

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y
0,39276322,7195,742718109,2013-06-30,2013-08-12,61112.0,4705000.0,0.020468,43 days,Communications,Large-Cap Value,81.6200,57645.185004,2013-05-01,76.9900
1,39276331,7195,92343V104,2013-06-30,2013-08-12,94160.0,4740000.0,0.020620,43 days,Communications,Large-Cap Value,49.6500,95468.277946,2013-05-01,52.4000
2,39276303,7195,369604103,2013-06-30,2013-08-12,182959.0,4243000.0,0.018458,43 days,Communications,MidCap Value,24.1915,175392.183205,2013-05-01,22.0784
3,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000,62664.141414,2013-05-01,72.7600
4,39276297,7195,22160K105,2013-06-30,2013-08-12,41274.0,4564000.0,0.019855,43 days,Consumer Discretionary,Large-Cap Growth,115.7300,39436.619718,2013-05-01,108.2200
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678608,65812260,1721608,92189F445,2018-06-30,2018-07-13,49724.0,1212000.0,0.004417,13 days,NA,NA,NaN,NaN,2018-05-01,NaN
1678609,65812259,1721608,46434G772,2018-06-30,2018-07-13,260955.0,9394000.0,0.034237,13 days,NA,NA,NaN,NaN,2018-05-01,NaN
1678610,65812273,1721608,46090E103,2018-06-30,2018-07-13,14237.0,2444000.0,0.008907,13 days,Technology,Large-Cap Growth,179.6100,13607.260175,2018-05-01,162.7800
1678611,65812254,1721608,464288174,2018-06-30,2018-07-13,6167.0,482000.0,0.001757,13 days,Technology,Small-Cap Growth,76.9032,6267.619553,2018-05-01,78.1677
1678612,65812274,1721608,464287739,2018-06-30,2018-07-13,107697.0,8678000.0,0.031628,13 days,Utilities,MidCap Value,79.4892,109172.063626,2018-05-01,73.7377

In [44]:
# check nontrading date
p_date = fund_prices["pSP_DATE"].unique()
f_date = form13f_3mos[~form13f_3mos["filing_3mos"].isin(p_date)]["filing_3mos"].unique()
print(len(p_date))
print(len(f_date))
f_date

1449
5

array([datetime.date(2014, 11, 1), datetime.date(2015, 8, 1),
       datetime.date(2015, 11, 1), datetime.date(2016, 1, 31),
       datetime.date(2016, 5, 1)], dtype=object)

In [45]:
# check (so many) NaN
print(len(form13f_3mos[(form13f_3mos["pSP_CLOSE_y"].isna())]["iCIK"].unique()))
for i in form13f_3mos[(form13f_3mos["pSP_CLOSE_y"].isna())]["iCIK"].unique():
    f = form13f_3mos[(form13f_3mos["pSP_CLOSE_y"].isna()) & (form13f_3mos["iCIK"] == i) & (form13f_3mos["iPERIOD_END"] == datetime.date(2013,6,30))]
    print(i, len(f["iCUSIP"].unique()))

1778
18748 3
21175 5
65957 2
80835 1
84616 1
86312 1
101199 5
102212 2
312955 11
320376 23
712011 1
764112 1
774602 1
778963 28
779519 3
806097 12
809339 14
810672 20
810716 7
811360 1
811454 1
819535 1
846788 2
860189 1
860580 7
860645 10
860748 2
862853 20
866780 4
866995 1
868911 17
869367 9
872078 7
874791 5
878228 10
883790 12
884306 2
884310 12
884548 3
886920 18
894205 3
894300 1
898399 1
900169 8
902614 6
903064 18
911270 6
918504 14
919497 11
919530 2
920441 7
923469 1
924166 9
928204 5
928400 6
931328 1
932141 37
934745 17
937886 3
938506 2
938759 13
939791 5
939835 12
941560 5
943442 7
943712 5
945625 15
948985 15
1002152 14
1003279 5
1004744 1
1006435 1
1008877 4
1008895 34
1009950 1
1013234 4
1013701 5
1014306 2
1014315 3
1016150 1
1016683 17
1016972 6
1017115 5
1019231 2
1021117 32
1026303 1
1027799 2
1031972 7
1033974 2
1034012 1
1034188 27
1035912 12
1037558 7
1038661 29
1041241 1
1042063 6
1044924 2
1044929 17
1047339 15
1049648 3
1049650 40
1050417 3
1050463 22
1051042 5
1052174 1
1054233 8
1054425 1
1055544 14
1055954 3
1055963 40
1056516 41
1056519 4
1056821 10
1056827 1
1056868 11
1056958 7
1057395 48
1058949 5
1061187 5
1067532 21
1068840 2
1072843 1
1074027 27
1074273 5
1076964 1
1077148 24
1078246 3
1078635 13
1079373 2
1079397 1
1079738 10
1079930 3
1079935 3
1080071 3
1080132 9
1080166 34
1080173 1
1080197 6
1080201 1
1080351 9
1080523 24
1082339 24
1082482 8
1082491 62
1084207 2
1085163 2
1085227 4
1088731 17
1088859 4
1091961 7
1092290 39
1093276 1
1098062 2
1100916 94
1104366 9
1105344 9
1105468 7
1105471 3
1105871 1
1106505 17
1106544 1
1107211 7
1108893 3
1108965 3
1113303 1
1114702 1
1115373 2
1119254 30
1121477 136
1121908 14
1123320 2
1123798 5
1123812 8
1124841 6
1125727 7
1126735 2
1127544 25
1128213 4
1129770 3
1132356 34
1132556 1
1132708 15
1133653 76
1136704 3
1138486 42
1140468 5
1141455 2
1158583 3
1160099 1
1161822 7
1161825 3
1162781 4
1162827 46
1163902 1
1164062 37
1165805 6
1166308 1
1166385 12
1166402 9
1166620 11
1166716 42
1166741 7
1167026 7
1168889 3
1172779 11
1172799 22
1177018 10
1177043 7
1177132 4
1185072 2
1212225 1
1213206 5
1213310 1
1217675 1
1218179 4
1218254 5
1218555 3
1219062 4
1224014 14
1224890 3
1226779 3
1252007 17
1255435 23
1259671 5
1260468 10
1262677 16
1269786 9
1269950 6
1275124 2
1276525 1
1276853 6
1277158 5
1277537 5
1277779 3
1278641 2
1279708 13
1280051 61
1280577 5
1280604 1
1281011 18
1284208 2
1298596 1
1301540 1
1307203 4
1308001 2
1308523 9
1308778 16
1309148 1
1313978 5
1314404 9
1315269 1
1315889 26
1316393 1
1316729 1
1317103 4
1317209 32
1317346 18
1317733 19
1317802 17
1317829 22
1318259 1
1321194 3
1321219 19
1321993 6
1322924 11
1324022 2
1326766 6
1330463 8
1335851 3
1336098 31
1336800 1
1339270 38
1346378 1
1349353 1
1350290 2
1350312 1
1350780 8
1351407 1
1351841 4
1352122 1
1352306 41
1352449 9
1352776 17
1352871 1
1352900 1
1353318 1
1354739 1
1356202 3
1356407 10
1358828 53
1360505 3
1360798 10
1364725 22
1365707 29
1366838 19
1367663 55
1370629 3
1372130 21
1375664 4
1377817 1
1377929 2
1379119 14
1380137 6
1381296 24
1382303 11
1384484 2
1384943 2
1385011 1
1387130 14
1387304 2
1387458 6
1387615 3
1387818 1
1388279 3
1388409 6
1388437 16
1388838 16
1389082 1
1389256 8
1390003 3
1390043 1
1390063 3
1390205 2
1392364 36
1392910 1
1395055 1
1397290 1
1404652 2
1406484 4
1410833 2
1416856 11
1418359 2
1419027 3
1419099 4
1420473 2
1420816 10
1421594 7
1422508 12
1423045 2
1423065 14
1424196 1
1424322 4
1424467 1
1424480 3
1425041 1
1426588 21
1426754 6
1426771 1
1427147 2
1427684 3
1428350 5
1428601 3
1429788 1
1430681 2
1434323 4
1434689 9
1434845 9
1442173 6
1443095 17
1445891 8
1450008 1
1450558 28
1453102 2
1453155 2
1453526 3
1453819 6
1454424 3
1455176 5
1455251 24
1455452 1
1455495 12
1455924 7
1459754 3
1461287 47
1462525 4
1464586 4
1467888 1
1468685 4
1469219 6
1469528 13
1475150 1
1476804 3
1481714 1
1482010 149
1482012 1
1482106 2
1482390 3
1482688 5
1482880 12
1482935 4
1482970 14
1483060 1
1483065 190
1483170 13
1483467 1
1483796 15
1483824 2
1483969 1
1484085 1
1486946 2
1490429 1
1492162 7
1497637 14
1503269 1
1504941 5
1505961 2
1506073 17
1507971 9
1508120 16
1509508 19
1509873 7
1509973 5
1509974 1
1510201 1
1510809 1
1510848 2
1511144 1
1511291 2
1511465 9
1511550 3
1511794 1
1511888 4
1511915 1
1511985 1
1512024 3
1512251 20
1512545 7
1512601 2
1512652 1
1512808 1
1512814 3
1512865 6
1512914 4
1512978 2
1513122 1
1513125 1
1513211 27
1513865 1
1515072 6
1518364 1
1529832 1
1532262 1
1532618 5
1533321 1
1533954 2
1534417 2
1534561 8
1535315 8
1535477 1
1535610 2
1535679 1
1536114 1
1536430 1
1536924 3
1537558 2
1537703 28
1539338 4
1539948 2
1540569 1
1540944 2
1541399 13
1541496 2
1541596 1
1542108 4
1542143 1
1542162 3
1542165 2
1542287 3
1542300 11
1544744 2
1544806 1
1545812 2
1546283 2
1546967 3
1548882 3
1550228 7
1551969 2
1552426 7
1553656 6
1555170 1
1556915 1
1556970 17
1557513 3
1557664 4
1559538 2
1559968 2
1559972 3
1561790 1
1563690 21
1565061 1
1566887 3
1567195 1
1567634 1
1567890 3
1567912 4
1567993 16
1568298 1
1568540 9
1568542 1
1568787 1
1568894 1
1568939 2
1569067 3
1569071 6
1569099 1
1569102 2
1569117 32
1569119 6
1569147 5
1569148 2
1569174 8
1569175 3
1569453 1
1569606 2
1569656 1
1569667 36
1569688 3
1569766 18
1571556 1
1573485 4
1573767 2
1576707 9
1577001 36
1577920 1
1583092 11
791191 0
825161 0
831457 0
860176 0
883803 0
884300 0
887402 0
909450 0
911274 0
918893 0
933141 0
936936 0
1002672 0
1009259 0
1020580 0
1043853 0
1053054 0
1055290 0
1074266 0
1089710 0
1096783 0
1096978 0
1102256 0
1105863 0
1105876 0
1105907 0
1112179 0
1122241 0
1125725 0
1132699 0
1133219 0
1134288 0
1135307 0
1166988 0
1167167 0
1169318 0
1232960 0
1251567 0
1259261 0
1269134 0
1275880 0
1276755 0
1278793 0
1278951 0
1280200 0
1280493 0
1281446 0
1282189 0
1287618 0
1301743 0
1304762 0
1308377 0
1317784 0
1322590 0
1323510 0
1324659 0
1332811 0
1334952 0
1347104 0
1349654 0
1352859 0
1357372 0
1374998 0
1379995 0
1381859 0
1382646 0
1385080 0
1387723 0
1387814 0
1388076 0
1388142 0
1388168 0
1388382 0
1389223 0
1389974 0
1404574 0
1405555 0
1418421 0
1419345 0
1423296 0
1423876 0
1426665 0
1427263 0
1455288 0
1455969 0
1476179 0
1476961 0
1480535 0
1481447 0
1482171 0
1483535 0
1484205 0
1499882 0
1505207 0
1507758 0
1508195 0
1509550 0
1510434 0
1512026 0
1512145 0
1512746 0
1512858 0
1518320 0
1519319 0
1519676 0
1525865 0
1534259 0
1535227 0
1538037 0
1539919 0
1541353 0
1541536 0
1541597 0
1541787 0
1542166 0
1542179 0
1542324 0
1542421 0
1549358 0
1552999 0
1554815 0
1564579 0
1566414 0
1566493 0
1566494 0
1568049 0
1568289 0
1568555 0
1569137 0
1569519 0
1569650 0
1569833 0
1571042 0
1579254 0
1582813 0
1584801 0
1590073 0
1590491 0
1590784 0
1591379 0
1591625 0
1591925 0
7195 0
36066 0
51812 0
712050 0
790354 0
846633 0
860862 0
869179 0
905608 0
923116 0
939761 0
942618 0
944361 0
945444 0
1000490 0
1008868 0
1008937 0
1016021 0
1027451 0
1047859 0
1053013 0
1056488 0
1058854 0
1080381 0
1095836 0
1097833 0
1101250 0
1104186 0
1105838 0
1114739 0
1115055 0
1116247 0
1123274 0
1140331 0
1140474 0
1167212 0
1167348 0
1181544 0
1278178 0
1279097 0
1313871 0
1318055 0
1327944 0
1353110 0
1353311 0
1357975 0
1362987 0
1378559 0
1388028 0
1390271 0
1394866 0
1399706 0
1406585 0
1408103 0
1411512 0
1425649 0
1425963 0
1426266 0
1426940 0
1427351 0
1430308 0
1431518 0
1432539 0
1434981 0
1439743 0
1455267 0
1463698 0
1463753 0
1473429 0
1478417 0
1478775 0
1481986 0
1483472 0
1484256 0
1484540 0
1485921 0
1486180 0
1496201 0
1510475 0
1511172 0
1511229 0
1517429 0
1520770 0
1531064 0
1534843 0
1535106 0
1535631 0
1536078 0
1536444 0
1537335 0
1537621 0
1539947 0
1542317 0
1544825 0
1548468 0
1548836 0
1556245 0
1557485 0
1562668 0
1564721 0
1566113 0
1567397 0
1567889 0
1568280 0
1568303 0
1568389 0
1569141 0
1569853 0
1570296 0
1570396 0
1570598 0
1574661 0
1574758 0
1574886 0
1575581 0
1575766 0
1576102 0
1577773 0
1581298 0
1581465 0
1582635 0
1583977 0
1585047 0
1586986 0
1587643 0
1587836 0
1590569 0
1592405 0
1593410 0
1593688 0
1594492 0
1595852 0
1595853 0
1596077 0
1596355 0
1596901 0
1596906 0
1596920 0
1596957 0
1597099 0
1597200 0
1597549 0
1598011 0
1598013 0
1598147 0
1598177 0
1598180 0
1598245 0
1598348 0
1598352 0

1598550 0
1598803 0
1599054 0
1599210 0
1599212 0
1599217 0
1599390 0
1599425 0
1599444 0
1599466 0
1599468 0
1599562 0
1599579 0
1599623 0
1599731 0
1599746 0
1599747 0
1599813 0
1599863 0
1600004 0
1600085 0
1600136 0
1600145 0
200724 0
357301 0
740918 0
752365 0
813470 0
910886 0
1068809 0
1084683 0
1091923 0
1092838 0
1106590 0
1119032 0
1133385 0
1166134 0
1169581 0
1260824 0
1280054 0
1308555 0
1315828 0
1351063 0
1353198 0
1353570 0
1387869 0
1389403 0
1407382 0
1453885 0
1456511 0
1483394 0
1485153 0
1500605 0
1506294 0
1510940 0
1512901 0
1513193 0
1525109 0
1527570 0
1531611 0
1533327 0
1536725 0
1543991 0
1555283 0
1555900 0
1569036 0
1569292 0
1570251 0
1576151 0
1580830 0
1581655 0
1582968 0
1584086 0
1584087 0
1584246 0
1585045 0
1585740 0
1593921 0
1595124 0
1595509 0
1595855 0
1597245 0
1598340 0
1598381 0
1599760 0
1599793 0
1599882 0
1600035 0
1600151 0
1600583 0
1600746 0
1600999 0
1601742 0
1601904 0
1602198 0
1602476 0
1603001 0
1603142 0
1603937 0
1606588 0
1607231 0
1607636 0
1608057 0
1608179 0
59470 0
882119 0
883948 0
919086 0
928566 0
1026081 0
1053911 0
1053914 0
1066816 0
1103245 0
1160841 0
1215208 0
1272544 0
1314273 0
1314376 0
1314377 0
1315059 0
1317208 0
1339908 0
1342396 0
1347683 0
1352675 0
1379495 0
1381055 0
1386714 0
1387366 0
1388443 0
1389234 0
1389307 0
1391974 0
1426755 0
1426967 0
1427372 0
1441646 0
1463970 0
1482339 0
1494234 0
1510668 0
1511098 0
1534646 0
1535061 0
1535249 0
1536442 0
1543100 0
1546592 0
1556168 0
1561509 0
1563223 0
1565432 0
1576002 0
1579111 0
1584639 0
1589282 0
1589358 0
1591546 0
1591590 0
1592615 0
1592616 0
1593404 0
1595851 0
1596076 0
1598244 0
1598304 0
1599084 0
1599170 0
1599900 0
1605522 0
1607278 0
1607866 0
1608376 0
1614704 0
1615424 0
1616328 0
19481 0
314169 0
810386 0
949853 0
1009005 0
1010452 0
1022314 0
1108969 0
1119191 0
1120927 0
1123803 0
1140315 0
1166573 0
1167487 0
1315339 0
1340614 0
1350660 0
1357867 0
1381954 0
1387921 0
1387978 0
1387980 0
1395067 0
1424878 0
1450935 0
1451643 0
1455289 0
1455290 0
1478997 0
1483801 0
1511037 0
1512022 0
1513013 0
1532516 0
1546408 0
1550660 0
1568235 0
1568891 0
1569454 0
1569709 0
1571207 0
1578964 0
1583119 0
1587192 0
1590721 0
1596055 0
1598898 0
1599469 0
1599576 0
1599814 0
1599852 0
1600585 0
1600636 0
1606810 0
1616664 0
1624723 0
19475 0
320335 0
708848 0
711089 0
712534 0
714364 0
810958 0
849854 0
867926 0
883511 0
893738 0
927952 0
1009022 0
1014738 0
1028874 0
1044936 0
1071640 0
1089707 0
1092688 0
1125243 0
1131908 0
1140753 0
1141800 0
1143892 0
1169347 0
1172036 0
1201001 0
1214183 0
1276151 0
1285973 0
1309342 0
1316397 0
1333792 0
1359371 0
1368905 0
1369913 0
1376772 0
1393369 0
1409661 0
1411268 0
1423875 0
1426774 0
1426857 0
1427261 0
1428242 0
1475271 0
1479355 0
1484265 0
1484721 0
1492040 0
1493936 0
1495703 0
1505791 0
1511739 0
1512404 0
1518934 0
1521951 0
1523609 0
1527641 0
1528147 0
1535578 0
1535862 0
1536799 0
1537996 0
1540425 0
1540945 0
1541666 0
1542164 0
1549738 0
1550188 0
1550191 0
1554656 0
1559832 0
1566968 0
1568219 0
1569100 0
1576422 0
1576762 0
1580212 0
1581641 0
1583104 0
1585550 0
1586444 0
1588225 0
1591122 0
1591271 0
1591377 0
1592162 0
1594585 0
1595077 0
1595849 0
1596452 0
1597089 0
1597298 0
1597691 0
1597843 0
1597864 0
1598102 0
1598379 0
1598611 0
1599273 0
1599275 0
1599670 0
1599923 0
1603470 0
1604723 0
1609674 0
1611518 0
1611848 0
1613331 0
1613634 0
1615135 0
1615359 0
1615963 0
1616004 0
1618824 0
1619724 0
1620081 0
1620916 0
1624809 0
1625246 0
1625986 0
1626494 0
1631052 0
1631084 0
1631353 0
1631408 0
1631639 0
1631665 0
1631738 0
1631864 0
1631930 0
1631941 0
1632078 0
1632105 0
1632248 0
1632560 0
1632801 0
1632966 0
1632972 0
1633024 0
1633172 0
1633343 0
1633362 0
1633448 0
732847 0
919538 0
1009003 0
1034550 0
1058022 0
1070265 0
1128286 0
1138996 0
1139986 0
1143261 0
1291424 0
1299434 0
1316466 0
1326918 0
1386935 0
1423673 0
1461790 0
1471474 0
1499266 0
1510912 0
1512135 0
1531987 0
1535630 0
1540142 0
1542284 0
1552981 0
1572748 0
1579853 0
1580162 0
1580572 0
1590144 0
1600307 0
1600327 0
1601086 0
1601539 0
1602603 0
1606507 0
1609251 0
1616584 0
1617516 0
1619390 0
1622820 0
1624729 0
1626691 0
1627608 0
1628896 0
1630365 0
1631507 0
1632096 0
1632108 0
1632118 0
1632512 0
1632802 0
1632866 0
1633275 0
1633387 0
1633517 0
1633648 0
1633695 0
1633862 0
1633910 0
1634155 0
1634208 0
1634212 0
1634222 0
1637246 0
1637541 0
1638049 0
1641864 0
1642570 0
1023279 0
1081668 0
1086416 0
1127761 0
1307748 0
1387303 0
1389709 0
1415201 0
1438258 0
1467902 0
1475597 0
1482611 0
1484368 0
1491072 0
1510870 0
1541901 0
1542383 0
1558313 0
1569765 0
1582844 0
1600133 0
1600581 0
1602987 0
1605070 0
1624510 0
1633055 0
1633313 0
1633861 0
1634865 0
1638555 0
1640335 0
1642216 0
1645382 0
1645890 0
1649776 0
1650654 0
61227 0
902528 0
917579 0
938077 0
938487 0
1009012 0
1020317 0
1030618 0
1036250 0
1044330 0
1056581 0
1059543 0
1080382 0
1108829 0
1114039 0
1166152 0
1179232 0
1230869 0
1277279 0
1288125 0
1313473 0
1315497 0
1322853 0
1331875 0
1334199 0
1349352 0
1353098 0
1357550 0
1378410 0
1385925 0
1390457 0
1394096 0
1397076 0
1409765 0
1417889 0
1425419 0
1435346 0
1442573 0
1443077 0
1476329 0
1482416 0
1483532 0
1491998 0
1535264 0
1541211 0
1541349 0
1544676 0
1561784 0
1566728 0
1567738 0
1569356 0
1569532 0
1574408 0
1581793 0
1585828 0
1585859 0
1599016 0
1600403 0
1606716 0
1632097 0
1633227 0
1635342 0
1635523 0
1639753 0
1639754 0
1641438 0
1642351 0
1648101 0
1648901 0
1649888 0
1653866 0
710127 0
764611 0
903514 0
911088 0
914933 0
1002912 0
1014358 0
1081198 0
1184820 0
1266014 0
1286295 0
1289851 0
1358331 0
1389400 0
1389933 0
1473438 0
1475373 0
1512367 0
1529389 0
1534261 0
1535172 0
1536063 0
1536630 0
1537319 0
1551867 0
1555486 0
1567992 0
1568890 0
1569863 0
1584691 0
1598841 0
1599749 0
1618205 0
1623707 0
1626757 0
1630409 0
1632098 0
1632283 0
1632368 0
1633516 0
1633570 0
1634553 0
1639668 0
1641042 0
1641391 0
1650092 0
1651960 0
1653199 0
1653202 0
1653253 0
1654599 0
1654847 0
1655543 0
1657428 0
1659420 0
1659997 0
1660071 0
1660086 0
1661144 0
1661163 0
1661222 0
1663138 0
1663649 0
1663896 0
1664771 0
1665445 0
1665446 0
1665642 0
1666256 0
1666363 0
1666470 0
1666736 0
1666746 0
754811 0
767684 0
805867 0
842766 0
844150 0
859139 0
896159 0
1050068 0
1174850 0
1286534 0
1431256 0
1451428 0
1504304 0
1512162 0
1531593 0
1536080 0
1544341 0
1575151 0
1576053 0
1589661 0
1602263 0
1608062 0
1622431 0
1625800 0
1629680 0
1630939 0
1631208 0
1632929 0
1645157 0
1649147 0
1654710 0
1655095 0
1658535 0
1659346 0
1660203 0
1661149 0
1664214 0
1665199 0
1665302 0
1665359 0
1666786 0
1666788 0
1667694 0
1668155 0
1668256 0
1669733 0
1670053 0
1670903 0
1672070 0
1673815 0
1673907 0
1673922 0
936941 0
1010232 0
1054880 0
1313893 0
1387761 0
1468395 0
1511137 0
1549042 0
1592613 0
1618832 0
1618872 0
1632407 0
1640638 0
1641440 0
1641643 0
1649107 0
1653168 0
1663224 0
1664147 0
1664385 0
1664772 0
1666239 0
1666738 0
1667019 0
1667074 0
1667102 0
1667140 0
1667164 0
1668189 0
1673633 0
1679118 0
1679807 0
1053994 0
1095721 0
1169883 0
1216093 0
1301050 0
1316550 0
1362255 0
1429895 0
1438129 0
1446440 0
1465837 0
1483276 0
1484165 0
1502631 0
1511826 0
1541055 0
1598558 0
1599795 0
1609074 0
1637187 0
1640361 0
1666733 0
1667132 0
1671716 0
1674712 0
1677443 0
1680365 0
77132 0
808722 0
934866 0
1068804 0
1074902 0
1085867 0
1115419 0
1122490 0
1135631 0
1165248 0
1175130 0
1245862 0
1280511 0
1287978 0
1343119 0
1348145 0
1365555 0
1373017 0
1377635 0
1387369 0
1424116 0
1427350 0
1442641 0
1444055 0
1455468 0
1510099 0
1512415 0
1513227 0
1538338 0
1543830 0
1561089 0
1576654 0
1594197 0
1600152 0
1604350 0
1617032 0
1620822 0
1623796 0
1624865 0
1630806 0
1633046 0
1633446 0
1633703 0
1650301 0
1656666 0
1659203 0
1662449 0
1665976 0
1667134 0
1671161 0
1672829 0
1676603 0
1678953 0
1680326 0
1681126 0
1682733 0
1684868 0
1685959 0
1686444 0
1687156 0
1688171 0
1688774 0
1689013 0
1690531 0
1690717 0
1692252 0
1692623 0
1693809 0
1694284 0
1694297 0
1694886 0
1695214 0
1695320 0
1695345 0
1695490 0
1696494 0
1696497 0
1696548 0
1696656 0
1696867 0
1697300 0
1697444 0
1697493 0
1697539 0
1697646 0
1697715 0

1697717 0
1697790 0
1697796 0
1697847 0
1697855 0
1698051 0
811407 0
872359 0
899211 0
935359 0
944733 0
1041773 0
1109767 0
1122470 0
1218749 0
1279396 0
1353651 0
1367786 0
1438574 0
1473174 0
1532472 0
1535677 0
1536006 0
1536446 0
1572838 0
1576584 0
1578242 0
1580677 0
1591307 0
1606134 0
1616628 0
1626220 0
1632548 0
1638022 0
1656713 0
1657516 0
1661462 0
1665518 0
1665589 0
1666024 0
1669662 0
1671811 0
1672067 0
1672201 0
1683182 0
1683754 0
1689872 0
1690186 0
1691804 0
1691982 0
1694079 0
1694948 0
1695582 0
1695658 0
1696263 0
1696438 0
1696615 0
1696628 0
1696957 0
1697360 0
1697767 0
1697791 0
1697848 0
1697882 0
1698094 0
1698146 0
1698215 0
1698220 0
1699622 0
1699803 0
1703080 0
1704107 0
1705711 0
1706248 0
811808 0
820123 0
1054522 0
1343916 0
1425165 0
1634301 0
1652391 0
1656537 0
1675762 0
1680613 0
1681662 0
1688931 0
1694896 0
1697725 0
1698218 0
1703100 0
1706836 0
1709698 0
1710524 0
1713520 0
1713735 0
351262 0
1019531 0
1128239 0
1133999 0
1357993 0
1557689 0
1568839 0
1604831 0
1632253 0
1632965 0
1633288 0
1652174 0
1665590 0
1679064 0
1688666 0
1689470 0
1706351 0
1708872 0
1710666 0
1711200 0
1712671 0
1713678 0
1716399 0
1719739 0
1721608 0
1440771 0
1621855 0
1644329 0
1661140 0
1680638 0
1689829 0
1694283 0
1697162 0
1714341 0
1645721 0
1646343 0
1689874 0
1544554 0
1598561 0
1666647 0
1713521 0

In [46]:
form13f_3mos["market_V_3mos"] = form13f_3mos["shares"] * form13f_3mos["pSP_CLOSE_y"]
form13f_3mos

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos
0,39276322,7195,742718109,2013-06-30,2013-08-12,61112.0,4705000.0,0.020468,43 days,Communications,Large-Cap Value,81.6200,57645.185004,2013-05-01,76.9900,4.438103e+06
1,39276331,7195,92343V104,2013-06-30,2013-08-12,94160.0,4740000.0,0.020620,43 days,Communications,Large-Cap Value,49.6500,95468.277946,2013-05-01,52.4000,5.002538e+06
2,39276303,7195,369604103,2013-06-30,2013-08-12,182959.0,4243000.0,0.018458,43 days,Communications,MidCap Value,24.1915,175392.183205,2013-05-01,22.0784,3.872379e+06
3,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000,62664.141414,2013-05-01,72.7600,4.559443e+06
4,39276297,7195,22160K105,2013-06-30,2013-08-12,41274.0,4564000.0,0.019855,43 days,Consumer Discretionary,Large-Cap Growth,115.7300,39436.619718,2013-05-01,108.2200,4.267831e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678608,65812260,1721608,92189F445,2018-06-30,2018-07-13,49724.0,1212000.0,0.004417,13 days,NA,NA,NaN,NaN,2018-05-01,NaN,NaN
1678609,65812259,1721608,46434G772,2018-06-30,2018-07-13,260955.0,9394000.0,0.034237,13 days,NA,NA,NaN,NaN,2018-05-01,NaN,NaN
1678610,65812273,1721608,46090E103,2018-06-30,2018-07-13,14237.0,2444000.0,0.008907,13 days,Technology,Large-Cap Growth,179.6100,13607.260175,2018-05-01,162.7800,2.214990e+06
1678611,65812254,1721608,464288174,2018-06-30,2018-07-13,6167.0,482000.0,0.001757,13 days,Technology,Small-Cap Growth,76.9032,6267.619553,2018-05-01,78.1677,4.899254e+05
1678612,65812274,1721608,464287739,2018-06-30,2018-07-13,107697.0,8678000.0,0.031628,13 days,Utilities,MidCap Value,79.4892,109172.063626,2018-05-01,73.7377,8.050097e+06

In [47]:
form13f_3mos_new = form13f_3mos.dropna()
form13f_3mos_new

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos
0,39276322,7195,742718109,2013-06-30,2013-08-12,61112.0,4705000.0,0.020468,43 days,Communications,Large-Cap Value,81.6200,57645.185004,2013-05-01,76.9900,4.438103e+06
1,39276331,7195,92343V104,2013-06-30,2013-08-12,94160.0,4740000.0,0.020620,43 days,Communications,Large-Cap Value,49.6500,95468.277946,2013-05-01,52.4000,5.002538e+06
2,39276303,7195,369604103,2013-06-30,2013-08-12,182959.0,4243000.0,0.018458,43 days,Communications,MidCap Value,24.1915,175392.183205,2013-05-01,22.0784,3.872379e+06
3,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000,62664.141414,2013-05-01,72.7600,4.559443e+06
4,39276297,7195,22160K105,2013-06-30,2013-08-12,41274.0,4564000.0,0.019855,43 days,Consumer Discretionary,Large-Cap Growth,115.7300,39436.619718,2013-05-01,108.2200,4.267831e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678604,65812268,1721608,464286806,2018-06-30,2018-07-13,12898.0,387000.0,0.001410,13 days,Materials,Small-Cap Growth,30.6300,12634.671890,2018-05-01,31.5867,3.990876e+05
1678605,65812258,1721608,922042874,2018-06-30,2018-07-13,1178.0,66000.0,0.000241,13 days,Materials,Small-Cap Growth,56.1676,1175.054658,2018-05-01,56.9964,6.697389e+04
1678610,65812273,1721608,46090E103,2018-06-30,2018-07-13,14237.0,2444000.0,0.008907,13 days,Technology,Large-Cap Growth,179.6100,13607.260175,2018-05-01,162.7800,2.214990e+06
1678611,65812254,1721608,464288174,2018-06-30,2018-07-13,6167.0,482000.0,0.001757,13 days,Technology,Small-Cap Growth,76.9032,6267.619553,2018-05-01,78.1677,4.899254e+05
1678612,65812274,1721608,464287739,2018-06-30,2018-07-13,107697.0,8678000.0,0.031628,13 days,Utilities,MidCap Value,79.4892,109172.063626,2018-05-01,73.7377,8.050097e+06

In [48]:
total_market_V = form13f_3mos_new.groupby(["iCIK","iPERIOD_END"],as_index=False).iMARKET_VALUE.sum()
total_market_V_3mos = form13f_3mos_new.groupby(["iCIK","iPERIOD_END"],as_index=False).market_V_3mos.sum()
Return = pd.merge(total_market_V,total_market_V_3mos, on=["iCIK","iPERIOD_END"])
Return["return"] = (Return["iMARKET_VALUE"] - Return["market_V_3mos"]) / Return["market_V_3mos"]
Return # return of each fund in each period

          iCIK iPERIOD_END  iMARKET_VALUE  market_V_3mos    return
0         7195  2013-06-30    229871000.0   2.157608e+08  0.065397
1         7195  2013-09-30    220987000.0   2.191440e+08  0.008410
2         7195  2013-12-31    244650000.0   2.355210e+08  0.038761
3         7195  2014-03-31    243537000.0   2.359490e+08  0.032159
4         7195  2014-06-30    236104000.0   2.258708e+08  0.045306
...        ...         ...            ...            ...       ...
15477  1719739  2018-06-30    145355000.0   1.339388e+08  0.085235
15478  1721608  2017-09-30    114173000.0   1.116571e+08  0.022532
15479  1721608  2017-12-31    160337000.0   1.587604e+08  0.009931
15480  1721608  2018-03-31    222791000.0   2.304703e+08 -0.033320
15481  1721608  2018-06-30    246107000.0   2.421252e+08  0.016445

[15482 rows x 5 columns]

In [49]:
cik_mean_returns = Return.groupby("iCIK",as_index=False)["return"].mean()
cik_mean_returns # mean return of each fund

         iCIK    return
0        7195  0.025251
1       18748  0.010671
2       19475  0.050653
3       19481  0.060120
4       21175  0.020743
...       ...       ...
1801  1713735  0.030064
1802  1714341  0.012985
1803  1716399  0.021163
1804  1719739  0.039878
1805  1721608  0.003897

[1806 rows x 2 columns]

In [50]:
mean_return = cik_mean_returns["return"].mean()
mean_return # mean return of all funds

0.024716644832761658

In [51]:
def performance(row):
    if row['return'] > mean_return * 1.2:
        p = "high"
    elif row['return'] < mean_return * 0.8:
        p = "low"
    else:
        p = "medium"
    return p
cik_mean_returns["performance"] = cik_mean_returns.apply(performance, axis=1)
cik_mean_returns

         iCIK    return performance
0        7195  0.025251      medium
1       18748  0.010671         low
2       19475  0.050653        high
3       19481  0.060120        high
4       21175  0.020743      medium
...       ...       ...         ...
1801  1713735  0.030064        high
1802  1714341  0.012985         low
1803  1716399  0.021163      medium
1804  1719739  0.039878        high
1805  1721608  0.003897         low

[1806 rows x 3 columns]

In [52]:
len(form13f_3mos["iCIK"].unique())

1808

### 4. Volatility

In [53]:
# std of period returns for each fund (Return) -> take mean
volatility = Return.groupby("iCIK",as_index=False)["return"].std()
volatility.columns = ["iCIK", "volatility"]
volatility

         iCIK  volatility
0        7195    0.042513
1       18748    0.037731
2       19475    0.031249
3       19481    0.009252
4       21175    0.067871
...       ...         ...
1801  1713735    0.034755
1802  1714341    0.052941
1803  1716399    0.035538
1804  1719739    0.055073
1805  1721608    0.025339

[1806 rows x 2 columns]

In [54]:
mean_volatility = volatility["volatility"].mean()
mean_volatility

0.05209480122518896

In [55]:
def vol(row):
    if row['volatility'] > mean_volatility * 1.2:
        v = "high"
    elif row['volatility'] < mean_volatility * 0.8:
        v = "low"
    else:
        v = "medium"
    return v
volatility["volatility group"] = volatility.apply(vol, axis=1)
volatility

         iCIK  volatility volatility group
0        7195    0.042513           medium
1       18748    0.037731              low
2       19475    0.031249              low
3       19481    0.009252              low
4       21175    0.067871             high
...       ...         ...              ...
1801  1713735    0.034755              low
1802  1714341    0.052941           medium
1803  1716399    0.035538              low
1804  1719739    0.055073           medium
1805  1721608    0.025339              low

[1806 rows x 3 columns]

### 5. Survival Time

In [56]:
period_min = form13f_3mos.groupby("iCIK",as_index=False).iPERIOD_END.min()
period_min.columns = ["iCIK", "iPERIOD_END_min"]
period_max = form13f_3mos.groupby("iCIK",as_index=False).iPERIOD_END.max()
period_max.columns = ["iCIK", "iPERIOD_END_max"]
period = pd.merge(period_min, period_max, on=["iCIK"])
period["survival time"] = period["iPERIOD_END_max"] - period["iPERIOD_END_min"]
period

         iCIK iPERIOD_END_min iPERIOD_END_max survival time
0        7195      2013-06-30      2018-06-30     1826 days
1       18748      2013-06-30      2016-09-30     1188 days
2       19475      2013-06-30      2018-06-30     1826 days
3       19481      2013-06-30      2015-03-31      639 days
4       21175      2013-06-30      2018-06-30     1826 days
...       ...             ...             ...           ...
1803  1713735      2017-06-30      2018-06-30      365 days
1804  1714341      2017-06-30      2018-06-30      365 days
1805  1716399      2017-09-30      2018-06-30      273 days
1806  1719739      2017-09-30      2018-06-30      273 days
1807  1721608      2017-09-30      2018-06-30      273 days

[1808 rows x 4 columns]

In [57]:
mean_survival = period["survival time"].mean()
mean_survival

Timedelta('1155 days 18:27:04.778761056')

In [58]:
def survival(row):
    if row['survival time'] > mean_survival * 1.5: # no fund survives twice the mean survival time
        s = "high"
    elif row['survival time'] < mean_survival * 0.8:
        s = "low"
    else:
        s = "medium"
    return s
period["survival group"] = period.apply(survival, axis=1)
period

         iCIK iPERIOD_END_min iPERIOD_END_max survival time survival group
0        7195      2013-06-30      2018-06-30     1826 days           high
1       18748      2013-06-30      2016-09-30     1188 days         medium
2       19475      2013-06-30      2018-06-30     1826 days           high
3       19481      2013-06-30      2015-03-31      639 days            low
4       21175      2013-06-30      2018-06-30     1826 days           high
...       ...             ...             ...           ...            ...
1803  1713735      2017-06-30      2018-06-30      365 days            low
1804  1714341      2017-06-30      2018-06-30      365 days            low
1805  1716399      2017-09-30      2018-06-30      273 days            low
1806  1719739      2017-09-30      2018-06-30      273 days            low
1807  1721608      2017-09-30      2018-06-30      273 days            low

[1808 rows x 5 columns]

### 6. Idiosyncratic Risk

In [59]:
####### ?????????

### 7. Inflow & Turnover

In [60]:
form13f_3mos

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos
0,39276322,7195,742718109,2013-06-30,2013-08-12,61112.0,4705000.0,0.020468,43 days,Communications,Large-Cap Value,81.6200,57645.185004,2013-05-01,76.9900,4.438103e+06
1,39276331,7195,92343V104,2013-06-30,2013-08-12,94160.0,4740000.0,0.020620,43 days,Communications,Large-Cap Value,49.6500,95468.277946,2013-05-01,52.4000,5.002538e+06
2,39276303,7195,369604103,2013-06-30,2013-08-12,182959.0,4243000.0,0.018458,43 days,Communications,MidCap Value,24.1915,175392.183205,2013-05-01,22.0784,3.872379e+06
3,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000,62664.141414,2013-05-01,72.7600,4.559443e+06
4,39276297,7195,22160K105,2013-06-30,2013-08-12,41274.0,4564000.0,0.019855,43 days,Consumer Discretionary,Large-Cap Growth,115.7300,39436.619718,2013-05-01,108.2200,4.267831e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678608,65812260,1721608,92189F445,2018-06-30,2018-07-13,49724.0,1212000.0,0.004417,13 days,NA,NA,NaN,NaN,2018-05-01,NaN,NaN
1678609,65812259,1721608,46434G772,2018-06-30,2018-07-13,260955.0,9394000.0,0.034237,13 days,NA,NA,NaN,NaN,2018-05-01,NaN,NaN
1678610,65812273,1721608,46090E103,2018-06-30,2018-07-13,14237.0,2444000.0,0.008907,13 days,Technology,Large-Cap Growth,179.6100,13607.260175,2018-05-01,162.7800,2.214990e+06
1678611,65812254,1721608,464288174,2018-06-30,2018-07-13,6167.0,482000.0,0.001757,13 days,Technology,Small-Cap Growth,76.9032,6267.619553,2018-05-01,78.1677,4.899254e+05
1678612,65812274,1721608,464287739,2018-06-30,2018-07-13,107697.0,8678000.0,0.031628,13 days,Utilities,MidCap Value,79.4892,109172.063626,2018-05-01,73.7377,8.050097e+06

In [61]:
############################################ ex. iCIK == 7195 ##################################################
tp = form13f_3mos[form13f_3mos['iCIK'] == 7195]
tp = tp.sort_values(by = ["iCUSIP","iPERIOD_END"])
tp['buy'] = 0
tp

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos,buy
1589502,65860591,7195,00206R102,2018-06-30,2018-07-19,29025.0,932000.0,0.004254,19 days,Communications,MidCap Value,31.2700,29804.924848,2018-05-01,32.5400,9.698523e+05,0
1589566,65860611,7195,00287Y109,2018-06-30,2018-07-19,3656.0,339000.0,0.001547,19 days,Technology,MidCap Growth,89.9500,3768.760422,2018-05-01,102.0700,3.846774e+05,0
25,39276284,7195,009158106,2013-06-30,2013-08-12,46990.0,4303000.0,0.018719,43 days,Health Care,MidCap Value,95.9923,44826.512126,2013-05-01,79.7053,3.572911e+06,0
53604,40312064,7195,009158106,2013-09-30,2013-10-16,42995.0,4582000.0,0.020734,16 days,Health Care,MidCap Value,101.4710,45155.758788,2013-08-01,99.7595,4.504716e+06,0
113954,48527318,7195,009158106,2013-12-31,2014-01-21,42995.0,4806000.0,0.019558,21 days,Health Care,MidCap Value,104.2240,46112.219834,2013-11-01,100.4570,4.632295e+06,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32,39276308,7195,G47791101,2013-06-30,2013-08-12,85988.0,4774000.0,0.020768,43 days,Industrial,MidCap Blend,48.8932,97641.389805,2013-05-01,41.6114,4.062995e+06,0
53611,40312088,7195,G47791101,2013-09-30,2013-10-16,77953.0,5062000.0,0.022906,16 days,Industrial,MidCap Blend,50.4707,100295.815196,2013-08-01,49.4828,4.962918e+06,0
113961,48527304,7195,G47791101,2013-12-31,2014-01-21,77953.0,4802000.0,0.019541,21 days,Industrial,MidCap Blend,62.0700,77364.266151,2013-11-01,53.9682,4.175210e+06,0
186278,48825005,7195,G47791101,2014-03-31,2014-04-14,67158.0,3844000.0,0.015784,14 days,Industrial,MidCap Blend,55.2600,69562.070214,2014-01-30,59.0300,4.106249e+06,0
263547,49986220,7195,G47791101,2014-06-30,2014-07-21,10438.0,652000.0,0.002726,21 days,Industrial,MidCap Blend,61.8500,10541.632983,2014-05-01,59.9600,6.320763e+05,0

In [62]:
stocks = tp['iCUSIP'].unique()
for i in stocks:
    temp = tp[tp['iCUSIP'] == i]
    if len(temp) == 1:
        tp.at[temp.index[0], 'buy'] = temp.iloc[0]['iMARKET_VALUE']
    else:
        diff = np.diff(temp['iMARKET_VALUE'])
        diff = np.insert(diff, 0, temp.iloc[0]['iMARKET_VALUE'])
        for j in range(len(temp)):
            tp.at[temp.index[j],'buy'] = diff[j]
            
tp = tp.sort_values(by='iPERIOD_END')
tp

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos,buy
35,39276296,7195,219350105,2013-06-30,2013-08-12,302325.0,4302000.0,0.018715,43 days,Materials,Large-Cap Value,15.110,284712.111185,2013-05-01,14.330,4.079925e+06,4302000
29,39276307,7195,452308109,2013-06-30,2013-08-12,69101.0,4780000.0,0.020794,43 days,Industrial,Large-Cap Blend,73.520,65016.322089,2013-05-01,63.870,4.152592e+06,4780000
36,39276330,7195,907818108,2013-06-30,2013-08-12,33615.0,5186000.0,0.022561,43 days,Materials,MidCap Growth,79.585,65163.033235,2013-05-01,72.835,4.746150e+06,5186000
44,39276309,7195,458140100,2013-06-30,2013-08-12,189457.0,4591000.0,0.019972,43 days,Technology,Large-Cap Growth,22.640,202782.685512,2013-05-01,23.990,4.864757e+06,4591000
12,39276310,7195,459200101,2013-06-30,2013-08-12,21721.0,4151000.0,0.018058,43 days,Energy,Small-Cap Blend,189.090,21952.509387,2013-05-01,199.630,4.382379e+06,4151000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1589558,65860583,7195,67066G104,2018-06-30,2018-07-19,20400.0,4833000.0,0.022058,19 days,Technology,Large-Cap Growth,252.030,19176.288537,2018-05-01,227.140,4.355702e+06,4833000
1589520,65860604,7195,674599105,2018-06-30,2018-07-19,60265.0,5043000.0,0.023016,19 days,Energy,Small-Cap Growth,82.980,60773.680405,2018-05-01,76.580,4.654048e+06,991000
1589508,65860599,7195,713448108,2018-06-30,2018-07-19,39656.0,4317000.0,0.019703,19 days,Consumer Staples,Large-Cap Value,115.770,37289.453226,2018-05-01,99.130,3.696503e+06,292000
1589568,65860584,7195,615369105,2018-06-30,2018-07-19,1494.0,255000.0,0.001164,19 days,Technology,MidCap Growth,182.350,1398.409652,2018-05-01,164.160,2.295629e+05,255000
1589502,65860591,7195,00206R102,2018-06-30,2018-07-19,29025.0,932000.0,0.004254,19 days,Communications,MidCap Value,31.270,29804.924848,2018-05-01,32.540,9.698523e+05,932000

In [63]:
tp[(tp["iCUSIP"] == "882508104") & (tp["iPERIOD_END"] == datetime.date(2020,3,31))]

Empty DataFrame
Columns: [iRECORD_ID, iCIK, iCUSIP, iPERIOD_END, iFILING_DATE, iQTY, iMARKET_VALUE, iLONG_FRACTION, FILING_INTERVAL, sector, value_size, pSP_CLOSE_x, shares, filing_3mos, pSP_CLOSE_y, market_V_3mos, buy]
Index: []

In [64]:
temp = tp['buy'].values
zeros = np.zeros_like(temp)
tp['sell'] = np.maximum(zeros, -temp)
tp['buy'] = np.maximum(zeros, temp)
tp

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos,buy,sell
35,39276296,7195,219350105,2013-06-30,2013-08-12,302325.0,4302000.0,0.018715,43 days,Materials,Large-Cap Value,15.110,284712.111185,2013-05-01,14.330,4.079925e+06,4302000,0
29,39276307,7195,452308109,2013-06-30,2013-08-12,69101.0,4780000.0,0.020794,43 days,Industrial,Large-Cap Blend,73.520,65016.322089,2013-05-01,63.870,4.152592e+06,4780000,0
36,39276330,7195,907818108,2013-06-30,2013-08-12,33615.0,5186000.0,0.022561,43 days,Materials,MidCap Growth,79.585,65163.033235,2013-05-01,72.835,4.746150e+06,5186000,0
44,39276309,7195,458140100,2013-06-30,2013-08-12,189457.0,4591000.0,0.019972,43 days,Technology,Large-Cap Growth,22.640,202782.685512,2013-05-01,23.990,4.864757e+06,4591000,0
12,39276310,7195,459200101,2013-06-30,2013-08-12,21721.0,4151000.0,0.018058,43 days,Energy,Small-Cap Blend,189.090,21952.509387,2013-05-01,199.630,4.382379e+06,4151000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1589558,65860583,7195,67066G104,2018-06-30,2018-07-19,20400.0,4833000.0,0.022058,19 days,Technology,Large-Cap Growth,252.030,19176.288537,2018-05-01,227.140,4.355702e+06,4833000,0
1589520,65860604,7195,674599105,2018-06-30,2018-07-19,60265.0,5043000.0,0.023016,19 days,Energy,Small-Cap Growth,82.980,60773.680405,2018-05-01,76.580,4.654048e+06,991000,0
1589508,65860599,7195,713448108,2018-06-30,2018-07-19,39656.0,4317000.0,0.019703,19 days,Consumer Staples,Large-Cap Value,115.770,37289.453226,2018-05-01,99.130,3.696503e+06,292000,0
1589568,65860584,7195,615369105,2018-06-30,2018-07-19,1494.0,255000.0,0.001164,19 days,Technology,MidCap Growth,182.350,1398.409652,2018-05-01,164.160,2.295629e+05,255000,0
1589502,65860591,7195,00206R102,2018-06-30,2018-07-19,29025.0,932000.0,0.004254,19 days,Communications,MidCap Value,31.270,29804.924848,2018-05-01,32.540,9.698523e+05,932000,0

In [65]:
grouped = tp.groupby(["iPERIOD_END"]).sum()
grouped['turnover'] = np.minimum(grouped['buy'], grouped['sell'])/grouped['iMARKET_VALUE']
grouped = grouped['turnover']
grouped = grouped.reset_index()
grouped['iCIK'] = 7195
grouped

   iPERIOD_END  turnover  iCIK
0   2013-06-30  0.000000  7195
1   2013-09-30  0.025201  7195
2   2013-12-31  0.001058  7195
3   2014-03-31  0.026546  7195
4   2014-06-30  0.050941  7195
5   2014-09-30  0.028756  7195
6   2014-12-31  0.015475  7195
7   2015-03-31  0.012458  7195
8   2015-06-30  0.020293  7195
9   2015-09-30  0.047148  7195
10  2015-12-31  0.016916  7195
11  2016-03-31  0.026190  7195
12  2016-06-30  0.026386  7195
13  2016-09-30  0.031026  7195
14  2016-12-31  0.023662  7195
15  2017-03-31  0.001995  7195
16  2017-06-30  0.015492  7195
17  2017-09-30  0.001252  7195
18  2017-12-31  0.008225  7195
19  2018-03-31  0.004520  7195
20  2018-06-30  0.028717  7195

In [66]:
##################################################################################################################

In [67]:
# Quarterly turnover for each fund
def turnover_one_fund(df, index):
    tp = df[df['iCIK'] == index]
    tp = tp.sort_values(by = ["iCUSIP","iPERIOD_END"])
    tp['buy'] = 0
    stocks = tp['iCUSIP'].unique()
    for i in stocks:
        temp = tp[tp['iCUSIP'] == i]
        if len(temp) == 1:
            tp.at[temp.index[0], 'buy'] = temp.iloc[0]['iMARKET_VALUE']
        else:
            diff = np.diff(temp['iMARKET_VALUE'])
            diff = np.insert(diff, 0, temp.iloc[0]['iMARKET_VALUE'])
            for j in range(len(temp)):
                tp.at[temp.index[j],'buy'] = diff[j]
    tp = tp.sort_values(by='iPERIOD_END')
    temp = tp['buy'].values
    zeros = np.zeros_like(temp)
    tp['sell'] = np.maximum(zeros, -temp)
    tp['buy'] = np.maximum(zeros, temp)
    grouped = tp.groupby(["iPERIOD_END"]).sum()
    grouped['turnover'] = np.minimum(grouped['buy'], grouped['sell'])/grouped['iMARKET_VALUE']
    grouped = grouped['turnover']
    grouped = grouped.reset_index()
    grouped['iCIK'] = index
    return tp, grouped

In [68]:
form13f_inflow = []
Turnover = []

for i in form13f_3mos['iCIK'].unique():
    inflow, turnover = turnover_one_fund(form13f_3mos, i)
    form13f_inflow.append(inflow)
    Turnover.append(turnover)

form13f_inflow = pd.concat(form13f_inflow)
Turnover = pd.concat(Turnover)

In [69]:
form13f_inflow

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos,buy,sell
35,39276296,7195,219350105,2013-06-30,2013-08-12,302325.0,4302000.0,0.018715,43 days,Materials,Large-Cap Value,15.1100,284712.111185,2013-05-01,14.3300,4.079925e+06,4302000,0
29,39276307,7195,452308109,2013-06-30,2013-08-12,69101.0,4780000.0,0.020794,43 days,Industrial,Large-Cap Blend,73.5200,65016.322089,2013-05-01,63.8700,4.152592e+06,4780000,0
36,39276330,7195,907818108,2013-06-30,2013-08-12,33615.0,5186000.0,0.022561,43 days,Materials,MidCap Growth,79.5850,65163.033235,2013-05-01,72.8350,4.746150e+06,5186000,0
44,39276309,7195,458140100,2013-06-30,2013-08-12,189457.0,4591000.0,0.019972,43 days,Technology,Large-Cap Growth,22.6400,202782.685512,2013-05-01,23.9900,4.864757e+06,4591000,0
12,39276310,7195,459200101,2013-06-30,2013-08-12,21721.0,4151000.0,0.018058,43 days,Energy,Small-Cap Blend,189.0900,21952.509387,2013-05-01,199.6300,4.382379e+06,4151000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678596,65812266,1721608,78463X863,2018-06-30,2018-07-13,8483.0,332000.0,0.001210,13 days,Health Care,MidCap Value,37.8504,8771.373618,2018-05-01,38.7655,3.400267e+05,20000,0
1678584,65812256,1721608,78467V608,2018-06-30,2018-07-13,174973.0,8218000.0,0.029951,13 days,Communications,MidCap Value,45.2506,181610.851569,2018-05-01,45.0628,8.183893e+06,6341000,0
1678583,65812284,1721608,78468R408,2018-06-30,2018-07-13,31911.0,871000.0,0.003174,13 days,Communications,MidCap Value,26.2391,33194.736100,2018-05-01,25.9226,8.604939e+05,871000,0
1678606,65812253,1721608,92189F494,2018-06-30,2018-07-13,83255.0,1417000.0,0.005164,13 days,NA,NA,NaN,NaN,2018-05-01,NaN,NaN,0,98000
1678600,65812271,1721608,97717W422,2018-06-30,2018-07-13,330467.0,8318000.0,0.030316,13 days,Materials,Large-Cap Blend,25.2507,329416.610233,2018-05-01,26.1881,8.626795e+06,8318000,0

In [70]:
Turnover.sort_values(by='iPERIOD_END')
Turnover # turnover for each fund in each period

   iPERIOD_END  turnover     iCIK
0   2013-06-30  0.000000     7195
1   2013-09-30  0.025201     7195
2   2013-12-31  0.001058     7195
3   2014-03-31  0.026546     7195
4   2014-06-30  0.050941     7195
..         ...       ...      ...
3   2018-06-30  0.018762  1719739
0   2017-09-30  0.000000  1721608
1   2017-12-31  0.000000  1721608
2   2018-03-31  0.066387  1721608
3   2018-06-30  0.040462  1721608

[20027 rows x 3 columns]

In [71]:
turnover_mean = Turnover.groupby('iPERIOD_END').mean()
turnover_mean

             turnover          iCIK
iPERIOD_END
2013-06-30   0.047669  1.271251e+06
2013-09-30   0.082798  1.286632e+06
2013-12-31   0.031695  1.316943e+06
2014-03-31   0.056569  1.323565e+06
2014-06-30   0.052065  1.335759e+06
2014-09-30   0.065565  1.332481e+06
2014-12-31   0.061723  1.333539e+06
2015-03-31   0.064917  1.347450e+06
2015-06-30   0.062884  1.351731e+06
2015-09-30   0.078780  1.336446e+06
2015-12-31   0.061542  1.355122e+06
2016-03-31   0.070822  1.356783e+06
2016-06-30   0.061181  1.369108e+06
2016-09-30   0.068167  1.386532e+06
2016-12-31   0.067627  1.402426e+06
2017-03-31   0.060058  1.408493e+06
2017-06-30   0.054410  1.388758e+06
2017-09-30   0.056766  1.417891e+06
2017-12-31   0.061640  1.421318e+06
2018-03-31   0.075885  1.413545e+06
2018-06-30   0.066476  1.417092e+06

In [72]:
def f(row):
    if row['turnover'] > turnover_mean.loc[row['iPERIOD_END']]['turnover'] * 1.5:
        t = "high"
    elif row['turnover'] < turnover_mean.loc[row['iPERIOD_END']]['turnover'] * 0.8:
        t = "low"
    else:
        t = "medium"
    return t
Turnover["turnover group"] = Turnover.apply(f, axis=1)
Turnover

   iPERIOD_END  turnover     iCIK turnover group
0   2013-06-30  0.000000     7195            low
1   2013-09-30  0.025201     7195            low
2   2013-12-31  0.001058     7195            low
3   2014-03-31  0.026546     7195            low
4   2014-06-30  0.050941     7195         medium
..         ...       ...      ...            ...
3   2018-06-30  0.018762  1719739            low
0   2017-09-30  0.000000  1721608            low
1   2017-12-31  0.000000  1721608            low
2   2018-03-31  0.066387  1721608         medium
3   2018-06-30  0.040462  1721608            low

[20027 rows x 4 columns]

In [73]:
Turnover.sort_values(by='iPERIOD_END')
Turnover

   iPERIOD_END  turnover     iCIK turnover group
0   2013-06-30  0.000000     7195            low
1   2013-09-30  0.025201     7195            low
2   2013-12-31  0.001058     7195            low
3   2014-03-31  0.026546     7195            low
4   2014-06-30  0.050941     7195         medium
..         ...       ...      ...            ...
3   2018-06-30  0.018762  1719739            low
0   2017-09-30  0.000000  1721608            low
1   2017-12-31  0.000000  1721608            low
2   2018-03-31  0.066387  1721608         medium
3   2018-06-30  0.040462  1721608            low

[20027 rows x 4 columns]

# Further Filtering

### 1. Turnover: funds with low / medium quarterly turnover

In [74]:
Turnover_filtered = Turnover.groupby("iCIK").filter(lambda x:((x["turnover group"] == "low") | (x["turnover group"] == "medium")).all())
Turnover_filtered

   iPERIOD_END  turnover     iCIK turnover group
0   2013-06-30  0.000000     7195            low
1   2013-09-30  0.025201     7195            low
2   2013-12-31  0.001058     7195            low
3   2014-03-31  0.026546     7195            low
4   2014-06-30  0.050941     7195         medium
..         ...       ...      ...            ...
3   2018-06-30  0.018762  1719739            low
0   2017-09-30  0.000000  1721608            low
1   2017-12-31  0.000000  1721608            low
2   2018-03-31  0.066387  1721608         medium
3   2018-06-30  0.040462  1721608            low

[7612 rows x 4 columns]

In [75]:
form13f_FF1 = form13f_inflow[form13f_inflow.iCIK.isin(Turnover_filtered.iCIK.unique())]
form13f_FF1

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos,buy,sell
35,39276296,7195,219350105,2013-06-30,2013-08-12,302325.0,4302000.0,0.018715,43 days,Materials,Large-Cap Value,15.1100,284712.111185,2013-05-01,14.3300,4.079925e+06,4302000,0
29,39276307,7195,452308109,2013-06-30,2013-08-12,69101.0,4780000.0,0.020794,43 days,Industrial,Large-Cap Blend,73.5200,65016.322089,2013-05-01,63.8700,4.152592e+06,4780000,0
36,39276330,7195,907818108,2013-06-30,2013-08-12,33615.0,5186000.0,0.022561,43 days,Materials,MidCap Growth,79.5850,65163.033235,2013-05-01,72.8350,4.746150e+06,5186000,0
44,39276309,7195,458140100,2013-06-30,2013-08-12,189457.0,4591000.0,0.019972,43 days,Technology,Large-Cap Growth,22.6400,202782.685512,2013-05-01,23.9900,4.864757e+06,4591000,0
12,39276310,7195,459200101,2013-06-30,2013-08-12,21721.0,4151000.0,0.018058,43 days,Energy,Small-Cap Blend,189.0900,21952.509387,2013-05-01,199.6300,4.382379e+06,4151000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1678596,65812266,1721608,78463X863,2018-06-30,2018-07-13,8483.0,332000.0,0.001210,13 days,Health Care,MidCap Value,37.8504,8771.373618,2018-05-01,38.7655,3.400267e+05,20000,0
1678584,65812256,1721608,78467V608,2018-06-30,2018-07-13,174973.0,8218000.0,0.029951,13 days,Communications,MidCap Value,45.2506,181610.851569,2018-05-01,45.0628,8.183893e+06,6341000,0
1678583,65812284,1721608,78468R408,2018-06-30,2018-07-13,31911.0,871000.0,0.003174,13 days,Communications,MidCap Value,26.2391,33194.736100,2018-05-01,25.9226,8.604939e+05,871000,0
1678606,65812253,1721608,92189F494,2018-06-30,2018-07-13,83255.0,1417000.0,0.005164,13 days,NA,NA,NaN,NaN,2018-05-01,NaN,NaN,0,98000
1678600,65812271,1721608,97717W422,2018-06-30,2018-07-13,330467.0,8318000.0,0.030316,13 days,Materials,Large-Cap Blend,25.2507,329416.610233,2018-05-01,26.1881,8.626795e+06,8318000,0

### 2. Survival time: funds with high / medium survival times

In [76]:
period_filtered = period[(period["survival group"] == "high") | (period["survival group"] == "medium")]
period_filtered

         iCIK iPERIOD_END_min iPERIOD_END_max survival time survival group
0        7195      2013-06-30      2018-06-30     1826 days           high
1       18748      2013-06-30      2016-09-30     1188 days         medium
2       19475      2013-06-30      2018-06-30     1826 days           high
4       21175      2013-06-30      2018-06-30     1826 days           high
5       36066      2013-12-31      2018-06-30     1642 days         medium
...       ...             ...             ...           ...            ...
1591  1645890      2015-06-30      2018-06-30     1096 days         medium
1594  1648101      2015-06-30      2018-06-30     1096 days         medium
1599  1649888      2015-06-30      2018-06-30     1096 days         medium
1602  1650654      2015-06-30      2018-06-30     1096 days         medium
1610  1653866      2015-09-30      2018-06-30     1004 days         medium

[1082 rows x 5 columns]

In [77]:
form13f_FF2 = form13f_FF1[form13f_FF1.iCIK.isin(period_filtered.iCIK.unique())]
form13f_FF2

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos,buy,sell
35,39276296,7195,219350105,2013-06-30,2013-08-12,302325.0,4302000.0,0.018715,43 days,Materials,Large-Cap Value,15.110,284712.111185,2013-05-01,14.330,4.079925e+06,4302000,0
29,39276307,7195,452308109,2013-06-30,2013-08-12,69101.0,4780000.0,0.020794,43 days,Industrial,Large-Cap Blend,73.520,65016.322089,2013-05-01,63.870,4.152592e+06,4780000,0
36,39276330,7195,907818108,2013-06-30,2013-08-12,33615.0,5186000.0,0.022561,43 days,Materials,MidCap Growth,79.585,65163.033235,2013-05-01,72.835,4.746150e+06,5186000,0
44,39276309,7195,458140100,2013-06-30,2013-08-12,189457.0,4591000.0,0.019972,43 days,Technology,Large-Cap Growth,22.640,202782.685512,2013-05-01,23.990,4.864757e+06,4591000,0
12,39276310,7195,459200101,2013-06-30,2013-08-12,21721.0,4151000.0,0.018058,43 days,Energy,Small-Cap Blend,189.090,21952.509387,2013-05-01,199.630,4.382379e+06,4151000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1664701,65828192,1653866,406216101,2018-06-30,2018-07-17,25045.0,1129000.0,0.002557,17 days,Energy,Small-Cap Blend,45.060,25055.481580,2018-05-01,52.440,1.313909e+06,0,67000
1664712,65828136,1653866,78467X109,2018-06-30,2018-07-17,6346.0,1540000.0,0.003488,17 days,Financial,Large-Cap Blend,251.280,6128.621458,2018-05-01,240.760,1.475527e+06,8000,0
1664711,65828101,1653866,06740L444,2018-06-30,2018-07-17,74198.0,1407000.0,0.003187,17 days,Energy,Small-Cap Growth,19.330,72788.411795,2018-05-01,20.840,1.516911e+06,0,1000
1664673,65828107,1653866,370334104,2018-06-30,2018-07-17,10823.0,479000.0,0.001085,17 days,Communications,MidCap Value,44.230,10829.753561,2018-05-01,43.550,4.716358e+05,479000,0
1664752,65828140,1653866,H2906T109,2018-06-30,2018-07-17,4000.0,244000.0,0.000553,17 days,Materials,Small-Cap Blend,64.060,3808.929129,2018-05-01,58.990,2.246887e+05,244000,0

### 3. Volatility: funds with low / medium volatility

In [78]:
volatility_filtered = volatility[(volatility["volatility group"] == "low") | (volatility["volatility group"] == "medium")]
volatility_filtered

         iCIK  volatility volatility group
0        7195    0.042513           medium
1       18748    0.037731              low
2       19475    0.031249              low
3       19481    0.009252              low
5       36066    0.033806              low
...       ...         ...              ...
1801  1713735    0.034755              low
1802  1714341    0.052941           medium
1803  1716399    0.035538              low
1804  1719739    0.055073           medium
1805  1721608    0.025339              low

[1417 rows x 3 columns]

In [79]:
form13f_FF3 = form13f_FF2[form13f_FF2.iCIK.isin(volatility_filtered.iCIK.unique())]
form13f_FF3

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos,buy,sell
35,39276296,7195,219350105,2013-06-30,2013-08-12,302325.0,4302000.0,0.018715,43 days,Materials,Large-Cap Value,15.110,284712.111185,2013-05-01,14.330,4.079925e+06,4302000,0
29,39276307,7195,452308109,2013-06-30,2013-08-12,69101.0,4780000.0,0.020794,43 days,Industrial,Large-Cap Blend,73.520,65016.322089,2013-05-01,63.870,4.152592e+06,4780000,0
36,39276330,7195,907818108,2013-06-30,2013-08-12,33615.0,5186000.0,0.022561,43 days,Materials,MidCap Growth,79.585,65163.033235,2013-05-01,72.835,4.746150e+06,5186000,0
44,39276309,7195,458140100,2013-06-30,2013-08-12,189457.0,4591000.0,0.019972,43 days,Technology,Large-Cap Growth,22.640,202782.685512,2013-05-01,23.990,4.864757e+06,4591000,0
12,39276310,7195,459200101,2013-06-30,2013-08-12,21721.0,4151000.0,0.018058,43 days,Energy,Small-Cap Blend,189.090,21952.509387,2013-05-01,199.630,4.382379e+06,4151000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1664701,65828192,1653866,406216101,2018-06-30,2018-07-17,25045.0,1129000.0,0.002557,17 days,Energy,Small-Cap Blend,45.060,25055.481580,2018-05-01,52.440,1.313909e+06,0,67000
1664712,65828136,1653866,78467X109,2018-06-30,2018-07-17,6346.0,1540000.0,0.003488,17 days,Financial,Large-Cap Blend,251.280,6128.621458,2018-05-01,240.760,1.475527e+06,8000,0
1664711,65828101,1653866,06740L444,2018-06-30,2018-07-17,74198.0,1407000.0,0.003187,17 days,Energy,Small-Cap Growth,19.330,72788.411795,2018-05-01,20.840,1.516911e+06,0,1000
1664673,65828107,1653866,370334104,2018-06-30,2018-07-17,10823.0,479000.0,0.001085,17 days,Communications,MidCap Value,44.230,10829.753561,2018-05-01,43.550,4.716358e+05,479000,0
1664752,65828140,1653866,H2906T109,2018-06-30,2018-07-17,4000.0,244000.0,0.000553,17 days,Materials,Small-Cap Blend,64.060,3808.929129,2018-05-01,58.990,2.246887e+05,244000,0

### 4. performance: funds with high / medium cik_mean_returns

In [80]:
cik_mean_returns_filtered = cik_mean_returns[(cik_mean_returns["performance"] == "high") | (cik_mean_returns["performance"] == "medium")]
cik_mean_returns_filtered

         iCIK    return performance
0        7195  0.025251      medium
2       19475  0.050653        high
3       19481  0.060120        high
4       21175  0.020743      medium
5       36066  0.023635      medium
...       ...       ...         ...
1797  1712671  0.020454      medium
1799  1713521  0.032111        high
1801  1713735  0.030064        high
1803  1716399  0.021163      medium
1804  1719739  0.039878        high

[1111 rows x 3 columns]

In [81]:
form13f_FF4 = form13f_FF3[form13f_FF3.iCIK.isin(cik_mean_returns_filtered.iCIK.unique())]
form13f_FF4

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos,buy,sell
35,39276296,7195,219350105,2013-06-30,2013-08-12,302325.0,4302000.0,0.018715,43 days,Materials,Large-Cap Value,15.110,284712.111185,2013-05-01,14.330,4.079925e+06,4302000,0
29,39276307,7195,452308109,2013-06-30,2013-08-12,69101.0,4780000.0,0.020794,43 days,Industrial,Large-Cap Blend,73.520,65016.322089,2013-05-01,63.870,4.152592e+06,4780000,0
36,39276330,7195,907818108,2013-06-30,2013-08-12,33615.0,5186000.0,0.022561,43 days,Materials,MidCap Growth,79.585,65163.033235,2013-05-01,72.835,4.746150e+06,5186000,0
44,39276309,7195,458140100,2013-06-30,2013-08-12,189457.0,4591000.0,0.019972,43 days,Technology,Large-Cap Growth,22.640,202782.685512,2013-05-01,23.990,4.864757e+06,4591000,0
12,39276310,7195,459200101,2013-06-30,2013-08-12,21721.0,4151000.0,0.018058,43 days,Energy,Small-Cap Blend,189.090,21952.509387,2013-05-01,199.630,4.382379e+06,4151000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1664701,65828192,1653866,406216101,2018-06-30,2018-07-17,25045.0,1129000.0,0.002557,17 days,Energy,Small-Cap Blend,45.060,25055.481580,2018-05-01,52.440,1.313909e+06,0,67000
1664712,65828136,1653866,78467X109,2018-06-30,2018-07-17,6346.0,1540000.0,0.003488,17 days,Financial,Large-Cap Blend,251.280,6128.621458,2018-05-01,240.760,1.475527e+06,8000,0
1664711,65828101,1653866,06740L444,2018-06-30,2018-07-17,74198.0,1407000.0,0.003187,17 days,Energy,Small-Cap Growth,19.330,72788.411795,2018-05-01,20.840,1.516911e+06,0,1000
1664673,65828107,1653866,370334104,2018-06-30,2018-07-17,10823.0,479000.0,0.001085,17 days,Communications,MidCap Value,44.230,10829.753561,2018-05-01,43.550,4.716358e+05,479000,0
1664752,65828140,1653866,H2906T109,2018-06-30,2018-07-17,4000.0,244000.0,0.000553,17 days,Materials,Small-Cap Blend,64.060,3808.929129,2018-05-01,58.990,2.246887e+05,244000,0

In [82]:
print("number of funds after further filtering:", len(form13f_FF4.iCIK.unique()))

number of funds after further filtering: 227

In [83]:
# remaining stocks in fund_prices
fund_prices_FF = fund_prices[fund_prices.pSP_CUSIP.isin(form13f_FF4.iCUSIP.unique())]
len(fund_prices_FF.pSP_CUSIP.unique())

4792

# Files for feature engineering (EXHIBIT 7)

In [84]:
form13f_FF4.to_csv("../output/form13f_FF4.csv", sep='\t', index=False)

In [85]:
fund_prices_FF.to_csv("../output/fund_prices_FF.csv", sep='\t', index=False)

In [86]:
form13f[form13f.iPERIOD_END >= datetime.date(2013,6,30)].iPERIOD_END.unique()

array([datetime.date(2013, 6, 30), datetime.date(2014, 12, 31),
       datetime.date(2014, 9, 30), datetime.date(2014, 6, 30),
       datetime.date(2014, 3, 31), datetime.date(2013, 12, 31),
       datetime.date(2013, 9, 30), datetime.date(2015, 3, 31),
       datetime.date(2015, 6, 30), datetime.date(2015, 9, 30),
       datetime.date(2015, 12, 31), datetime.date(2016, 3, 31),
       datetime.date(2016, 6, 30), datetime.date(2016, 9, 30),
       datetime.date(2016, 12, 31), datetime.date(2017, 3, 31),
       datetime.date(2017, 6, 30), datetime.date(2017, 9, 30),
       datetime.date(2017, 12, 31), datetime.date(2018, 3, 31),
       datetime.date(2018, 6, 30), datetime.date(2018, 9, 30),
       datetime.date(2018, 12, 31), datetime.date(2019, 3, 31),
       datetime.date(2019, 6, 30), datetime.date(2019, 9, 30),
       datetime.date(2019, 12, 31), datetime.date(2020, 3, 31)],
      dtype=object)

In [87]:
# split years!!!!
# both form13f & prices：2013.6.30-2018.6.30 train; 2018.9.30-2020.3.31 test quarterly 每季test完把data加进train里？目标值是return？
# 构建因子，model selection# this is an expanding window