In [1]:
import pandas as pd
import numpy as np
import datetime
from dateutil.relativedelta import *

In [2]:
form13f = pd.read_csv("../RebellionData/rebellion_databases/form13f.csv", sep=";")

In [3]:
form13f["iFILING_DATE"]= pd.to_datetime(form13f["iFILING_DATE"]).dt.date
form13f["iPERIOD_END"]= pd.to_datetime(form13f["iPERIOD_END"]).dt.date

In [4]:
form13f

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iAMEND,iRESTATEMENT,iTYPE,iQTY,iMARKET_VALUE,iLONG_FRACTION
0,4443748,216235,055622104,1999-09-30,2000-01-03,0,0,0,28287.0,3134550.0,0.009282
1,4443749,216235,020039103,1999-09-30,2000-01-03,0,0,0,79199.0,5690620.0,0.016851
2,4443750,216235,713448108,1999-09-30,2000-01-03,0,0,0,186140.0,5795950.0,0.017163
3,4443751,216235,002824100,1999-09-30,2000-01-03,0,0,0,169555.0,6290420.0,0.018627
4,4443752,216235,05964H105,1999-09-30,2000-01-03,0,0,0,16897.0,174250.0,0.000516
...,...,...,...,...,...,...,...,...,...,...,...
57569231,74561590,1730479,039483102,2020-03-31,2020-04-23,0,0,0,300.0,11000.0,0.000086
57569232,74561591,1730479,88160R101,2020-03-31,2020-04-23,0,0,0,25.0,13000.0,0.000102
57569233,74561592,1730479,921937793,2020-03-31,2020-04-23,0,0,0,230.0,25000.0,0.000196
57569234,74561593,1730479,863667101,2020-03-31,2020-04-23,0,0,0,1030.0,171000.0,0.001341
57569235,74561594,1730479,232806109,2020-03-31,2020-04-23,0,0,0,100.0,2000.0,0.000016

# I. Data Processing

## Filter individual records

1. Remove records that were filed before June 30, 2013.

In [5]:
form13f_2013 = form13f[form13f.iFILING_DATE >= datetime.date(2013, 6, 30)]
form13f_2013

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iAMEND,iRESTATEMENT,iTYPE,iQTY,iMARKET_VALUE,iLONG_FRACTION
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,0,0,0,96510.0,3366000.0,0.023443
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,0,0,0,70214.0,5249000.0,0.036557
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,0,0,0,346115.0,15471000.0,0.107748
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,0,0,0,882340.0,11347000.0,0.079026
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,0,0,0,129065.0,3620000.0,0.025212
...,...,...,...,...,...,...,...,...,...,...,...
57569231,74561590,1730479,039483102,2020-03-31,2020-04-23,0,0,0,300.0,11000.0,0.000086
57569232,74561591,1730479,88160R101,2020-03-31,2020-04-23,0,0,0,25.0,13000.0,0.000102
57569233,74561592,1730479,921937793,2020-03-31,2020-04-23,0,0,0,230.0,25000.0,0.000196
57569234,74561593,1730479,863667101,2020-03-31,2020-04-23,0,0,0,1030.0,171000.0,0.001341
57569235,74561594,1730479,232806109,2020-03-31,2020-04-23,0,0,0,100.0,2000.0,0.000016

2. Remove records that are duplicates.
3. Remove records wherein QTY is zero.
4. Remove records wherein MARKET_VALUE is zero.

In [6]:
form13f_duplicate = form13f_2013.drop_duplicates()
form13f_QTY = form13f_duplicate[form13f_duplicate["iQTY"] != 0]
form13f_MARKET_VALUE = form13f_QTY[form13f_QTY["iMARKET_VALUE"] != 0]
form13f_MARKET_VALUE["FILING_INTERVAL"] = form13f_MARKET_VALUE["iFILING_DATE"]-form13f_MARKET_VALUE["iPERIOD_END"]
form13f_MARKET_VALUE

/var/folders/gd/f9gfs56x5qgb9q0h_h7dwwrc0000gn/T/ipykernel_8145/4067883774.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  form13f_MARKET_VALUE["FILING_INTERVAL"] = form13f_MARKET_VALUE["iFILING_DATE"]-form13f_MARKET_VALUE["iPERIOD_END"]

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iAMEND,iRESTATEMENT,iTYPE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,0,0,0,96510.0,3366000.0,0.023443,32 days
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,0,0,0,70214.0,5249000.0,0.036557,32 days
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,0,0,0,346115.0,15471000.0,0.107748,32 days
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,0,0,0,882340.0,11347000.0,0.079026,32 days
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,0,0,0,129065.0,3620000.0,0.025212,32 days
...,...,...,...,...,...,...,...,...,...,...,...,...
57569231,74561590,1730479,039483102,2020-03-31,2020-04-23,0,0,0,300.0,11000.0,0.000086,23 days
57569232,74561591,1730479,88160R101,2020-03-31,2020-04-23,0,0,0,25.0,13000.0,0.000102,23 days
57569233,74561592,1730479,921937793,2020-03-31,2020-04-23,0,0,0,230.0,25000.0,0.000196,23 days
57569234,74561593,1730479,863667101,2020-03-31,2020-04-23,0,0,0,1030.0,171000.0,0.001341,23 days
57569235,74561594,1730479,232806109,2020-03-31,2020-04-23,0,0,0,100.0,2000.0,0.000016,23 days

## Filter entire funds for each period

1. Funds must complete filing within 46 days of the end of the quarter.

In [7]:
# iCIK is fund identifier
form13f_46 = form13f_MARKET_VALUE.groupby(["iCIK", "iPERIOD_END"]).filter(lambda x:(x.FILING_INTERVAL <= datetime.timedelta(days = 45)).all())
form13f_46

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iAMEND,iRESTATEMENT,iTYPE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,0,0,0,96510.0,3366000.0,0.023443,32 days
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,0,0,0,70214.0,5249000.0,0.036557,32 days
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,0,0,0,346115.0,15471000.0,0.107748,32 days
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,0,0,0,882340.0,11347000.0,0.079026,32 days
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,0,0,0,129065.0,3620000.0,0.025212,32 days
...,...,...,...,...,...,...,...,...,...,...,...,...
57569231,74561590,1730479,039483102,2020-03-31,2020-04-23,0,0,0,300.0,11000.0,0.000086,23 days
57569232,74561591,1730479,88160R101,2020-03-31,2020-04-23,0,0,0,25.0,13000.0,0.000102,23 days
57569233,74561592,1730479,921937793,2020-03-31,2020-04-23,0,0,0,230.0,25000.0,0.000196,23 days
57569234,74561593,1730479,863667101,2020-03-31,2020-04-23,0,0,0,1030.0,171000.0,0.001341,23 days
57569235,74561594,1730479,232806109,2020-03-31,2020-04-23,0,0,0,100.0,2000.0,0.000016,23 days

2. Funds must have exactly one filing point for each quarter i.e., remove funds with amendments.

In [8]:
# counterexample
form13f_46[(form13f_46["iCIK"] == 1536562) & (form13f_46["iPERIOD_END"] == datetime.date(2014,12,31))]

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iAMEND,iRESTATEMENT,iTYPE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26100887,50955873,1536562,438516106,2014-12-31,2015-02-02,0,0,0,9000.0,769000.0,0.020278,33 days
26100888,50955874,1536562,71654V101,2014-12-31,2015-02-02,0,0,0,98132.0,10440000.0,0.275295,33 days
26100889,50955875,1536562,05961W105,2014-12-31,2015-02-02,0,0,0,68521.0,3180000.0,0.083854,33 days
26100890,50955876,1536562,594918104,2014-12-31,2015-02-02,0,0,0,23000.0,1141000.0,0.030087,33 days
26100891,50955877,1536562,437076102,2014-12-31,2015-02-02,0,0,0,6200.0,626000.0,0.016507,33 days
26100892,50955878,1536562,81369Y407,2014-12-31,2015-02-02,0,0,0,16500.0,1163000.0,0.030667,33 days
26100893,50955879,1536562,03524A108,2014-12-31,2015-02-02,0,0,0,105428.0,11476000.0,0.302613,33 days
26100894,50955880,1536562,38259P706,2014-12-31,2015-02-02,0,0,0,3500.0,744000.0,0.019619,33 days
26100895,50955881,1536562,146229109,2014-12-31,2015-02-02,0,0,0,92790.0,8384000.0,0.221080,33 days
26119280,50974218,1536562,438516106,2014-12-31,2015-02-03,1,1,0,9000.0,899000.0,0.000000,34 days
26119281,50974219,1536562,879273209,2014-12-31,2015-02-03,1,1,0,16719.0,324000.0,0.000000,34 days
26119282,50974220,1536562,71654V101,2014-12-31,2015-02-03,1,1,0,98132.0,744000.0,0.000000,34 days
26119283,50974221,1536562,918204108,2014-12-31,2015-02-03,1,1,0,557479.0,41755000.0,0.000000,34 days
26119284,50974222,1536562,82481R106,2014-12-31,2015-02-03,1,1,0,21246.0,4516000.0,0.000000,34 days
26119285,50974223,1536562,88579Y101,2014-12-31,2015-02-03,1,1,0,500000.0,82160000.0,0.000000,34 days
26119286,50974224,1536562,07329M100,2014-12-31,2015-02-03,1,1,0,1826950.0,25194000.0,0.000000,34 days
26119287,50974225,1536562,78462F103,2014-12-31,2015-02-03,1,1,0,23343.0,4797000.0,0.000000,34 days
26119288,50974226,1536562,81369Y407,2014-12-31,2015-02-03,1,1,0,16500.0,1190000.0,0.000000,34 days
26119289,50974227,1536562,81369Y308,2014-12-31,2015-02-03,1,1,0,135580.0,6574000.0,0.000000,34 days
26119290,50974228,1536562,03524A108,2014-12-31,2015-02-03,1,1,0,105428.0,11842000.0,0.000000,34 days
26119291,50974229,1536562,38259P706,2014-12-31,2015-02-03,1,1,0,3500.0,1842000.0,0.000000,34 days
26119292,50974230,1536562,09247X101,2014-12-31,2015-02-03,1,1,0,9500.0,3397000.0,0.000000,34 days
26119293,50974231,1536562,05961W105,2014-12-31,2015-02-03,1,1,0,68521.0,2997000.0,0.000000,34 days
26119294,50974232,1536562,437076102,2014-12-31,2015-02-03,1,1,0,6200.0,651000.0,0.000000,34 days
26119295,50974233,1536562,037833100,2014-12-31,2015-02-03,1,1,0,5500.0,607000.0,0.000000,34 days
26119296,50974234,1536562,369550108,2014-12-31,2015-02-03,1,1,0,3300.0,454000.0,0.000000,34 days
26119297,50974235,1536562,57636Q104,2014-12-31,2015-02-03,1,1,0,33498.0,2886000.0,0.000000,34 days
26119298,50974236,1536562,832696405,2014-12-31,2015-02-03,1,1,0,2489.0,251000.0,0.000000,34 days
26119299,50974237,1536562,254687106,2014-12-31,2015-02-03,1,1,0,18000.0,1695000.0,0.000000,34 days
26119300,50974238,1536562,146229109,2014-12-31,2015-02-03,1,1,0,92790.0,8101000.0,0.000000,34 days
26119301,50974239,1536562,594918104,2014-12-31,2015-02-03,1,1,0,23000.0,1069000.0,0.000000,34 days
26119302,50974240,1536562,29244A102,2014-12-31,2015-02-03,1,1,0,10752.0,101000.0,0.000000,34 days
26119303,50974241,1536562,984245100,2014-12-31,2015-02-03,1,1,0,1911450.0,50596000.0,0.000000,34 days
26119304,50974242,1536562,254709108,2014-12-31,2015-02-03,1,1,0,4500.0,295000.0,0.000000,34 days
26119305,50974243,1536562,231021106,2014-12-31,2015-02-03,1,1,0,6400.0,923000.0,0.000000,34 days
26119306,50974244,1536562,693506107,2014-12-31,2015-02-03,1,1,0,8947.0,2068000.0,0.000000,34 days
26119307,50974245,1536562,615369105,2014-12-31,2015-02-03,1,1,0,13500.0,1293000.0,0.000000,34 days
26119308,50974246,1536562,478160104,2014-12-31,2015-02-03,1,1,0,10200.0,1067000.0,0.000000,34 days
26119309,50974247,1536562,767204100,2014-12-31,2015-02-03,1,1,0,212290.0,9779000.0,0.000000,34 days

In [9]:
# remove the whole fund for that filing period if amend/restate/type=1
form13f_amend = form13f_46.groupby(["iCIK", "iPERIOD_END"]).filter(lambda x:((x.iAMEND == 0)&(x.iRESTATEMENT == 0)&(x.iTYPE == 0)).all())
form13f_amend = form13f_amend.drop('iAMEND', axis=1)
form13f_amend = form13f_amend.drop('iRESTATEMENT', axis=1)
form13f_amend = form13f_amend.drop('iTYPE', axis=1)
form13f_amend

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,96510.0,3366000.0,0.023443,32 days
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,70214.0,5249000.0,0.036557,32 days
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,346115.0,15471000.0,0.107748,32 days
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,882340.0,11347000.0,0.079026,32 days
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,129065.0,3620000.0,0.025212,32 days
...,...,...,...,...,...,...,...,...,...
57569231,74561590,1730479,039483102,2020-03-31,2020-04-23,300.0,11000.0,0.000086,23 days
57569232,74561591,1730479,88160R101,2020-03-31,2020-04-23,25.0,13000.0,0.000102,23 days
57569233,74561592,1730479,921937793,2020-03-31,2020-04-23,230.0,25000.0,0.000196,23 days
57569234,74561593,1730479,863667101,2020-03-31,2020-04-23,1030.0,171000.0,0.001341,23 days
57569235,74561594,1730479,232806109,2020-03-31,2020-04-23,100.0,2000.0,0.000016,23 days

3. Funds must have between 20 and 200 holdings.

In [10]:
form13f_20_200 = form13f_amend.groupby(["iCIK", "iPERIOD_END"]).filter(lambda x: ((20 <= len(x))&(len(x) <= 200)))
form13f_20_200

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,96510.0,3366000.0,0.023443,32 days
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,70214.0,5249000.0,0.036557,32 days
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,346115.0,15471000.0,0.107748,32 days
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,882340.0,11347000.0,0.079026,32 days
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,129065.0,3620000.0,0.025212,32 days
...,...,...,...,...,...,...,...,...,...
57568897,74561256,1638520,550021109,2020-03-31,2020-04-23,1320.0,250000.0,0.001275,23 days
57568898,74561257,1638520,g1151c101,2020-03-31,2020-04-23,4053.0,662000.0,0.003377,23 days
57568899,74561258,1638520,988498101,2020-03-31,2020-04-23,3611.0,247000.0,0.001260,23 days
57568900,74561259,1638520,78462f103,2020-03-31,2020-04-23,1742.0,449000.0,0.002290,23 days
57568901,74561260,1638520,88160R101,2020-03-31,2020-04-23,591.0,310000.0,0.001581,23 days

4. Funds must be valued between 100M and 500M.

In [11]:
form13f_100_500 = form13f_20_200.groupby(["iCIK", "iPERIOD_END"]).filter(lambda x:((100000000 <= sum(x.iMARKET_VALUE))&(sum(x.iMARKET_VALUE) <= 500000000)))
form13f_100_500

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,96510.0,3366000.0,0.023443,32 days
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,70214.0,5249000.0,0.036557,32 days
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,346115.0,15471000.0,0.107748,32 days
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,882340.0,11347000.0,0.079026,32 days
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,129065.0,3620000.0,0.025212,32 days
...,...,...,...,...,...,...,...,...,...
57568897,74561256,1638520,550021109,2020-03-31,2020-04-23,1320.0,250000.0,0.001275,23 days
57568898,74561257,1638520,g1151c101,2020-03-31,2020-04-23,4053.0,662000.0,0.003377,23 days
57568899,74561258,1638520,988498101,2020-03-31,2020-04-23,3611.0,247000.0,0.001260,23 days
57568900,74561259,1638520,78462f103,2020-03-31,2020-04-23,1742.0,449000.0,0.002290,23 days
57568901,74561260,1638520,88160R101,2020-03-31,2020-04-23,591.0,310000.0,0.001581,23 days

5. Funds had to meet all filtering criteria for at least one year -- Survival funds

In [12]:
form13f_1year = form13f_100_500.groupby("iCIK").filter(lambda x:(x.iPERIOD_END.nunique() >= 4))
form13f_1year

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL
26088669,38587073,1349353,002824100,2013-06-30,2013-08-01,96510.0,3366000.0,0.023443,32 days
26088670,38587074,1349353,025816109,2013-06-30,2013-08-01,70214.0,5249000.0,0.036557,32 days
26088671,38587075,1349353,026874784,2013-06-30,2013-08-01,346115.0,15471000.0,0.107748,32 days
26088672,38587076,1349353,060505104,2013-06-30,2013-08-01,882340.0,11347000.0,0.079026,32 days
26088673,38587077,1349353,064058100,2013-06-30,2013-08-01,129065.0,3620000.0,0.025212,32 days
...,...,...,...,...,...,...,...,...,...
57568408,74560767,1670053,478160104,2020-03-31,2020-04-23,30167.0,3956000.0,0.034295,23 days
57568409,74560768,1670053,922908769,2020-03-31,2020-04-23,2287.0,295000.0,0.002557,23 days
57568410,74560769,1670053,941848103,2020-03-31,2020-04-23,12301.0,2239000.0,0.019410,23 days
57568411,74560770,1670053,502431109,2020-03-31,2020-04-23,5373.0,968000.0,0.008392,23 days
57568412,74560771,1670053,863667101,2020-03-31,2020-04-23,5882.0,979000.0,0.008487,23 days

In [13]:
print("number of survival funds:", len(form13f_1year["iCIK"].unique()))

number of survival funds: 2292

In [14]:
fund_stocks = form13f_1year["iCUSIP"].unique()
print(len(fund_stocks))
fund_stocks

20365

array(['002824100', '025816109', '026874784', ..., '879433845',
       '910331107', '74347B276'], dtype=object)

# II. FUND CLASSIFICATION AND FEATURE EXTRACTION

### 1. Industry Classification (correlation to sector ETFs)

In [15]:
prices = pd.read_csv("../RebellionData/rebellion_databases/prices.csv", sep=";")

In [16]:
prices["pSP_DATE"]= pd.to_datetime(prices["pSP_DATE"]).dt.date
prices.sort_values(by=["pSP_DATE"], inplace = True, ascending = True)

In [17]:
prices

,pSP_CUSIP,pSP_EXCHANGE,pSP_TICKER,pSP_DATE,pSP_VOLUME,pSP_OPEN,pSP_HIGH,pSP_LOW,pSP_CLOSE
9581087,73936Q405,N,PAO,2013-01-01,0,0.215,0.215,0.215,0.2150
9877577,73937B100,N,PKN,2013-01-01,0,46.700,46.700,46.700,46.6950
9882024,78464A805,N,TMW,2013-01-01,0,4.324,4.324,4.324,4.3240
9882494,73935X203,N,PWO,2013-01-01,0,24.640,24.640,24.640,24.6445
9583019,30304T106,N,FSG,2013-01-01,0,1.110,1.110,1.110,1.1120
...,...,...,...,...,...,...,...,...,...
34828660,46116V105,O,INTL,2020-05-29,149226,51.700,51.700,49.720,51.0100
34828622,458140100,O,INTC,2020-05-29,33395740,61.900,63.660,61.620,62.9300
34828584,457669307,O,INSM,2020-05-29,1020255,24.760,25.000,23.805,24.2900
34828774,45773Y105,O,INWK,2020-05-29,373154,1.290,1.290,1.160,1.1900
35410514,98979F107,A,ZOM,2020-05-29,33669380,0.160,0.162,0.154,0.1577

In [18]:
print("total number of stocks:", len(prices["pSP_CUSIP"].unique()))

total number of stocks: 30115

In [19]:
# prices of fund stocks
fund_prices = prices[prices["pSP_CUSIP"].isin(fund_stocks)]
len(fund_prices["pSP_CUSIP"].unique())

11320

In [20]:
XLF = prices.loc[prices["pSP_TICKER"] == "XLF" ]
XLY = prices.loc[prices["pSP_TICKER"] == "XLY" ]
XLK = prices.loc[prices["pSP_TICKER"] == "XLK" ]
XLB = prices.loc[prices["pSP_TICKER"] == "XLB" ]
XLI = prices.loc[prices["pSP_TICKER"] == "XLI" ]
XLE = prices.loc[prices["pSP_TICKER"] == "XLE" ]
XLU = prices.loc[prices["pSP_TICKER"] == "XLU" ]
XLV = prices.loc[prices["pSP_TICKER"] == "XLV" ]
XLP = prices.loc[prices["pSP_TICKER"] == "XLP" ]
VOX = prices.loc[prices["pSP_TICKER"] == "VOX" ]

In [31]:
VOX

,pSP_CUSIP,pSP_EXCHANGE,pSP_TICKER,pSP_DATE,pSP_VOLUME,pSP_OPEN,pSP_HIGH,pSP_LOW,pSP_CLOSE
2830918,92204A884,N,VOX,2013-01-02,1254705,63.94,64.09,63.15,63.7305
2830917,92204A884,N,VOX,2013-01-03,121946,63.98,64.12,63.55,63.7931
2830916,92204A884,N,VOX,2013-01-04,37255,63.79,64.33,63.69,64.2132
4627331,92204A884,N,VOX,2013-01-07,55715,64.16,64.40,63.95,64.3651
4627330,92204A884,N,VOX,2013-01-08,36025,64.37,64.37,63.24,63.3372
...,...,...,...,...,...,...,...,...,...
34741130,92204A884,N,VOX,2020-05-22,599900,91.78,92.21,91.14,92.1200
34741131,92204A884,N,VOX,2020-05-26,196900,94.09,94.09,92.47,92.5400
34741132,92204A884,N,VOX,2020-05-27,221700,93.02,93.52,91.42,93.5200
34741133,92204A884,N,VOX,2020-05-28,252900,93.10,94.11,92.33,92.6900
34741134,92204A884,N,VOX,2020-05-29,137200,92.57,93.53,91.85,93.1800

In [32]:
XLF = XLF[XLF["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLY = XLY[XLY["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLK = XLK[XLK["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLB = XLB[XLB["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLI = XLI[XLI["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLE = XLE[XLE["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLU = XLU[XLU["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLV = XLV[XLV["pSP_DATE"].isin(VOX["pSP_DATE"])]
XLP = XLP[XLP["pSP_DATE"].isin(VOX["pSP_DATE"])]

In [42]:
Etf_data = {'pSP_DATE':VOX["pSP_DATE"].values,
            'XLF':XLF["pSP_CLOSE"].values,
            'XLY':XLY["pSP_CLOSE"].values,
            'XLK':XLK["pSP_CLOSE"].values,
            'XLB':XLB["pSP_CLOSE"].values,
            'XLI':XLI["pSP_CLOSE"].values,
            'XLE':XLE["pSP_CLOSE"].values,
            'XLU':XLU["pSP_CLOSE"].values,
            'XLV':XLV["pSP_CLOSE"].values,
            'XLP':XLP["pSP_CLOSE"].values,
            'VOX':VOX["pSP_CLOSE"].values}

Etf_df = pd.DataFrame(Etf_data)
Etf_df

,pSP_DATE,XLF,XLY,XLK,XLB,XLI,XLE,XLU,XLV,XLP,VOX
0,2013-01-02,12.5558,45.5328,27.5843,35.2652,35.6120,66.0461,30.5576,38.1085,32.1762,63.7305
1,2013-01-03,12.5409,45.6456,27.4085,35.0086,35.6303,66.0280,30.5576,38.1554,32.0953,63.7931
2,2013-01-04,12.6897,45.8148,27.2974,35.4393,35.8964,66.7608,30.7123,38.3240,32.1852,64.2132
3,2013-01-07,12.6600,45.7020,27.2604,35.3660,35.7404,66.2451,30.4115,38.4458,31.9695,64.3651
4,2013-01-08,12.6228,45.5704,27.1586,35.4210,35.4652,66.0280,30.3170,38.4552,31.8796,63.3372
...,...,...,...,...,...,...,...,...,...,...,...
1859,2020-05-22,21.9200,121.2300,96.4900,52.9300,63.8400,38.4800,56.4800,99.6200,57.4700,92.1200
1860,2020-05-26,23.0600,123.1500,96.3900,54.3800,66.5200,39.5500,56.8500,99.4400,57.7800,92.5400
1861,2020-05-27,24.0600,125.2600,96.9400,54.9300,68.7400,40.0600,57.5300,100.4700,58.6500,93.5200
1862,2020-05-28,23.6800,123.7400,96.7500,55.4400,68.0900,38.9400,59.2300,101.7800,59.1700,92.6900
1863,2020-05-29,23.4100,124.1900,97.9700,55.4500,67.6700,38.7600,59.6900,103.0100,59.2300,93.1800

In [43]:
# ex. pSP_CUSIP == 032511107
x = fund_prices[fund_prices["pSP_CUSIP"] == "032511107" ]
joined = pd.merge(x, Etf_df, on = "pSP_DATE")
joined

,pSP_CUSIP,pSP_EXCHANGE,pSP_TICKER,pSP_DATE,pSP_VOLUME,pSP_OPEN,pSP_HIGH,pSP_LOW,pSP_CLOSE,XLF,XLY,XLK,XLB,XLI,XLE,XLU,XLV,XLP,VOX
0,032511107,N,APC,2013-01-02,4314603,75.75,76.08,74.7300,76.06,12.5558,45.5328,27.5843,35.2652,35.6120,66.0461,30.5576,38.1085,32.1762,63.7305
1,032511107,N,APC,2013-01-03,3098703,75.90,77.35,75.1600,76.33,12.5409,45.6456,27.4085,35.0086,35.6303,66.0280,30.5576,38.1554,32.0953,63.7931
2,032511107,N,APC,2013-01-04,3842372,76.59,78.48,76.4618,78.27,12.6897,45.8148,27.2974,35.4393,35.8964,66.7608,30.7123,38.3240,32.1852,64.2132
3,032511107,N,APC,2013-01-07,2744404,77.73,78.93,77.3500,78.25,12.6600,45.7020,27.2604,35.3660,35.7404,66.2451,30.4115,38.4458,31.9695,64.3651
4,032511107,N,APC,2013-01-08,3230932,77.83,78.86,77.2500,78.35,12.6228,45.5704,27.1586,35.4210,35.4652,66.0280,30.3170,38.4552,31.8796,63.3372
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1643,032511107,N,APC,2019-07-16,4231576,73.16,73.22,72.9100,73.06,28.0900,124.3200,80.6500,58.5500,78.5700,63.1800,60.5000,92.1800,59.9900,90.2800
1644,032511107,N,APC,2019-07-17,3686322,73.12,73.28,73.0400,73.14,27.8500,123.1300,80.4400,58.0300,76.8900,62.4600,60.7300,92.2000,59.9200,89.4100
1645,032511107,N,APC,2019-07-18,7253004,73.00,73.15,72.7600,72.97,28.0600,122.9700,81.0400,58.2800,77.0300,62.4700,61.2600,92.7200,60.3200,88.8600
1646,032511107,N,APC,2019-07-19,4304977,72.94,73.54,72.8600,73.38,27.9400,122.1600,80.6900,58.4100,77.4500,62.7600,60.3700,91.7600,59.9400,87.9100
1647,032511107,N,APC,2019-07-22,7904219,73.47,73.64,73.2200,73.64,28.0000,122.2300,81.6200,58.2600,77.5100,63.0500,60.2400,91.5700,59.5900,87.9400

In [44]:
# ex cont.
joined[joined.columns[8:]].corr()

,pSP_CLOSE,XLF,XLY,XLK,XLB,XLI,XLE,XLU,XLV,XLP,VOX
pSP_CLOSE,1.000000,-0.522738,-0.564257,-0.540915,-0.415069,-0.536652,0.870066,-0.670548,-0.599545,-0.707038,-0.456795
XLF,-0.522738,1.000000,0.957353,0.968562,0.956743,0.987761,-0.322593,0.871588,0.924300,0.831548,0.576358
XLY,-0.564257,0.957353,1.000000,0.988434,0.890164,0.967504,-0.408005,0.912336,0.959224,0.866635,0.547458
XLK,-0.540915,0.968562,0.988434,1.000000,0.911858,0.974808,-0.378051,0.906335,0.935704,0.832435,0.509832
XLB,-0.415069,0.956743,0.890164,0.911858,1.000000,0.964602,-0.154173,0.823172,0.881335,0.788593,0.616452
XLI,-0.536652,0.987761,0.967504,0.974808,0.964602,1.000000,-0.309832,0.907745,0.941391,0.866685,0.626164
XLE,0.870066,-0.322593,-0.408005,-0.378051,-0.154173,-0.309832,1.000000,-0.499090,-0.429908,-0.530916,-0.188775
XLU,-0.670548,0.871588,0.912336,0.906335,0.823172,0.907745,-0.499090,1.000000,0.922899,0.951659,0.700065
XLV,-0.599545,0.924300,0.959224,0.935704,0.881335,0.941391,-0.429908,0.922899,1.000000,0.912414,0.604085
XLP,-0.707038,0.831548,0.866635,0.832435,0.788593,0.866685,-0.530916,0.951659,0.912414,1.000000,0.808184
VOX,-0.456795,0.576358,0.547458,0.509832,0.616452,0.626164,-0.188775,0.700065,0.604085,0.808184,1.000000

In [45]:
# ex cont.
joined[joined.columns[8:]].corr()["pSP_CLOSE"][1:]

XLF   -0.522738
XLY   -0.564257
XLK   -0.540915
XLB   -0.415069
XLI   -0.536652
XLE    0.870066
XLU   -0.670548
XLV   -0.599545
XLP   -0.707038
VOX   -0.456795
Name: pSP_CLOSE, dtype: float64

In [46]:
# group fund_prices data by pSP_CUSIP
# for every group, do merge and correlation
# calculate each stock's industry through a correlation script
stock_group = fund_prices.groupby("pSP_CUSIP")
sector_categories = pd.DataFrame(columns = ["iCUSIP", "sector"])
Headings = ["Financial", "Consumer Discretionary", "Technology", "Materials", "Industrial",
            "Energy", "Utilities", "Health Care", "Consumer Staples", "Communications"]

for i in fund_stocks:
    try:
        stock = stock_group.get_group(str(i))
        joined = pd.merge(stock, Etf_df, on = "pSP_DATE")
        sector = joined[joined.columns[8:]].corr()["pSP_CLOSE"][1:]
        sector_index = np.array(sector).argmax()
        sector_categories = sector_categories.append({'iCUSIP': i, 'sector':Headings[sector_index]}, ignore_index = True)
    except KeyError:
        sector_categories = sector_categories.append({'iCUSIP': i, 'sector':'NA'}, ignore_index = True)

In [47]:
sector_categories

          iCUSIP          sector
0      002824100      Technology
1      025816109       Financial
2      026874784  Communications
3      060505104       Financial
4      064058100       Materials
...          ...             ...
20360  15912k001              NA
20361  82900l102              NA
20362  879433845              NA
20363  910331107              NA
20364  74347B276              NA

[20365 rows x 2 columns]

In [48]:
form13f_sector = pd.merge(form13f_1year, sector_categories, on = "iCUSIP")
form13f_sector.sort_values(by=["iPERIOD_END", "iCIK", "sector"], inplace = True, ascending = True)
form13f_sector

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector
289794,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary
424891,39276290,7195,053015103,2013-06-30,2013-08-12,71320.0,4911000.0,0.021364,43 days,Consumer Discretionary
597372,39276293,7195,171232101,2013-06-30,2013-08-12,53980.0,4569000.0,0.019876,43 days,Consumer Discretionary
781996,39276291,7195,075887109,2013-06-30,2013-08-12,47543.0,4699000.0,0.020442,43 days,Consumer Discretionary
821021,39276304,7195,38259P508,2013-06-30,2013-08-12,5809.0,5114000.0,0.022247,43 days,Consumer Discretionary
...,...,...,...,...,...,...,...,...,...,...
1090386,74236106,1776296,464287176,2020-03-31,2020-05-15,3957.0,467000.0,0.004041,45 days,Utilities
1349209,74236153,1776296,30161N101,2020-03-31,2020-05-15,47585.0,1752000.0,0.015161,45 days,Utilities
1422361,74236131,1776296,816851109,2020-03-31,2020-05-15,16899.0,1909000.0,0.016520,45 days,Utilities
1650418,74236148,1776296,46429B655,2020-03-31,2020-05-15,4988.0,243000.0,0.002103,45 days,Utilities
1894086,74236112,1776296,G0450A105,2020-03-31,2020-05-15,12700.0,361000.0,0.003124,45 days,Utilities

### 2. Value & Size Classification (correlation to Value and Size ETFs)

In [49]:
SPY = prices.loc[prices["pSP_TICKER"] == "SPY" ] # 1865
QQQ = prices[(prices["pSP_TICKER"] == "QQQ") & (prices["pSP_CUSIP"] == "46090E103") ] # 1865
IWD = prices.loc[prices["pSP_TICKER"] == "IWD" ] # 1865
IJH = prices.loc[prices["pSP_TICKER"] == "IJH" ] # 1856
IWP = prices.loc[prices["pSP_TICKER"] == "IWP" ] # 1857
IWS = prices.loc[prices["pSP_TICKER"] == "IWS" ] # 1865
IWM = prices.loc[prices["pSP_TICKER"] == "IWM" ] # 1865
IWO = prices.loc[prices["pSP_TICKER"] == "IWO" ] # 1865
VBR = prices.loc[prices["pSP_TICKER"] == "VBR" ] # 1865

In [59]:
SPY = SPY[SPY["pSP_DATE"].isin(IJH["pSP_DATE"])]
QQQ = QQQ[QQQ["pSP_DATE"].isin(IJH["pSP_DATE"])]
IWD = IWD[IWD["pSP_DATE"].isin(IJH["pSP_DATE"])]
IWP = IWP[IWP["pSP_DATE"].isin(IJH["pSP_DATE"])]
IWS = IWS[IWS["pSP_DATE"].isin(IJH["pSP_DATE"])]
IWM = IWM[IWM["pSP_DATE"].isin(IJH["pSP_DATE"])]
IWO = IWO[IWO["pSP_DATE"].isin(IJH["pSP_DATE"])]
VBR = VBR[VBR["pSP_DATE"].isin(IJH["pSP_DATE"])]

In [68]:
Etf_data2 = {'pSP_DATE':SPY["pSP_DATE"].values,
             'SPY':SPY["pSP_CLOSE"].values,
             'QQQ':QQQ["pSP_CLOSE"].values,
             'IWD':IWD["pSP_CLOSE"].values,
             'IJH':IJH["pSP_CLOSE"].values,
             'IWP':IWP["pSP_CLOSE"].values,
             'IWS':IWS["pSP_CLOSE"].values,
             'IWM':IWM["pSP_CLOSE"].values,
             'IWO':IWO["pSP_CLOSE"].values,
             'VBR':VBR["pSP_CLOSE"].values}

Etf_df2 = pd.DataFrame(Etf_data2)
Etf_df2

,pSP_DATE,SPY,QQQ,IWD,IJH,IWP,IWS,IWM,IWO,VBR
0,2013-01-02,146.060,67.2000,67.8392,98.2093,61.8643,47.2322,81.8058,94.5759,69.0195
1,2013-01-03,145.734,66.8521,67.7392,98.2469,61.8547,47.2689,81.6173,94.5373,69.1488
2,2013-01-04,146.370,66.6300,68.2575,98.9322,62.2392,47.6732,82.2205,95.0677,69.6291
3,2013-01-07,145.969,66.6504,67.9574,98.6787,62.0662,47.4802,81.9094,94.9905,69.3058
4,2013-01-08,145.550,66.5200,67.7483,98.3971,61.9220,47.2322,81.8529,94.9713,69.1118
...,...,...,...,...,...,...,...,...,...,...
1851,2020-05-22,295.440,229.6600,109.2700,169.3000,149.3900,72.4200,134.8900,195.8700,100.8700
1852,2020-05-26,299.080,229.0400,112.3100,175.1900,150.8400,75.1100,138.7800,199.4600,105.1500
1853,2020-05-27,303.530,230.2900,114.8900,179.8700,152.5600,76.9900,143.0900,204.1300,108.7800
1854,2020-05-28,302.970,229.9900,114.2600,177.2100,152.8100,76.2800,139.7000,199.8100,106.4700
1855,2020-05-29,304.320,233.3600,114.1200,176.1200,154.6200,76.0400,138.9000,199.3900,105.2600

In [69]:
stock_group = fund_prices.groupby("pSP_CUSIP")
value_size_categories = pd.DataFrame(columns = ["iCUSIP", "value_size"])
Headings = ["Large-Cap Blend", "Large-Cap Growth", "Large-Cap Value", "MidCap Blend", "MidCap Growth",
            "MidCap Value", "Small-Cap Blend", "Small-Cap Growth", "Small-Cap Value"]

for i in fund_stocks:
    try:
        stock = stock_group.get_group(str(i))
        joined = pd.merge(stock, Etf_df2, on = "pSP_DATE")
        sector = joined[joined.columns[8:]].corr()["pSP_CLOSE"][1:]
        sector_index = np.array(sector).argmax()
        value_size_categories = value_size_categories.append({'iCUSIP': i, 'value_size':Headings[sector_index]}, ignore_index = True)
    except KeyError:
        value_size_categories = value_size_categories.append({'iCUSIP': i, 'value_size':'NA'}, ignore_index = True)

In [70]:
value_size_categories

          iCUSIP       value_size
0      002824100    MidCap Growth
1      025816109    MidCap Growth
2      026874784  Small-Cap Value
3      060505104  Small-Cap Blend
4      064058100  Small-Cap Value
...          ...              ...
20360  15912k001               NA
20361  82900l102               NA
20362  879433845               NA
20363  910331107               NA
20364  74347B276               NA

[20365 rows x 2 columns]

In [71]:
form13f_value_size = pd.merge(form13f_sector, value_size_categories, on = "iCUSIP")
form13f_value_size.sort_values(by=["iPERIOD_END", "iCIK", "sector", "value_size"], inplace = True, ascending = True)
form13f_value_size

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size
17415,39276291,7195,075887109,2013-06-30,2013-08-12,47543.0,4699000.0,0.020442,43 days,Consumer Discretionary,Large-Cap Blend
35486,39276326,7195,863667101,2013-06-30,2013-08-12,65418.0,4231000.0,0.018406,43 days,Consumer Discretionary,Large-Cap Blend
0,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth
16248,39276293,7195,171232101,2013-06-30,2013-08-12,53980.0,4569000.0,0.019876,43 days,Consumer Discretionary,Large-Cap Growth
10510,39276290,7195,053015103,2013-06-30,2013-08-12,71320.0,4911000.0,0.021364,43 days,Consumer Discretionary,MidCap Growth
...,...,...,...,...,...,...,...,...,...,...,...
1871285,74236112,1776296,G0450A105,2020-03-31,2020-05-15,12700.0,361000.0,0.003124,45 days,Utilities,Large-Cap Value
340589,74236101,1776296,742718109,2020-03-31,2020-05-15,30211.0,3323000.0,0.028757,45 days,Utilities,MidCap Growth
382499,74236116,1776296,58933Y105,2020-03-31,2020-05-15,4279.0,329000.0,0.002847,45 days,Utilities,MidCap Growth
982100,74236153,1776296,30161N101,2020-03-31,2020-05-15,47585.0,1752000.0,0.015161,45 days,Utilities,MidCap Growth
1562744,74236131,1776296,816851109,2020-03-31,2020-05-15,16899.0,1909000.0,0.016520,45 days,Utilities,MidCap Growth

In [72]:
###### change the years!!!!!!

### 3. Performance (mean of funds' return as benchmark)

In [73]:
# closing price on filing date
form13f_close = pd.merge(form13f_value_size, fund_prices[["pSP_CLOSE","pSP_CUSIP","pSP_DATE"]],  how='left', left_on=["iCUSIP","iFILING_DATE"], right_on = ["pSP_CUSIP","pSP_DATE"])
form13f_close = form13f_close.iloc[:,:-2]
form13f_close

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE
0,39276291,7195,075887109,2013-06-30,2013-08-12,47543.0,4699000.0,0.020442,43 days,Consumer Discretionary,Large-Cap Blend,100.0000
1,39276326,7195,863667101,2013-06-30,2013-08-12,65418.0,4231000.0,0.018406,43 days,Consumer Discretionary,Large-Cap Blend,70.7600
2,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000
3,39276293,7195,171232101,2013-06-30,2013-08-12,53980.0,4569000.0,0.019876,43 days,Consumer Discretionary,Large-Cap Growth,85.5200
4,39276290,7195,053015103,2013-06-30,2013-08-12,71320.0,4911000.0,0.021364,43 days,Consumer Discretionary,MidCap Growth,63.9936
...,...,...,...,...,...,...,...,...,...,...,...,...
2326339,74236112,1776296,G0450A105,2020-03-31,2020-05-15,12700.0,361000.0,0.003124,45 days,Utilities,Large-Cap Value,22.9800
2326340,74236101,1776296,742718109,2020-03-31,2020-05-15,30211.0,3323000.0,0.028757,45 days,Utilities,MidCap Growth,114.6100
2326341,74236116,1776296,58933Y105,2020-03-31,2020-05-15,4279.0,329000.0,0.002847,45 days,Utilities,MidCap Growth,79.7800
2326342,74236153,1776296,30161N101,2020-03-31,2020-05-15,47585.0,1752000.0,0.015161,45 days,Utilities,MidCap Growth,35.2900
2326343,74236131,1776296,816851109,2020-03-31,2020-05-15,16899.0,1909000.0,0.016520,45 days,Utilities,MidCap Growth,119.2000

In [74]:
form13f_close["shares"] = form13f_close["iMARKET_VALUE"] / form13f_close["pSP_CLOSE"]
form13f_close

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE,shares
0,39276291,7195,075887109,2013-06-30,2013-08-12,47543.0,4699000.0,0.020442,43 days,Consumer Discretionary,Large-Cap Blend,100.0000,46990.000000
1,39276326,7195,863667101,2013-06-30,2013-08-12,65418.0,4231000.0,0.018406,43 days,Consumer Discretionary,Large-Cap Blend,70.7600,59793.668739
2,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000,62664.141414
3,39276293,7195,171232101,2013-06-30,2013-08-12,53980.0,4569000.0,0.019876,43 days,Consumer Discretionary,Large-Cap Growth,85.5200,53426.099158
4,39276290,7195,053015103,2013-06-30,2013-08-12,71320.0,4911000.0,0.021364,43 days,Consumer Discretionary,MidCap Growth,63.9936,76742.049205
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326339,74236112,1776296,G0450A105,2020-03-31,2020-05-15,12700.0,361000.0,0.003124,45 days,Utilities,Large-Cap Value,22.9800,15709.312446
2326340,74236101,1776296,742718109,2020-03-31,2020-05-15,30211.0,3323000.0,0.028757,45 days,Utilities,MidCap Growth,114.6100,28993.979583
2326341,74236116,1776296,58933Y105,2020-03-31,2020-05-15,4279.0,329000.0,0.002847,45 days,Utilities,MidCap Growth,79.7800,4123.840562
2326342,74236153,1776296,30161N101,2020-03-31,2020-05-15,47585.0,1752000.0,0.015161,45 days,Utilities,MidCap Growth,35.2900,49645.792009
2326343,74236131,1776296,816851109,2020-03-31,2020-05-15,16899.0,1909000.0,0.016520,45 days,Utilities,MidCap Growth,119.2000,16015.100671

In [96]:
form13f_close["FILING_INTERVAL"].astype('timedelta64[D]').mean() # mean filing interval

32.7729377082667

In [112]:
# assume filing interval is 32 days
# filing_3mos: previous filing date
# funds report完换股票
form13f_close["filing_3mos"] = form13f_close["iPERIOD_END"] - relativedelta(days=+60) # 31+30+31(previous period)-32(filing interval)
form13f_close

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE,shares,filing_3mos
0,39276291,7195,075887109,2013-06-30,2013-08-12,47543.0,4699000.0,0.020442,43 days,Consumer Discretionary,Large-Cap Blend,100.0000,46990.000000,2013-05-01
1,39276326,7195,863667101,2013-06-30,2013-08-12,65418.0,4231000.0,0.018406,43 days,Consumer Discretionary,Large-Cap Blend,70.7600,59793.668739,2013-05-01
2,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000,62664.141414,2013-05-01
3,39276293,7195,171232101,2013-06-30,2013-08-12,53980.0,4569000.0,0.019876,43 days,Consumer Discretionary,Large-Cap Growth,85.5200,53426.099158,2013-05-01
4,39276290,7195,053015103,2013-06-30,2013-08-12,71320.0,4911000.0,0.021364,43 days,Consumer Discretionary,MidCap Growth,63.9936,76742.049205,2013-05-01
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326339,74236112,1776296,G0450A105,2020-03-31,2020-05-15,12700.0,361000.0,0.003124,45 days,Utilities,Large-Cap Value,22.9800,15709.312446,2020-01-31
2326340,74236101,1776296,742718109,2020-03-31,2020-05-15,30211.0,3323000.0,0.028757,45 days,Utilities,MidCap Growth,114.6100,28993.979583,2020-01-31
2326341,74236116,1776296,58933Y105,2020-03-31,2020-05-15,4279.0,329000.0,0.002847,45 days,Utilities,MidCap Growth,79.7800,4123.840562,2020-01-31
2326342,74236153,1776296,30161N101,2020-03-31,2020-05-15,47585.0,1752000.0,0.015161,45 days,Utilities,MidCap Growth,35.2900,49645.792009,2020-01-31
2326343,74236131,1776296,816851109,2020-03-31,2020-05-15,16899.0,1909000.0,0.016520,45 days,Utilities,MidCap Growth,119.2000,16015.100671,2020-01-31

In [113]:
# closing price 2 months before period end
form13f_3mos = pd.merge(form13f_close, fund_prices[["pSP_CLOSE","pSP_CUSIP","pSP_DATE"]],  how='left', left_on=["iCUSIP","filing_3mos"], right_on = ["pSP_CUSIP","pSP_DATE"])
form13f_3mos = form13f_3mos.iloc[:,:-2]
form13f_3mos

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y
0,39276291,7195,075887109,2013-06-30,2013-08-12,47543.0,4699000.0,0.020442,43 days,Consumer Discretionary,Large-Cap Blend,100.0000,46990.000000,2013-05-01,93.5800
1,39276326,7195,863667101,2013-06-30,2013-08-12,65418.0,4231000.0,0.018406,43 days,Consumer Discretionary,Large-Cap Blend,70.7600,59793.668739,2013-05-01,65.3000
2,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000,62664.141414,2013-05-01,72.7600
3,39276293,7195,171232101,2013-06-30,2013-08-12,53980.0,4569000.0,0.019876,43 days,Consumer Discretionary,Large-Cap Growth,85.5200,53426.099158,2013-05-01,87.3000
4,39276290,7195,053015103,2013-06-30,2013-08-12,71320.0,4911000.0,0.021364,43 days,Consumer Discretionary,MidCap Growth,63.9936,76742.049205,2013-05-01,58.7369
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326339,74236112,1776296,G0450A105,2020-03-31,2020-05-15,12700.0,361000.0,0.003124,45 days,Utilities,Large-Cap Value,22.9800,15709.312446,2020-01-31,44.1600
2326340,74236101,1776296,742718109,2020-03-31,2020-05-15,30211.0,3323000.0,0.028757,45 days,Utilities,MidCap Growth,114.6100,28993.979583,2020-01-31,124.6200
2326341,74236116,1776296,58933Y105,2020-03-31,2020-05-15,4279.0,329000.0,0.002847,45 days,Utilities,MidCap Growth,79.7800,4123.840562,2020-01-31,85.4400
2326342,74236153,1776296,30161N101,2020-03-31,2020-05-15,47585.0,1752000.0,0.015161,45 days,Utilities,MidCap Growth,35.2900,49645.792009,2020-01-31,47.5900
2326343,74236131,1776296,816851109,2020-03-31,2020-05-15,16899.0,1909000.0,0.016520,45 days,Utilities,MidCap Growth,119.2000,16015.100671,2020-01-31,160.6400

In [114]:
# check nontrading date
p_date = fund_prices["pSP_DATE"].unique()
f_date = form13f_3mos[~form13f_3mos["filing_3mos"].isin(p_date)]["filing_3mos"].unique()
print(len(p_date))
print(len(f_date))
f_date

1899
5

array([datetime.date(2014, 11, 1), datetime.date(2015, 8, 1),
       datetime.date(2015, 11, 1), datetime.date(2016, 1, 31),
       datetime.date(2016, 5, 1)], dtype=object)

In [115]:
# check (so many) NaN
print(len(form13f_3mos[(form13f_3mos["pSP_CLOSE_y"].isna())]["iCIK"].unique()))
for i in form13f_3mos[(form13f_3mos["pSP_CLOSE_y"].isna())]["iCIK"].unique():
    f = form13f_3mos[(form13f_3mos["pSP_CLOSE_y"].isna()) & (form13f_3mos["iCIK"] == i) & (form13f_3mos["iPERIOD_END"] == datetime.date(2013,6,30))]
    print(i, len(f["iCUSIP"].unique()))

2251
18748 3
21175 5
65957 2
80835 1
84616 1
86312 1
101199 5
102212 2
312955 11
320376 23
712011 1
764112 1
774602 1
778963 28
779519 3
806097 12
809339 14
810672 20
810716 7
811360 1
811454 1
819535 1
846788 2
860189 1
860580 7
860645 10
860748 2
862853 20
866780 4
866995 1
868911 17
869367 9
872078 7
874791 5
878228 10
883790 12
884306 2
884310 12
884548 3
886920 18
894205 3
894300 1
898399 1
900169 8
900529 5
902614 6
903064 18
911270 6
918504 14
919497 11
919530 2
920441 7
923469 1
924166 9
926833 2
928204 5
928400 6
931328 1
932141 37
934745 17
937886 3
938506 2
938759 13
939791 5
939835 12
941560 5
943442 7
943712 5
945625 15
948985 15
1002152 14
1003279 5
1004744 1
1006435 1
1008877 4
1008895 34
1009950 1
1013234 4
1013701 5
1014306 2
1014315 3
1016150 1
1016683 17
1016972 6
1017115 5
1019231 2
1021117 32
1026303 1
1027799 2
1031972 7
1033974 2
1034012 1
1034188 27
1035912 12
1037558 7
1038661 29
1041241 1
1042063 6
1044924 2
1044929 17
1047339 15
1049648 3
1049650 40
1050417 3
1050463 22
1051042 5
1052174 1
1054233 8
1054425 1
1055544 14
1055954 3
1055963 40
1056516 41
1056519 4
1056821 10
1056827 1
1056868 11
1056958 7
1057395 48
1058949 5
1061187 5
1067532 21
1068840 2
1072843 1
1074027 27
1074273 5
1076964 1
1077148 24
1078246 3
1078635 13
1078841 2
1079373 2
1079397 1
1079738 10
1079930 3
1079935 3
1080071 3
1080132 9
1080166 34
1080173 1
1080197 6
1080201 1
1080351 9
1080523 24
1082339 24
1082482 8
1082491 62
1084207 2
1085163 2
1085227 4
1088731 17
1088859 4
1091961 7
1092290 39
1093276 1
1098062 2
1100916 94
1104366 9
1105344 9
1105468 7
1105471 3
1105871 1
1106505 17
1106544 1
1107211 7
1108893 3
1108965 3
1113303 1
1114702 1
1115373 2
1119254 30
1119376 1
1121477 136
1121908 14
1123320 2
1123798 5
1123812 8
1124841 6
1125727 7
1126735 2
1127544 25
1128213 4
1129770 3
1132356 34
1132556 1
1132708 15
1133653 76
1136704 3
1138486 42
1140468 5
1141455 2
1158583 3
1160099 1
1161822 7
1161825 3
1162781 4
1162827 46
1163902 1
1164062 37
1165805 6
1166308 1
1166385 12
1166402 9
1166620 11
1166716 42
1166741 7
1167026 7
1168889 3
1172779 11
1172799 22
1177018 10
1177043 7
1177132 4
1185072 2
1212225 1
1213206 5
1213310 1
1217675 1
1218179 4
1218254 5
1218555 3
1219062 4
1224014 14
1224890 3
1226779 3
1252007 17
1255435 23
1259671 5
1260468 10
1262677 16
1269786 9
1269950 6
1275124 2
1276525 1
1276853 6
1277158 5
1277537 5
1277779 3
1278641 2
1279708 13
1280051 61
1280577 5
1280604 1
1281011 18
1284208 2
1298596 1
1301540 1
1307203 4
1308001 2
1308523 9
1308778 16
1309148 1
1313978 5
1314404 9
1315269 1
1315889 26
1316393 1
1316729 1
1317103 4
1317209 32
1317346 18
1317410 1
1317733 19
1317802 17
1317829 22
1318259 1
1321194 3
1321219 19
1321993 6
1322924 11
1324022 2
1326766 6
1330463 8
1335851 3
1336098 31
1336800 1
1339270 38
1346378 1
1349353 1
1350290 2
1350312 1
1350780 8
1351407 1
1351841 4
1352122 1
1352306 41
1352449 9
1352776 17
1352860 6
1352871 1
1352900 1
1353318 1
1354739 1
1356202 3
1356407 10
1358828 53
1360505 3
1360798 10
1364725 22
1365707 29
1366838 19
1367663 55
1370629 3
1372130 21
1375664 4
1377817 1
1377929 2
1379119 14
1380137 6
1381296 24
1382303 11
1384484 2
1384943 2
1385011 1
1387130 14
1387304 2
1387458 6
1387615 3
1387818 1
1388279 3
1388409 6
1388437 16
1388838 16
1389082 1
1389256 8
1390003 3
1390043 1
1390063 3
1390205 2
1392364 36
1392910 1
1395055 1
1397290 1
1404652 2
1406484 4
1410833 2
1416856 11
1418359 2
1419027 3
1419099 4
1420473 2
1420816 10
1421594 7
1422508 12
1423045 2
1423065 14
1424196 1
1424322 4
1424467 1
1424480 3
1425041 1
1425949 3
1426588 21
1426754 6
1426771 1
1427147 2
1427684 3
1428350 5
1428601 3
1429788 1
1430681 2
1434323 4
1434689 9
1434845 9
1442173 6
1443095 17
1445891 8
1450008 1
1450558 28
1453102 2
1453155 2
1453526 3
1453819 6
1454424 3
1455176 5
1455251 24
1455452 1
1455495 12
1455924 7
1459754 3
1461287 47
1462525 4
1464586 4
1467888 1
1468685 4
1469219 6
1469528 13
1475150 1
1476804 3
1481714 1
1482010 149
1482012 1
1482106 2
1482390 3
1482688 5
1482880 12
1482935 4
1482970 14
1483060 1
1483065 190
1483170 13
1483467 1
1483796 15
1483824 2
1483969 1
1484085 1
1486946 2
1490429 1
1492162 7
1497637 14
1503269 1
1504941 5
1505961 2
1506073 17
1507971 9
1508120 16
1509508 19
1509873 7
1509973 5
1509974 1
1510201 1
1510809 1
1510848 2
1511144 1
1511291 2
1511465 9
1511550 3
1511794 1
1511888 4
1511915 1
1511985 1
1512024 3
1512251 20
1512545 7
1512601 2
1512652 1
1512808 1
1512814 3
1512865 6
1512914 4
1512920 3
1512978 2
1513122 1
1513125 1
1513211 27
1513865 1
1515072 6
1518364 1
1529832 1
1532262 1
1532618 5
1533321 1
1533954 2
1534417 2
1534561 8
1535315 8
1535477 1
1535610 2
1535679 1
1536114 1
1536430 1
1536924 3
1537558 2
1537703 28
1539338 4
1539948 2
1540569 1
1540944 2
1541399 13
1541496 2
1541596 1
1542108 4
1542143 1
1542162 3
1542165 2
1542287 3
1542300 11
1544744 2
1544806 1
1545812 2
1546283 2
1546967 3
1548882 3
1550228 7
1551969 2
1552426 7
1553656 6
1555170 1
1556915 1
1556970 17
1557513 3
1557664 4
1559538 2
1559968 2
1559972 3
1561790 1
1563690 21
1565061 1
1566887 3
1567195 1
1567634 1
1567890 3
1567912 4
1567993 16
1568298 1
1568540 9
1568542 1
1568787 1
1568894 1
1568939 2
1569067 3
1569071 6
1569099 1
1569102 2
1569117 32
1569119 6
1569147 5
1569148 2
1569174 8
1569175 3
1569453 1
1569606 2
1569656 1
1569667 36
1569688 3
1569766 18
1571556 1
1573485 4
1573767 2
1576707 9
1577001 36
1577920 1
1583092 11
791191 0
825161 0
831457 0
860176 0
883803 0
884300 0
887402 0
909450 0
911274 0
918893 0
933141 0
936936 0
1002672 0
1009259 0
1020580 0
1043853 0
1053054 0
1055290 0
1074266 0
1080493 0
1089710 0
1096783 0
1096978 0
1102256 0
1105863 0
1105876 0
1105907 0
1112179 0
1122241 0
1125725 0
1132699 0
1133219 0
1134288 0
1135307 0
1166988 0
1167167 0
1169318 0
1232960 0
1251567 0
1259261 0
1269134 0
1275880 0
1276755 0
1278793 0
1278951 0
1280200 0
1280493 0
1281446 0
1282189 0
1287618 0
1301743 0
1304762 0
1308377 0
1317784 0
1322590 0
1323510 0
1324659 0
1332811 0
1334952 0
1347104 0
1349654 0
1352859 0
1357372 0
1374998 0
1379995 0
1381859 0
1382646 0
1385080 0
1387723 0
1387814 0
1388076 0
1388142 0
1388168 0
1388382 0
1389223 0
1389974 0
1404574 0
1405555 0
1418421 0
1419345 0
1423296 0
1423876 0
1426665 0
1427263 0
1455288 0
1455969 0
1476179 0
1476961 0
1480535 0
1481447 0
1482171 0
1483535 0
1484205 0
1499882 0
1505207 0
1507758 0
1508195 0
1509550 0
1510434 0
1512026 0
1512145 0
1512746 0
1512858 0
1518320 0
1519319 0
1519676 0
1525865 0
1534259 0
1535227 0
1538037 0
1539919 0
1541353 0
1541536 0
1541597 0
1541787 0
1542166 0
1542179 0
1542324 0
1542421 0
1549358 0
1552999 0
1554815 0
1564579 0
1566414 0
1566493 0
1566494 0
1568049 0
1568289 0
1568555 0
1569137 0
1569519 0
1569650 0
1569833 0
1571042 0
1579254 0
1582813 0
1584801 0
1590073 0
1590491 0
1590784 0
1591379 0
1591625 0
1591925 0
7195 0
36066 0
51812 0
712050 0
790354 0
846633 0
860862 0
869179 0
905608 0
923116 0
939761 0
942618 0
944361 0
945444 0
1000490 0
1008868 0
1008937 0
1016021 0
1027451 0
1047859 0
1053013 0
1056488 0
1058854 0
1080381 0
1095836 0
1097833 0
1101250 0
1104186 0
1105838 0
1114739 0
1115055 0
1116247 0
1123274 0
1140331 0
1140474 0
1141911 0
1167212 0
1167348 0
1181544 0
1278178 0
1279097 0
1313871 0
1318055 0
1327944 0
1353110 0
1353311 0
1357975 0
1362987 0
1378559 0
1388028 0
1390271 0
1394866 0
1399706 0
1406585 0
1408103 0
1411512 0
1425649 0
1425963 0
1426266 0
1426940 0
1427351 0
1430308 0
1431518 0
1432539 0
1434981 0
1439743 0
1455267 0
1463698 0
1463753 0
1473429 0
1478417 0
1478775 0
1481986 0
1483472 0
1484067 0
1484256 0
1484540 0
1485921 0
1486180 0
1496201 0
1510475 0
1511172 0
1511229 0
1517429 0
1520770 0
1531064 0
1534843 0
1535106 0
1535631 0
1536078 0
1536444 0
1537335 0
1537621 0
1539947 0
1542317 0
1542943 0
1544825 0
1548468 0
1548836 0
1556245 0
1557485 0
1562668 0
1564721 0
1566113 0
1567397 0
1567889 0
1568280 0
1568303 0
1568389 0
1569141 0
1569638 0
1569853 0
1570296 0
1570396 0
1570598 0
1574661 0
1574758 0
1574886 0
1575581 0
1575766 0
1576102 0
1577773 0
1581298 0
1581465 0
1582635 0
1583977 0
1585047 0
1586986 0
1587643 0
1587836 0
1590569 0
1592405 0
1593410 0
1593688 0
1594492 0
1595852 0
1595853 0
1596077 0
1596355 0
1596901 0
1596906 0

1596920 0
1596957 0
1597099 0
1597200 0
1597549 0
1598011 0
1598013 0
1598147 0
1598177 0
1598180 0
1598245 0
1598348 0
1598352 0
1598550 0
1598803 0
1599054 0
1599210 0
1599212 0
1599217 0
1599390 0
1599425 0
1599444 0
1599466 0
1599468 0
1599562 0
1599579 0
1599623 0
1599731 0
1599746 0
1599747 0
1599813 0
1599863 0
1600004 0
1600085 0
1600136 0
1600145 0
200724 0
357301 0
740918 0
752365 0
813470 0
910886 0
1068809 0
1084683 0
1091923 0
1092838 0
1106590 0
1119032 0
1133385 0
1166134 0
1169581 0
1260824 0
1280054 0
1308555 0
1315828 0
1351063 0
1353198 0
1353570 0
1387869 0
1389403 0
1407382 0
1453885 0
1456511 0
1483394 0
1485153 0
1500605 0
1506294 0
1510940 0
1512901 0
1513193 0
1525109 0
1527570 0
1531611 0
1533327 0
1536725 0
1543991 0
1555283 0
1555900 0
1569036 0
1569292 0
1570251 0
1576151 0
1580830 0
1581655 0
1582968 0
1584086 0
1584087 0
1584246 0
1585045 0
1585740 0
1593921 0
1595124 0
1595509 0
1595855 0
1597245 0
1597823 0
1598340 0
1598381 0
1599760 0
1599793 0
1599882 0
1600035 0
1600151 0
1600583 0
1600746 0
1600999 0
1601742 0
1601904 0
1602198 0
1602476 0
1603001 0
1603142 0
1603937 0
1606588 0
1607231 0
1607636 0
1608057 0
1608179 0
59470 0
882119 0
883948 0
919086 0
928566 0
1026081 0
1053911 0
1053914 0
1066816 0
1103245 0
1160841 0
1215208 0
1272544 0
1314273 0
1314376 0
1314377 0
1315059 0
1317208 0
1339908 0
1342396 0
1347683 0
1352675 0
1379495 0
1381055 0
1386714 0
1387366 0
1388443 0
1389234 0
1389307 0
1391974 0
1426755 0
1426967 0
1427372 0
1441646 0
1463970 0
1482339 0
1494234 0
1510668 0
1511098 0
1534646 0
1535061 0
1535249 0
1536442 0
1543100 0
1546592 0
1556168 0
1561509 0
1563223 0
1565432 0
1576002 0
1579111 0
1584639 0
1589282 0
1589358 0
1591546 0
1591590 0
1592615 0
1592616 0
1593404 0
1595851 0
1596076 0
1598244 0
1598304 0
1599084 0
1599170 0
1599900 0
1605522 0
1607278 0
1607866 0
1608376 0
1611519 0
1614704 0
1615424 0
1616328 0
19481 0
108572 0
314169 0
810386 0
949853 0
1009005 0
1010452 0
1022314 0
1075699 0
1108969 0
1119191 0
1120927 0
1123803 0
1140315 0
1166573 0
1167487 0
1315339 0
1340614 0
1350660 0
1357867 0
1381954 0
1387921 0
1387978 0
1387980 0
1395067 0
1424878 0
1450935 0
1451643 0
1455289 0
1455290 0
1478997 0
1483801 0
1511037 0
1512022 0
1513013 0
1532516 0
1546408 0
1550660 0
1568235 0
1568891 0
1569454 0
1569709 0
1571207 0
1578964 0
1583119 0
1587192 0
1590721 0
1596055 0
1598898 0
1599469 0
1599576 0
1599814 0
1599852 0
1600585 0
1600636 0
1606810 0
1616664 0
1624723 0
19475 0
320335 0
708848 0
711089 0
712534 0
714364 0
810958 0
849854 0
867926 0
883511 0
893738 0
927952 0
1009022 0
1014738 0
1028874 0
1044936 0
1071640 0
1089707 0
1092688 0
1125243 0
1131908 0
1140753 0
1141800 0
1143892 0
1169347 0
1172036 0
1201001 0
1214183 0
1276151 0
1285973 0
1309342 0
1316397 0
1333792 0
1359371 0
1368905 0
1369913 0
1376772 0
1393369 0
1409661 0
1411268 0
1423875 0
1426774 0
1426857 0
1427261 0
1428242 0
1475271 0
1479355 0
1484265 0
1484721 0
1492040 0
1493936 0
1495703 0
1505791 0
1511739 0
1512404 0
1512944 0
1518934 0
1521951 0
1523609 0
1527641 0
1528147 0
1535578 0
1535862 0
1536799 0
1537996 0
1540425 0
1540945 0
1541666 0
1542164 0
1549738 0
1550188 0
1550191 0
1554656 0
1559832 0
1566968 0
1568219 0
1569100 0
1576422 0
1576762 0
1580212 0
1581641 0
1583104 0
1585550 0
1586444 0
1588225 0
1591122 0
1591271 0
1591377 0
1592162 0
1594585 0
1595077 0
1595849 0
1596053 0
1596452 0
1597089 0
1597298 0
1597691 0
1597843 0
1597864 0
1598102 0
1598379 0
1598611 0
1599273 0
1599275 0
1599670 0
1599923 0
1603470 0
1604723 0
1605826 0
1609674 0
1611518 0
1611848 0
1613331 0
1613634 0
1615135 0
1615359 0
1615963 0
1616004 0
1618824 0
1619724 0
1620081 0
1620916 0
1624809 0
1625246 0
1625986 0
1626494 0
1631052 0
1631084 0
1631353 0
1631408 0
1631639 0
1631665 0
1631738 0
1631864 0
1631930 0
1631941 0
1632078 0
1632105 0
1632248 0
1632560 0
1632665 0
1632801 0
1632966 0
1632972 0
1633024 0
1633172 0
1633343 0
1633362 0
1633448 0
1633624 0
1633716 0
732847 0
919538 0
1009003 0
1034550 0
1058022 0
1070265 0
1128286 0
1138996 0
1139986 0
1143261 0
1291424 0
1299434 0
1316466 0
1326918 0
1350879 0
1386935 0
1423673 0
1461790 0
1471474 0
1499266 0
1510912 0
1512135 0
1531987 0
1535630 0
1540142 0
1542284 0
1552981 0
1572748 0
1579853 0
1580162 0
1580572 0
1590144 0
1600307 0
1600327 0
1601086 0
1601539 0
1602603 0
1606507 0
1609251 0
1616584 0
1617516 0
1619390 0
1622820 0
1624729 0
1626691 0
1627608 0
1628896 0
1630365 0
1631507 0
1632096 0
1632108 0
1632118 0
1632512 0
1632802 0
1632866 0
1633207 0
1633275 0
1633387 0
1633517 0
1633648 0
1633695 0
1633862 0
1633910 0
1634083 0
1634155 0
1634208 0
1634212 0
1634222 0
1637246 0
1637541 0
1638049 0
1641864 0
1642570 0
1023279 0
1081668 0
1086416 0
1127761 0
1307748 0
1387303 0
1389709 0
1415201 0
1438258 0
1467902 0
1475597 0
1482611 0
1484368 0
1491072 0
1510870 0
1541901 0
1542383 0
1558313 0
1569765 0
1582844 0
1600133 0
1600581 0
1602987 0
1605070 0
1624510 0
1633055 0
1633313 0
1633861 0
1634865 0
1638555 0
1640335 0
1642216 0
1642246 0
1645382 0
1645890 0
1649776 0
1650654 0
61227 0
733020 0
902528 0
917579 0
938077 0
938487 0
1009012 0
1020317 0
1030618 0
1036250 0
1044330 0
1056581 0
1059543 0
1080382 0
1108829 0
1114039 0
1166152 0
1179232 0
1230869 0
1251557 0
1277279 0
1288125 0
1313473 0
1315497 0
1322853 0
1331875 0
1334199 0
1349352 0
1353098 0
1357550 0
1378410 0
1384982 0
1385925 0
1390457 0
1394096 0
1397076 0
1409765 0
1417889 0
1425419 0
1435346 0
1442573 0
1443077 0
1476329 0
1482416 0
1483532 0
1491998 0
1535264 0
1541211 0
1541349 0
1544676 0
1561784 0
1566728 0
1567738 0
1569356 0
1569532 0
1574408 0
1581793 0
1585828 0
1585859 0
1599016 0
1600403 0
1606716 0
1632097 0
1633227 0
1635342 0
1635523 0
1639753 0
1639754 0
1641438 0
1642351 0
1648101 0
1648901 0
1649888 0
1653866 0
710127 0
764611 0
894309 0
903514 0
911088 0
914933 0
1002912 0
1014358 0
1081198 0
1184820 0
1266014 0
1286295 0
1289851 0
1358331 0
1389400 0
1389933 0
1473438 0
1475373 0
1512367 0
1529389 0
1534261 0
1535172 0
1536063 0
1536630 0
1537319 0
1551867 0
1555486 0
1567992 0
1568890 0
1569863 0
1584691 0
1598841 0
1599749 0
1604903 0
1618205 0
1623707 0
1626757 0
1630409 0
1632098 0
1632283 0
1632368 0
1633516 0
1633570 0
1634553 0
1639668 0
1641042 0
1641391 0
1650092 0
1651960 0
1653199 0
1653202 0
1653253 0
1654599 0
1654847 0
1655543 0
1657428 0
1659420 0
1659997 0
1660071 0
1660086 0
1661144 0
1661163 0
1661222 0
1663138 0
1663649 0
1663896 0
1664771 0
1665445 0
1665446 0
1665642 0
1666256 0
1666363 0
1666470 0
1666736 0
1666746 0
754811 0
767684 0
805867 0
842766 0
844150 0
859139 0
896159 0
1050068 0
1174850 0
1272164 0
1279030 0
1286534 0
1326638 0
1330325 0
1431256 0
1451428 0
1504304 0
1512162 0
1531593 0
1536080 0
1544341 0
1575151 0
1576053 0
1576497 0
1589661 0
1602263 0
1608062 0
1622431 0
1625800 0
1629680 0
1630939 0
1631208 0
1632929 0
1645157 0
1649147 0
1654710 0
1655095 0
1658535 0
1659346 0
1660203 0
1661149 0
1664214 0
1665199 0
1665302 0
1665359 0
1666786 0
1666788 0
1667694 0
1668155 0
1668256 0
1669733 0
1670053 0
1670903 0
1672070 0
1673815 0
1673907 0
1673922 0
936941 0
1010232 0
1054880 0
1286478 0
1313893 0
1387761 0
1468395 0
1511137 0
1549042 0
1592613 0
1618832 0
1618872 0
1632407 0
1640638 0
1641440 0
1641643 0
1649107 0
1653168 0
1663224 0
1664147 0
1664385 0
1664772 0
1666239 0
1666738 0
1667019 0
1667074 0
1667102 0
1667140 0
1667164 0
1668189 0
1673633 0
1679118 0
1679807 0
1053994 0
1095721 0
1169883 0
1216093 0
1301050 0
1316550 0
1362255 0
1421306 0
1426083 0
1429895 0
1438129 0
1446440 0
1465837 0
1483276 0
1484165 0
1502631 0
1511826 0
1541055 0
1598558 0
1599795 0
1609074 0
1637187 0
1640361 0
1666733 0
1667132 0
1671716 0
1674712 0
1677443 0
1680365 0
1682146 0
77132 0
808722 0
934866 0
944317 0
1068804 0
1074902 0
1085867 0
1115419 0
1122490 0
1135631 0
1165248 0
1175130 0
1245862 0
1280511 0
1287978 0
1328331 0
1343119 0
1348145 0
1365555 0
1373017 0
1377635 0
1387369 0
1424116 0
1427350 0
1442641 0
1444055 0
1455468 0
1510099 0
1512415 0
1513227 0
1538338 0
1543830 0
1561089 0
1576654 0
1594197 0
1600152 0
1604350 0
1604488 0
1617032 0
1620822 0
1623796 0
1624865 0
1630806 0
1633046 0
1633446 0
1633703 0
1650301 0
1656666 0

1659203 0
1662449 0
1665976 0
1667134 0
1671161 0
1672829 0
1674784 0
1676603 0
1678953 0
1680326 0
1681126 0
1682501 0
1682733 0
1684868 0
1685959 0
1686444 0
1687156 0
1688171 0
1688774 0
1688882 0
1689013 0
1689024 0
1690531 0
1690717 0
1692252 0
1692623 0
1693809 0
1694284 0
1694297 0
1694886 0
1695214 0
1695320 0
1695345 0
1695490 0
1696494 0
1696497 0
1696548 0
1696656 0
1696867 0
1697300 0
1697444 0
1697493 0
1697539 0
1697646 0
1697715 0
1697717 0
1697790 0
1697796 0
1697847 0
1697855 0
1698051 0
811407 0
872359 0
899211 0
935359 0
944733 0
1041773 0
1109767 0
1122470 0
1218749 0
1279396 0
1335325 0
1353651 0
1367786 0
1434641 0
1438574 0
1464790 0
1473174 0
1532472 0
1535677 0
1536006 0
1536446 0
1572838 0
1576584 0
1578242 0
1580677 0
1591307 0
1606134 0
1616628 0
1626220 0
1632548 0
1638022 0
1656713 0
1657516 0
1661462 0
1665518 0
1665589 0
1666024 0
1669662 0
1671811 0
1672067 0
1672201 0
1675688 0
1683182 0
1683754 0
1689872 0
1690186 0
1691804 0
1691982 0
1694079 0
1694948 0
1695344 0
1695582 0
1695658 0
1696263 0
1696438 0
1696615 0
1696628 0
1696957 0
1697360 0
1697767 0
1697791 0
1697848 0
1697882 0
1698094 0
1698146 0
1698215 0
1698220 0
1699622 0
1699803 0
1703080 0
1704107 0
1705711 0
1706248 0
811808 0
820123 0
1054522 0
1343916 0
1425165 0
1634301 0
1652391 0
1656537 0
1675762 0
1680613 0
1681662 0
1688931 0
1694896 0
1697366 0
1697725 0
1698218 0
1700286 0
1703100 0
1705929 0
1706836 0
1709698 0
1710524 0
1713520 0
1713735 0
351262 0
1019531 0
1128239 0
1133999 0
1357993 0
1386364 0
1420299 0
1557689 0
1568839 0
1578370 0
1604831 0
1615486 0
1619899 0
1631773 0
1632253 0
1632965 0
1633288 0
1633673 0
1635663 0
1652174 0
1665590 0
1679064 0
1686242 0
1688666 0
1689470 0
1698481 0
1706327 0
1706351 0
1706915 0
1708872 0
1710666 0
1711200 0
1712671 0
1713678 0
1714093 0
1714346 0
1714678 0
1716180 0
1716399 0
1719739 0
1721608 0
764739 0
837980 0
904793 0
1075444 0
1086611 0
1100710 0
1318011 0
1389544 0
1425294 0
1440771 0
1467517 0
1471265 0
1508512 0
1512073 0
1535611 0
1536557 0
1543160 0
1566089 0
1592450 0
1601384 0
1619779 0
1621855 0
1633857 0
1644329 0
1646639 0
1650373 0
1659171 0
1661140 0
1675855 0
1675884 0
1680638 0
1681004 0
1682021 0
1687832 0
1688184 0
1689829 0
1694165 0
1694283 0
1697024 0
1697162 0
1697719 0
1698819 0
1700272 0
1703208 0
1703556 0
1705655 0
1706016 0
1708001 0
1710440 0
1710539 0
1710951 0
1712686 0
1713506 0
1713936 0
1714062 0
1714267 0
1714341 0
1714506 0
1715228 0
1716539 0
1717027 0
1717479 0
1717658 0
1718982 0
1719087 0
1720336 0
1722283 0
1722436 0
1722638 0
1724090 0
1725247 0
1725910 0
1726375 0
1726673 0
1727269 0
1727342 0
1727593 0
1727993 0
1728318 0
1728355 0
1729045 0
1729048 0
1729093 0
1729096 0
1729269 0
1729299 0
1729381 0
1729428 0
1729515 0
1729516 0
1729673 0
1729677 0
1729867 0
1729869 0
1730126 0
1730456 0
1730471 0
1730477 0
1730478 0
1730521 0
1730565 0
1730574 0
1730660 0
1730808 0
1730890 0
1731123 0
1731124 0
1731134 0
1731169 0
1731372 0
1731447 0
1731466 0
1086762 0
1104329 0
1226355 0
1290162 0
1386462 0
1387941 0
1454937 0
1569452 0
1569655 0
1578299 0
1592828 0
1599637 0
1600052 0
1622757 0
1645721 0
1646343 0
1657980 0
1662212 0
1666613 0
1689874 0
1697013 0
1698777 0
1700481 0
1713558 0
1715635 0
1719307 0
1723681 0
1723925 0
1725888 0
1727710 0
1729049 0
1729051 0
1729847 0
1729848 0
1730475 0
1730709 0
1730887 0
1730959 0
1730961 0
1731132 0
1731216 0
1731275 0
1731358 0
1731359 0
1731497 0
1731671 0
1731713 0
1731878 0
1732537 0
1733456 0
1733777 0
1734460 0
1735513 0
1735605 0
1736260 0
1736736 0
1737112 0
1738720 0
1739043 0
1739728 0
1740316 0
1740729 0
83402 0
714395 0
728882 0
769954 0
838618 0
1263568 0
1276470 0
1315421 0
1415293 0
1454423 0
1486713 0
1531971 0
1544554 0
1569241 0
1589689 0
1596212 0
1598561 0
1602730 0
1617201 0
1658509 0
1664847 0
1666647 0
1672681 0
1680091 0
1692820 0
1693141 0
1697323 0
1697740 0
1697752 0
1697803 0
1697856 0
1702973 0
1706766 0
1713521 0
1716984 0
1720235 0
1722439 0
1725362 0
1727917 0
1728866 0
1729300 0
1730383 0
1730945 0
1731445 0
1731731 0
1733082 0
1734565 0
1735734 0
1738723 0
1741619 0
1742418 0
1742569 0
1744955 0
1745164 0
1748278 0
1748965 0
712537 0
855702 0
913990 0
1030815 0
1050464 0
1065350 0
1108831 0
1127889 0
1165830 0
1169069 0
1212897 0
1511847 0
1517666 0
1537276 0
1569537 0
1602224 0
1620943 0
1622852 0
1631775 0
1654033 0
1661762 0
1689007 0
1692507 0
1696802 0
1698068 0
1704677 0
1712533 0
1721568 0
1727111 0
1727573 0
1727588 0
1729094 0
1729304 0
1729866 0
1730068 0
1730575 0
1730813 0
1730815 0
1731876 0
1734398 0
1734493 0
1749890 0
1751817 0
1753219 0
1755651 0
1756959 0
1758087 0
701189 0
1010911 0
1127612 0
1135121 0
1218583 0
1302720 0
1365474 0
1389610 0
1531964 0
1535695 0
1546865 0
1554308 0
1582384 0
1652594 0
1664324 0
1697267 0
1697303 0
1698478 0
1713697 0
1736648 0
1737090 0
1740837 0
1749914 0
1750086 0
1750423 0
1750924 0
1752579 0
1759236 0
1760263 0
1760304 0
1760540 0
1761044 0
1764049 0
1764144 0
1765594 0
1765595 0
1765768 0
1766157 0
1766506 0
1766510 0
1766520 0
1766553 0
1766564 0
1766571 0
1766802 0
1766907 0
1766909 0
1766995 0
1767056 0
1767070 0
1767346 0
1767474 0
1767617 0
1767710 0
1767715 0
1767730 0
1767812 0
1767940 0
1767945 0
1767952 0
1767982 0
1768089 0
701516 0
942257 0
1053292 0
1346554 0
1520601 0
1544224 0
1549408 0
1600435 0
1606666 0
1606720 0
1623678 0
1626632 0
1643833 0
1652529 0
1694592 0
1696209 0
1706028 0
1707206 0
1708759 0
1715862 0
1717977 0
1728449 0
1728681 0
1729735 0
1729932 0
1730573 0
1730811 0
1730971 0
1733173 0
1733510 0
1743941 0
1744318 0
1753875 0
1757043 0
1757282 0
1759476 0
1759803 0
1762388 0
1764386 0
1766788 0
1766918 0
1767049 0
1767297 0
1767307 0
1767863 0
1768095 0
1768302 0
1768887 0
1769031 0
1770994 0
1771169 0
1772031 0
1772937 0
1773205 0
1774207 0
1774879 0
1776290 0
1776296 0
1133742 0
1179475 0
1346543 0
1592746 0
1656001 0
1672556 0
1715329 0
1721508 0
1725357 0
1733248 0
1767080 0
1767121 0
1511901 0
1533504 0
1694895 0
1695908 0
1659851 0
1682677 0
1761645 0
1762997 0

In [116]:
form13f_3mos["market_V_3mos"] = form13f_3mos["shares"] * form13f_3mos["pSP_CLOSE_y"]
form13f_3mos

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos
0,39276291,7195,075887109,2013-06-30,2013-08-12,47543.0,4699000.0,0.020442,43 days,Consumer Discretionary,Large-Cap Blend,100.0000,46990.000000,2013-05-01,93.5800,4.397324e+06
1,39276326,7195,863667101,2013-06-30,2013-08-12,65418.0,4231000.0,0.018406,43 days,Consumer Discretionary,Large-Cap Blend,70.7600,59793.668739,2013-05-01,65.3000,3.904527e+06
2,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000,62664.141414,2013-05-01,72.7600,4.559443e+06
3,39276293,7195,171232101,2013-06-30,2013-08-12,53980.0,4569000.0,0.019876,43 days,Consumer Discretionary,Large-Cap Growth,85.5200,53426.099158,2013-05-01,87.3000,4.664098e+06
4,39276290,7195,053015103,2013-06-30,2013-08-12,71320.0,4911000.0,0.021364,43 days,Consumer Discretionary,MidCap Growth,63.9936,76742.049205,2013-05-01,58.7369,4.507590e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326339,74236112,1776296,G0450A105,2020-03-31,2020-05-15,12700.0,361000.0,0.003124,45 days,Utilities,Large-Cap Value,22.9800,15709.312446,2020-01-31,44.1600,6.937232e+05
2326340,74236101,1776296,742718109,2020-03-31,2020-05-15,30211.0,3323000.0,0.028757,45 days,Utilities,MidCap Growth,114.6100,28993.979583,2020-01-31,124.6200,3.613230e+06
2326341,74236116,1776296,58933Y105,2020-03-31,2020-05-15,4279.0,329000.0,0.002847,45 days,Utilities,MidCap Growth,79.7800,4123.840562,2020-01-31,85.4400,3.523409e+05
2326342,74236153,1776296,30161N101,2020-03-31,2020-05-15,47585.0,1752000.0,0.015161,45 days,Utilities,MidCap Growth,35.2900,49645.792009,2020-01-31,47.5900,2.362643e+06
2326343,74236131,1776296,816851109,2020-03-31,2020-05-15,16899.0,1909000.0,0.016520,45 days,Utilities,MidCap Growth,119.2000,16015.100671,2020-01-31,160.6400,2.572666e+06

In [117]:
form13f_3mos_new = form13f_3mos.dropna()
form13f_3mos_new

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos
0,39276291,7195,075887109,2013-06-30,2013-08-12,47543.0,4699000.0,0.020442,43 days,Consumer Discretionary,Large-Cap Blend,100.0000,46990.000000,2013-05-01,93.5800,4.397324e+06
1,39276326,7195,863667101,2013-06-30,2013-08-12,65418.0,4231000.0,0.018406,43 days,Consumer Discretionary,Large-Cap Blend,70.7600,59793.668739,2013-05-01,65.3000,3.904527e+06
2,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000,62664.141414,2013-05-01,72.7600,4.559443e+06
3,39276293,7195,171232101,2013-06-30,2013-08-12,53980.0,4569000.0,0.019876,43 days,Consumer Discretionary,Large-Cap Growth,85.5200,53426.099158,2013-05-01,87.3000,4.664098e+06
4,39276290,7195,053015103,2013-06-30,2013-08-12,71320.0,4911000.0,0.021364,43 days,Consumer Discretionary,MidCap Growth,63.9936,76742.049205,2013-05-01,58.7369,4.507590e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326339,74236112,1776296,G0450A105,2020-03-31,2020-05-15,12700.0,361000.0,0.003124,45 days,Utilities,Large-Cap Value,22.9800,15709.312446,2020-01-31,44.1600,6.937232e+05
2326340,74236101,1776296,742718109,2020-03-31,2020-05-15,30211.0,3323000.0,0.028757,45 days,Utilities,MidCap Growth,114.6100,28993.979583,2020-01-31,124.6200,3.613230e+06
2326341,74236116,1776296,58933Y105,2020-03-31,2020-05-15,4279.0,329000.0,0.002847,45 days,Utilities,MidCap Growth,79.7800,4123.840562,2020-01-31,85.4400,3.523409e+05
2326342,74236153,1776296,30161N101,2020-03-31,2020-05-15,47585.0,1752000.0,0.015161,45 days,Utilities,MidCap Growth,35.2900,49645.792009,2020-01-31,47.5900,2.362643e+06
2326343,74236131,1776296,816851109,2020-03-31,2020-05-15,16899.0,1909000.0,0.016520,45 days,Utilities,MidCap Growth,119.2000,16015.100671,2020-01-31,160.6400,2.572666e+06

In [118]:
total_market_V = form13f_3mos_new.groupby(["iCIK","iPERIOD_END"],as_index=False).iMARKET_VALUE.sum()
total_market_V_3mos = form13f_3mos_new.groupby(["iCIK","iPERIOD_END"],as_index=False).market_V_3mos.sum()
Return = pd.merge(total_market_V,total_market_V_3mos, on=["iCIK","iPERIOD_END"])
Return["return"] = (Return["iMARKET_VALUE"] - Return["market_V_3mos"]) / Return["market_V_3mos"]
Return # return of each fund in each period

          iCIK iPERIOD_END  iMARKET_VALUE  market_V_3mos    return
0         7195  2013-06-30    229871000.0   2.157608e+08  0.065397
1         7195  2013-09-30    220987000.0   2.191440e+08  0.008410
2         7195  2013-12-31    244650000.0   2.355210e+08  0.038761
3         7195  2014-03-31    243537000.0   2.359490e+08  0.032159
4         7195  2014-06-30    236104000.0   2.258708e+08  0.045306
...        ...         ...            ...            ...       ...
23093  1776290  2020-03-31    220943000.0   2.568404e+08 -0.139765
23094  1776296  2019-03-31    121483000.0   1.175412e+08  0.033535
23095  1776296  2019-06-30    124451000.0   1.272546e+08 -0.022031
23096  1776296  2019-09-30    122178000.0   1.195080e+08  0.022341
23097  1776296  2020-03-31    113604000.0   1.329311e+08 -0.145392

[23098 rows x 5 columns]

In [119]:
cik_mean_returns = Return.groupby("iCIK",as_index=False)["return"].mean()
cik_mean_returns # mean return of each fund

         iCIK    return
0        7195  0.017095
1       18748  0.010671
2       19475  0.047786
3       19481  0.060120
4       21175 -0.007576
...       ...       ...
2285  1773205  0.006517
2286  1774207  0.003887
2287  1774879  0.000267
2288  1776290 -0.015332
2289  1776296 -0.027887

[2290 rows x 2 columns]

In [120]:
mean_return = cik_mean_returns["return"].mean()
mean_return # mean return of all funds

0.009510589229531633

In [121]:
def performance(row):
    if row['return'] > mean_return * 1.2:
        p = "high"
    elif row['return'] < mean_return * 0.8:
        p = "low"
    else:
        p = "medium"
    return p
cik_mean_returns["performance"] = cik_mean_returns.apply(performance, axis=1)
cik_mean_returns

         iCIK    return performance
0        7195  0.017095        high
1       18748  0.010671      medium
2       19475  0.047786        high
3       19481  0.060120        high
4       21175 -0.007576         low
...       ...       ...         ...
2285  1773205  0.006517         low
2286  1774207  0.003887         low
2287  1774879  0.000267         low
2288  1776290 -0.015332         low
2289  1776296 -0.027887         low

[2290 rows x 3 columns]

In [122]:
len(form13f_3mos["iCIK"].unique())

2292

### 4. Volatility

In [123]:
# std of period returns for each fund (Return) -> take mean
volatility = Return.groupby("iCIK",as_index=False)["return"].std()
volatility.columns = ["iCIK", "volatility"]
volatility

         iCIK  volatility
0        7195    0.049244
1       18748    0.037731
2       19475    0.038018
3       19481    0.009252
4       21175    0.081343
...       ...         ...
2285  1773205    0.072561
2286  1774207    0.075591
2287  1774879    0.061184
2288  1776290    0.083815
2289  1776296    0.081929

[2290 rows x 2 columns]

In [124]:
mean_volatility = volatility["volatility"].mean()
mean_volatility

0.06386791003851072

In [125]:
def vol(row):
    if row['volatility'] > mean_volatility * 1.2:
        v = "high"
    elif row['volatility'] < mean_volatility * 0.8:
        v = "low"
    else:
        v = "medium"
    return v
volatility["volatility group"] = volatility.apply(vol, axis=1)
volatility

         iCIK  volatility volatility group
0        7195    0.049244              low
1       18748    0.037731              low
2       19475    0.038018              low
3       19481    0.009252              low
4       21175    0.081343             high
...       ...         ...              ...
2285  1773205    0.072561           medium
2286  1774207    0.075591           medium
2287  1774879    0.061184           medium
2288  1776290    0.083815             high
2289  1776296    0.081929             high

[2290 rows x 3 columns]

### 5. Survival Time

In [126]:
period_min = form13f_3mos.groupby("iCIK",as_index=False).iPERIOD_END.min()
period_min.columns = ["iCIK", "iPERIOD_END_min"]
period_max = form13f_3mos.groupby("iCIK",as_index=False).iPERIOD_END.max()
period_max.columns = ["iCIK", "iPERIOD_END_max"]
period = pd.merge(period_min, period_max, on=["iCIK"])
period["survival time"] = period["iPERIOD_END_max"] - period["iPERIOD_END_min"]
period

         iCIK iPERIOD_END_min iPERIOD_END_max survival time
0        7195      2013-06-30      2020-03-31     2466 days
1       18748      2013-06-30      2016-09-30     1188 days
2       19475      2013-06-30      2020-03-31     2466 days
3       19481      2013-06-30      2015-03-31      639 days
4       21175      2013-06-30      2020-03-31     2466 days
...       ...             ...             ...           ...
2287  1773205      2019-03-31      2020-03-31      366 days
2288  1774207      2019-03-31      2020-03-31      366 days
2289  1774879      2019-03-31      2020-03-31      366 days
2290  1776290      2019-03-31      2020-03-31      366 days
2291  1776296      2019-03-31      2020-03-31      366 days

[2292 rows x 4 columns]

In [132]:
mean_survival = period["survival time"].mean()
mean_survival

Timedelta('1388 days 01:46:10.680628272')

In [133]:
def survival(row):
    if row['survival time'] > mean_survival * 1.5: # no fund survives twice the mean survival time
        s = "high"
    elif row['survival time'] < mean_survival * 0.8:
        s = "low"
    else:
        s = "medium"
    return s
period["survival group"] = period.apply(survival, axis=1)
period

         iCIK iPERIOD_END_min iPERIOD_END_max survival time survival group
0        7195      2013-06-30      2020-03-31     2466 days           high
1       18748      2013-06-30      2016-09-30     1188 days         medium
2       19475      2013-06-30      2020-03-31     2466 days           high
3       19481      2013-06-30      2015-03-31      639 days            low
4       21175      2013-06-30      2020-03-31     2466 days           high
...       ...             ...             ...           ...            ...
2287  1773205      2019-03-31      2020-03-31      366 days            low
2288  1774207      2019-03-31      2020-03-31      366 days            low
2289  1774879      2019-03-31      2020-03-31      366 days            low
2290  1776290      2019-03-31      2020-03-31      366 days            low
2291  1776296      2019-03-31      2020-03-31      366 days            low

[2292 rows x 5 columns]

### 6. Idiosyncratic Risk

In [134]:
####### WT?????????

### 7. Inflow & Turnover

In [205]:
form13f_3mos

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos
0,39276291,7195,075887109,2013-06-30,2013-08-12,47543.0,4699000.0,0.020442,43 days,Consumer Discretionary,Large-Cap Blend,100.0000,46990.000000,2013-05-01,93.5800,4.397324e+06
1,39276326,7195,863667101,2013-06-30,2013-08-12,65418.0,4231000.0,0.018406,43 days,Consumer Discretionary,Large-Cap Blend,70.7600,59793.668739,2013-05-01,65.3000,3.904527e+06
2,39276306,7195,437076102,2013-06-30,2013-08-12,64059.0,4963000.0,0.021590,43 days,Consumer Discretionary,Large-Cap Growth,79.2000,62664.141414,2013-05-01,72.7600,4.559443e+06
3,39276293,7195,171232101,2013-06-30,2013-08-12,53980.0,4569000.0,0.019876,43 days,Consumer Discretionary,Large-Cap Growth,85.5200,53426.099158,2013-05-01,87.3000,4.664098e+06
4,39276290,7195,053015103,2013-06-30,2013-08-12,71320.0,4911000.0,0.021364,43 days,Consumer Discretionary,MidCap Growth,63.9936,76742.049205,2013-05-01,58.7369,4.507590e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326339,74236112,1776296,G0450A105,2020-03-31,2020-05-15,12700.0,361000.0,0.003124,45 days,Utilities,Large-Cap Value,22.9800,15709.312446,2020-01-31,44.1600,6.937232e+05
2326340,74236101,1776296,742718109,2020-03-31,2020-05-15,30211.0,3323000.0,0.028757,45 days,Utilities,MidCap Growth,114.6100,28993.979583,2020-01-31,124.6200,3.613230e+06
2326341,74236116,1776296,58933Y105,2020-03-31,2020-05-15,4279.0,329000.0,0.002847,45 days,Utilities,MidCap Growth,79.7800,4123.840562,2020-01-31,85.4400,3.523409e+05
2326342,74236153,1776296,30161N101,2020-03-31,2020-05-15,47585.0,1752000.0,0.015161,45 days,Utilities,MidCap Growth,35.2900,49645.792009,2020-01-31,47.5900,2.362643e+06
2326343,74236131,1776296,816851109,2020-03-31,2020-05-15,16899.0,1909000.0,0.016520,45 days,Utilities,MidCap Growth,119.2000,16015.100671,2020-01-31,160.6400,2.572666e+06

In [206]:
############################################ ex. iCIK == 7195 ##################################################
tp = form13f_3mos[form13f_3mos['iCIK'] == 7195]
tp = tp.sort_values(by = ["iCUSIP","iPERIOD_END"])
tp['buy'] = 0
tp

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos,buy
1629212,65860591,7195,00206R102,2018-06-30,2018-07-19,29025.0,932000.0,0.004254,19 days,Communications,MidCap Value,31.2700,29804.924848,2018-05-01,32.5400,9.698523e+05,0
1629253,65860611,7195,00287Y109,2018-06-30,2018-07-19,3656.0,339000.0,0.001547,19 days,Materials,Small-Cap Growth,89.9500,3768.760422,2018-05-01,102.0700,3.846774e+05,0
1737377,67310509,7195,00287Y109,2018-09-30,2018-10-16,4272.0,404000.0,0.001739,16 days,Materials,Small-Cap Growth,91.9100,4395.604396,2018-08-01,93.9100,4.127912e+05,0
1845434,68489929,7195,00287Y109,2018-12-31,2019-02-06,4994.0,460000.0,0.002402,37 days,Materials,Small-Cap Growth,79.0800,5816.894284,2018-11-01,80.2100,4.665731e+05,0
1737394,67310520,7195,00724F101,2018-09-30,2018-10-16,1290.0,348000.0,0.001498,16 days,Technology,Large-Cap Growth,260.6700,1335.021291,2018-08-01,248.0100,3.310986e+05,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
47,39276308,7195,G47791101,2013-06-30,2013-08-12,85988.0,4774000.0,0.020768,43 days,Technology,MidCap Growth,48.8932,97641.389805,2013-05-01,41.6114,4.062995e+06,0
54443,40312088,7195,G47791101,2013-09-30,2013-10-16,77953.0,5062000.0,0.022906,16 days,Technology,MidCap Growth,50.4707,100295.815196,2013-08-01,49.4828,4.962918e+06,0
115540,48527304,7195,G47791101,2013-12-31,2014-01-21,77953.0,4802000.0,0.019541,21 days,Technology,MidCap Growth,62.0700,77364.266151,2013-11-01,53.9682,4.175210e+06,0
188645,48825005,7195,G47791101,2014-03-31,2014-04-14,67158.0,3844000.0,0.015784,14 days,Technology,MidCap Growth,55.2600,69562.070214,2014-01-30,59.0300,4.106249e+06,0
266293,49986220,7195,G47791101,2014-06-30,2014-07-21,10438.0,652000.0,0.002726,21 days,Technology,MidCap Growth,61.8500,10541.632983,2014-05-01,59.9600,6.320763e+05,0

In [207]:
stocks = tp['iCUSIP'].unique()
for i in stocks:
    temp = tp[tp['iCUSIP'] == i]
    if len(temp) == 1:
        tp.at[temp.index[0], 'buy'] = temp.iloc[0]['iMARKET_VALUE']
    else:
        diff = np.diff(temp['iMARKET_VALUE'])
        diff = np.insert(diff, 0, temp.iloc[0]['iMARKET_VALUE'])
        for j in range(len(temp)):
            tp.at[temp.index[j],'buy'] = diff[j]
            
tp = tp.sort_values(by='iPERIOD_END')
tp

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos,buy
16,39276311,7195,460146103,2013-06-30,2013-08-12,97765.0,4332000.0,0.018845,43 days,Energy,Small-Cap Value,47.8214,90587.059350,2013-05-01,45.5107,4.122680e+06,4332000
8,39276314,7195,494368103,2013-06-30,2013-08-12,49241.0,4783000.0,0.020807,43 days,Consumer Staples,Large-Cap Value,94.1450,50804.609910,2013-05-01,98.9241,5.025800e+06,4783000
38,39276288,7195,037833100,2013-06-30,2013-08-12,10532.0,4176000.0,0.018167,43 days,Technology,Large-Cap Growth,66.7657,62547.086303,2013-05-01,62.7557,3.925186e+06,4176000
42,39276315,7195,580135101,2013-06-30,2013-08-12,46852.0,4638000.0,0.020176,43 days,Technology,Large-Cap Growth,97.0400,47794.723825,2013-05-01,101.3800,4.845429e+06,4638000
41,39276316,7195,594918104,2013-06-30,2013-08-12,150622.0,5203000.0,0.022634,43 days,Technology,Large-Cap Growth,32.8700,158290.234256,2013-05-01,32.7200,5.179256e+06,5203000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2221883,73314143,7195,92826C839,2020-03-31,2020-04-24,24505.0,3948000.0,0.023493,24 days,Technology,Large-Cap Growth,167.3200,23595.505618,2020-01-31,198.9700,4.694798e+06,-762000
2221897,73314159,7195,907818108,2020-03-31,2020-04-24,23745.0,3349000.0,0.019929,24 days,Technology,MidCap Growth,156.0900,21455.570504,2020-01-31,179.4200,3.849558e+06,-663000
2221885,73314152,7195,67066G104,2020-03-31,2020-04-24,18112.0,4774000.0,0.028408,24 days,Technology,Large-Cap Growth,289.5900,16485.375876,2020-01-31,236.4300,3.897637e+06,76000
2221870,73314162,7195,291011104,2020-03-31,2020-04-24,40905.0,1949000.0,0.011598,24 days,Materials,Small-Cap Blend,53.8200,36213.303605,2020-01-31,71.6300,2.593959e+06,-883000
2221882,73314180,7195,337738108,2020-03-31,2020-04-24,4371.0,415000.0,0.002469,24 days,Technology,Large-Cap Growth,96.2900,4309.897186,2020-01-31,118.6100,5.111969e+05,415000

In [208]:
tp[(tp["iCUSIP"] == "882508104") & (tp["iPERIOD_END"] == datetime.date(2020,3,31))]

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos,buy
2221842,73314161,7195,882508104,2020-03-31,2020-04-24,33320.0,3330000.0,0.019815,24 days,Consumer Discretionary,Large-Cap Blend,113.93,29228.473624,2020-01-31,120.65,3.526415e+06,-1153000

In [209]:
temp = tp['buy'].values
zeros = np.zeros_like(temp)
tp['sell'] = np.maximum(zeros, -temp)
tp['buy'] = np.maximum(zeros, temp)
tp

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos,buy,sell
16,39276311,7195,460146103,2013-06-30,2013-08-12,97765.0,4332000.0,0.018845,43 days,Energy,Small-Cap Value,47.8214,90587.059350,2013-05-01,45.5107,4.122680e+06,4332000,0
8,39276314,7195,494368103,2013-06-30,2013-08-12,49241.0,4783000.0,0.020807,43 days,Consumer Staples,Large-Cap Value,94.1450,50804.609910,2013-05-01,98.9241,5.025800e+06,4783000,0
38,39276288,7195,037833100,2013-06-30,2013-08-12,10532.0,4176000.0,0.018167,43 days,Technology,Large-Cap Growth,66.7657,62547.086303,2013-05-01,62.7557,3.925186e+06,4176000,0
42,39276315,7195,580135101,2013-06-30,2013-08-12,46852.0,4638000.0,0.020176,43 days,Technology,Large-Cap Growth,97.0400,47794.723825,2013-05-01,101.3800,4.845429e+06,4638000,0
41,39276316,7195,594918104,2013-06-30,2013-08-12,150622.0,5203000.0,0.022634,43 days,Technology,Large-Cap Growth,32.8700,158290.234256,2013-05-01,32.7200,5.179256e+06,5203000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2221883,73314143,7195,92826C839,2020-03-31,2020-04-24,24505.0,3948000.0,0.023493,24 days,Technology,Large-Cap Growth,167.3200,23595.505618,2020-01-31,198.9700,4.694798e+06,0,762000
2221897,73314159,7195,907818108,2020-03-31,2020-04-24,23745.0,3349000.0,0.019929,24 days,Technology,MidCap Growth,156.0900,21455.570504,2020-01-31,179.4200,3.849558e+06,0,663000
2221885,73314152,7195,67066G104,2020-03-31,2020-04-24,18112.0,4774000.0,0.028408,24 days,Technology,Large-Cap Growth,289.5900,16485.375876,2020-01-31,236.4300,3.897637e+06,76000,0
2221870,73314162,7195,291011104,2020-03-31,2020-04-24,40905.0,1949000.0,0.011598,24 days,Materials,Small-Cap Blend,53.8200,36213.303605,2020-01-31,71.6300,2.593959e+06,0,883000
2221882,73314180,7195,337738108,2020-03-31,2020-04-24,4371.0,415000.0,0.002469,24 days,Technology,Large-Cap Growth,96.2900,4309.897186,2020-01-31,118.6100,5.111969e+05,415000,0

In [210]:
grouped = tp.groupby(["iPERIOD_END"]).sum()
grouped['turnover'] = np.minimum(grouped['buy'], grouped['sell'])/grouped['iMARKET_VALUE']
grouped = grouped['turnover']
grouped = grouped.reset_index()
grouped['iCIK'] = 7195
grouped

   iPERIOD_END  turnover  iCIK
0   2013-06-30  0.000000  7195
1   2013-09-30  0.025201  7195
2   2013-12-31  0.001058  7195
3   2014-03-31  0.026546  7195
4   2014-06-30  0.050941  7195
5   2014-09-30  0.028756  7195
6   2014-12-31  0.015475  7195
7   2015-03-31  0.012458  7195
8   2015-06-30  0.020293  7195
9   2015-09-30  0.047148  7195
10  2015-12-31  0.016916  7195
11  2016-03-31  0.026190  7195
12  2016-06-30  0.026386  7195
13  2016-09-30  0.031026  7195
14  2016-12-31  0.023662  7195
15  2017-03-31  0.001995  7195
16  2017-06-30  0.015492  7195
17  2017-09-30  0.001252  7195
18  2017-12-31  0.008225  7195
19  2018-03-31  0.004520  7195
20  2018-06-30  0.028717  7195
21  2018-09-30  0.003736  7195
22  2018-12-31  0.004214  7195
23  2019-03-31  0.003679  7195
24  2019-09-30  0.038759  7195
25  2020-03-31  0.059607  7195

In [211]:
##################################################################################################################

In [226]:
# Quarterly turnover for each fund
def turnover_one_fund(df, index):
    tp = df[df['iCIK'] == index]
    tp = tp.sort_values(by = ["iCUSIP","iPERIOD_END"])
    tp['buy'] = 0
    stocks = tp['iCUSIP'].unique()
    for i in stocks:
        temp = tp[tp['iCUSIP'] == i]
        if len(temp) == 1:
            tp.at[temp.index[0], 'buy'] = temp.iloc[0]['iMARKET_VALUE']
        else:
            diff = np.diff(temp['iMARKET_VALUE'])
            diff = np.insert(diff, 0, temp.iloc[0]['iMARKET_VALUE'])
            for j in range(len(temp)):
                tp.at[temp.index[j],'buy'] = diff[j]
    tp = tp.sort_values(by='iPERIOD_END')
    temp = tp['buy'].values
    zeros = np.zeros_like(temp)
    tp['sell'] = np.maximum(zeros, -temp)
    tp['buy'] = np.maximum(zeros, temp)
    grouped = tp.groupby(["iPERIOD_END"]).sum()
    grouped['turnover'] = np.minimum(grouped['buy'], grouped['sell'])/grouped['iMARKET_VALUE']
    grouped = grouped['turnover']
    grouped = grouped.reset_index()
    grouped['iCIK'] = index
    return tp, grouped

In [227]:
form13f_inflow = []
Turnover = []

for i in form13f_3mos['iCIK'].unique():
    inflow, turnover = turnover_one_fund(form13f_3mos, i)
    form13f_inflow.append(inflow)
    Turnover.append(turnover)

form13f_inflow = pd.concat(form13f_inflow)
Turnover = pd.concat(Turnover)

In [228]:
form13f_inflow

,iRECORD_ID,iCIK,iCUSIP,iPERIOD_END,iFILING_DATE,iQTY,iMARKET_VALUE,iLONG_FRACTION,FILING_INTERVAL,sector,value_size,pSP_CLOSE_x,shares,filing_3mos,pSP_CLOSE_y,market_V_3mos,buy,sell
16,39276311,7195,460146103,2013-06-30,2013-08-12,97765.0,4332000.0,0.018845,43 days,Energy,Small-Cap Value,47.8214,90587.059350,2013-05-01,45.5107,4.122680e+06,4332000,0
8,39276314,7195,494368103,2013-06-30,2013-08-12,49241.0,4783000.0,0.020807,43 days,Consumer Staples,Large-Cap Value,94.1450,50804.609910,2013-05-01,98.9241,5.025800e+06,4783000,0
38,39276288,7195,037833100,2013-06-30,2013-08-12,10532.0,4176000.0,0.018167,43 days,Technology,Large-Cap Growth,66.7657,62547.086303,2013-05-01,62.7557,3.925186e+06,4176000,0
42,39276315,7195,580135101,2013-06-30,2013-08-12,46852.0,4638000.0,0.020176,43 days,Technology,Large-Cap Growth,97.0400,47794.723825,2013-05-01,101.3800,4.845429e+06,4638000,0
41,39276316,7195,594918104,2013-06-30,2013-08-12,150622.0,5203000.0,0.022634,43 days,Technology,Large-Cap Growth,32.8700,158290.234256,2013-05-01,32.7200,5.179256e+06,5203000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2326317,74236102,1776296,46138E511,2020-03-31,2020-05-15,16113.0,212000.0,0.001835,45 days,NA,NA,NaN,NaN,2020-01-31,NaN,NaN,0,44000
2326307,74236138,1776296,231021106,2020-03-31,2020-05-15,18579.0,2514000.0,0.021756,45 days,Materials,Small-Cap Blend,155.6400,16152.659985,2020-01-31,159.9700,2.583941e+06,0,343000
2326309,74236147,1776296,88579Y101,2020-03-31,2020-05-15,3279.0,448000.0,0.003877,45 days,Materials,Small-Cap Value,138.6900,3230.225683,2020-01-31,158.6600,5.125076e+05,0,157000
2326335,74236120,1776296,254543101,2020-03-31,2020-05-15,75908.0,3085000.0,0.026697,45 days,Technology,MidCap Growth,43.7000,70594.965675,2020-01-31,51.6400,3.645524e+06,74000,0
2326312,74236158,1776296,59156R108,2020-03-31,2020-05-15,66657.0,2038000.0,0.017636,45 days,Materials,Small-Cap Value,31.7200,64249.684741,2020-01-31,49.7100,3.193852e+06,0,768000

In [229]:
Turnover.sort_values(by='iPERIOD_END')
Turnover # turnover for each fund in each period

   iPERIOD_END  turnover     iCIK
0   2013-06-30  0.000000     7195
1   2013-09-30  0.025201     7195
2   2013-12-31  0.001058     7195
3   2014-03-31  0.026546     7195
4   2014-06-30  0.050941     7195
..         ...       ...      ...
3   2020-03-31  0.095961  1776290
0   2019-03-31  0.000000  1776296
1   2019-06-30  0.038541  1776296
2   2019-09-30  0.057745  1776296
3   2020-03-31  0.192997  1776296

[27709 rows x 3 columns]

In [230]:
turnover_median = Turnover.groupby('iPERIOD_END').median()
turnover_median

             turnover       iCIK
iPERIOD_END
2013-06-30   0.000000  1352860.0
2013-09-30   0.028734  1362761.5
2013-12-31   0.013003  1398057.5
2014-03-31   0.038472  1411512.0
2014-06-30   0.033343  1423045.0
2014-09-30   0.046169  1419786.0
2014-12-31   0.044429  1424473.5
2015-03-31   0.047587  1430048.0
2015-06-30   0.042806  1431099.5
2015-09-30   0.062034  1413234.5
2015-12-31   0.042704  1441909.5
2016-03-31   0.049266  1455176.0
2016-06-30   0.040464  1482171.0
2016-09-30   0.041852  1483430.5
2016-12-31   0.047101  1510859.0
2017-03-31   0.037590  1511550.0
2017-06-30   0.035771  1484372.5
2017-09-30   0.032278  1519676.0
2017-12-31   0.032208  1544107.5
2018-03-31   0.051296  1548675.0
2018-06-30   0.040752  1560528.5
2018-09-30   0.032252  1561784.0
2018-12-31   0.079303  1568788.0
2019-03-31   0.056948  1569453.0
2019-06-30   0.038641  1569161.0
2019-09-30   0.045091  1576053.0
2020-03-31   0.117231  1568389.0

In [231]:
f = lambda row : row['turnover'] > turnover_median.loc[row['iPERIOD_END']]['turnover']

In [232]:
Turnover['greater'] = Turnover.apply(f, axis = 1)
Turnover.sort_values(by='iPERIOD_END')
Turnover

   iPERIOD_END  turnover     iCIK  greater
0   2013-06-30  0.000000     7195    False
1   2013-09-30  0.025201     7195    False
2   2013-12-31  0.001058     7195    False
3   2014-03-31  0.026546     7195    False
4   2014-06-30  0.050941     7195     True
..         ...       ...      ...      ...
3   2020-03-31  0.095961  1776290    False
0   2019-03-31  0.000000  1776296    False
1   2019-06-30  0.038541  1776296    False
2   2019-09-30  0.057745  1776296     True
3   2020-03-31  0.192997  1776296     True

[27709 rows x 4 columns]